/* data.c generated by valac 0.32.0, the Vala compiler
 * generated from data.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gxml/gxml.h>
#include <stdlib.h>
#include <string.h>


#define TILED_TYPE_DATA (tiled_data_get_type ())
#define TILED_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_DATA, TiledData))
#define TILED_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_DATA, TiledDataClass))
#define TILED_IS_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_DATA))
#define TILED_IS_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_DATA))
#define TILED_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_DATA, TiledDataClass))

typedef struct _TiledData TiledData;
typedef struct _TiledDataClass TiledDataClass;
typedef struct _TiledDataPrivate TiledDataPrivate;

#define TILED_TYPE_TILE (tiled_tile_get_type ())
#define TILED_TILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_TILE, TiledTile))
#define TILED_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_TILE, TiledTileClass))
#define TILED_IS_TILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_TILE))
#define TILED_IS_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_TILE))
#define TILED_TILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_TILE, TiledTileClass))

typedef struct _TiledTile TiledTile;
typedef struct _TiledTileClass TiledTileClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _TiledData {
	GXmlSerializableObjectModel parent_instance;
	TiledDataPrivate * priv;
};

struct _TiledDataClass {
	GXmlSerializableObjectModelClass parent_class;
};

struct _TiledDataPrivate {
	GXmlSerializableArrayList* _tiles;
};


static gpointer tiled_data_parent_class = NULL;

GType tiled_data_get_type (void) G_GNUC_CONST;
GType tiled_tile_get_type (void) G_GNUC_CONST;
#define TILED_DATA_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TILED_TYPE_DATA, TiledDataPrivate))
enum  {
	TILED_DATA_DUMMY_PROPERTY,
	TILED_DATA_TILES
};
static gchar* tiled_data_real_node_name (GXmlSerializableObjectModel* base);
static gchar* tiled_data_real_to_string (GXmlSerializableObjectModel* base);
TiledData* tiled_data_new (void);
TiledData* tiled_data_construct (GType object_type);
GXmlSerializableArrayList* tiled_data_get_tiles (TiledData* self);
void tiled_data_set_tiles (TiledData* self, GXmlSerializableArrayList* value);
static void tiled_data_finalize (GObject* obj);
static void _vala_tiled_data_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_tiled_data_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gchar* tiled_data_real_node_name (GXmlSerializableObjectModel* base) {
	TiledData * self;
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	self = (TiledData*) base;
	_tmp0_ = g_strdup ("Data");
	result = _tmp0_;
	return result;
}


static gchar* tiled_data_real_to_string (GXmlSerializableObjectModel* base) {
	TiledData * self;
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	self = (TiledData*) base;
	_tmp0_ = g_strdup ("Data: ");
	result = _tmp0_;
	return result;
}


TiledData* tiled_data_construct (GType object_type) {
	TiledData * self = NULL;
	self = (TiledData*) gxml_serializable_object_model_construct (object_type);
	return self;
}


TiledData* tiled_data_new (void) {
	return tiled_data_construct (TILED_TYPE_DATA);
}


GXmlSerializableArrayList* tiled_data_get_tiles (TiledData* self) {
	GXmlSerializableArrayList* result;
	GXmlSerializableArrayList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tiles;
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void tiled_data_set_tiles (TiledData* self, GXmlSerializableArrayList* value) {
	GXmlSerializableArrayList* _tmp0_ = NULL;
	GXmlSerializableArrayList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_tiles);
	self->priv->_tiles = _tmp1_;
	g_object_notify ((GObject *) self, "tiles");
}


static void tiled_data_class_init (TiledDataClass * klass) {
	tiled_data_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TiledDataPrivate));
	((GXmlSerializableObjectModelClass *) klass)->node_name = tiled_data_real_node_name;
	((GXmlSerializableObjectModelClass *) klass)->to_string = tiled_data_real_to_string;
	G_OBJECT_CLASS (klass)->get_property = _vala_tiled_data_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_tiled_data_set_property;
	G_OBJECT_CLASS (klass)->finalize = tiled_data_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_DATA_TILES, g_param_spec_object ("tiles", "tiles", "tiles", GXML_TYPE_SERIALIZABLE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void tiled_data_instance_init (TiledData * self) {
	GXmlSerializableArrayList* _tmp0_ = NULL;
	self->priv = TILED_DATA_GET_PRIVATE (self);
	_tmp0_ = gxml_serializable_array_list_new (TILED_TYPE_TILE, (GBoxedCopyFunc) g_object_ref, g_object_unref);
	self->priv->_tiles = _tmp0_;
}


static void tiled_data_finalize (GObject* obj) {
	TiledData * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TILED_TYPE_DATA, TiledData);
	_g_object_unref0 (self->priv->_tiles);
	G_OBJECT_CLASS (tiled_data_parent_class)->finalize (obj);
}


GType tiled_data_get_type (void) {
	static volatile gsize tiled_data_type_id__volatile = 0;
	if (g_once_init_enter (&tiled_data_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TiledDataClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tiled_data_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TiledData), 0, (GInstanceInitFunc) tiled_data_instance_init, NULL };
		GType tiled_data_type_id;
		tiled_data_type_id = g_type_register_static (GXML_TYPE_SERIALIZABLE_OBJECT_MODEL, "TiledData", &g_define_type_info, 0);
		g_once_init_leave (&tiled_data_type_id__volatile, tiled_data_type_id);
	}
	return tiled_data_type_id__volatile;
}


static void _vala_tiled_data_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	TiledData * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TILED_TYPE_DATA, TiledData);
	switch (property_id) {
		case TILED_DATA_TILES:
		g_value_set_object (value, tiled_data_get_tiles (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_tiled_data_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	TiledData * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TILED_TYPE_DATA, TiledData);
	switch (property_id) {
		case TILED_DATA_TILES:
		tiled_data_set_tiles (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



