/* layer.c generated by valac 0.32.0, the Vala compiler
 * generated from layer.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gxml/gxml.h>
#include <stdlib.h>
#include <string.h>


#define TILED_TYPE_LAYER (tiled_layer_get_type ())
#define TILED_LAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_LAYER, TiledLayer))
#define TILED_LAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_LAYER, TiledLayerClass))
#define TILED_IS_LAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_LAYER))
#define TILED_IS_LAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_LAYER))
#define TILED_LAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_LAYER, TiledLayerClass))

typedef struct _TiledLayer TiledLayer;
typedef struct _TiledLayerClass TiledLayerClass;
typedef struct _TiledLayerPrivate TiledLayerPrivate;

#define TILED_TYPE_DATA (tiled_data_get_type ())
#define TILED_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_DATA, TiledData))
#define TILED_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_DATA, TiledDataClass))
#define TILED_IS_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_DATA))
#define TILED_IS_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_DATA))
#define TILED_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_DATA, TiledDataClass))

typedef struct _TiledData TiledData;
typedef struct _TiledDataClass TiledDataClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _TiledLayer {
	GXmlSerializableObjectModel parent_instance;
	TiledLayerPrivate * priv;
};

struct _TiledLayerClass {
	GXmlSerializableObjectModelClass parent_class;
};

struct _TiledLayerPrivate {
	gchar* _name;
	gint _width;
	gint _height;
	TiledData* _data;
};


static gpointer tiled_layer_parent_class = NULL;

GType tiled_layer_get_type (void) G_GNUC_CONST;
GType tiled_data_get_type (void) G_GNUC_CONST;
#define TILED_LAYER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TILED_TYPE_LAYER, TiledLayerPrivate))
enum  {
	TILED_LAYER_DUMMY_PROPERTY,
	TILED_LAYER_NAME,
	TILED_LAYER_WIDTH,
	TILED_LAYER_HEIGHT,
	TILED_LAYER_DATA
};
static gchar* tiled_layer_real_node_name (GXmlSerializableObjectModel* base);
static gchar* tiled_layer_real_to_string (GXmlSerializableObjectModel* base);
const gchar* tiled_layer_get_name (TiledLayer* self);
gint tiled_layer_get_width (TiledLayer* self);
gint tiled_layer_get_height (TiledLayer* self);
TiledLayer* tiled_layer_new (void);
TiledLayer* tiled_layer_construct (GType object_type);
void tiled_layer_set_name (TiledLayer* self, const gchar* value);
void tiled_layer_set_width (TiledLayer* self, gint value);
void tiled_layer_set_height (TiledLayer* self, gint value);
TiledData* tiled_layer_get_data (TiledLayer* self);
void tiled_layer_set_data (TiledLayer* self, TiledData* value);
static void tiled_layer_finalize (GObject* obj);
static void _vala_tiled_layer_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_tiled_layer_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gchar* tiled_layer_real_node_name (GXmlSerializableObjectModel* base) {
	TiledLayer * self;
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	self = (TiledLayer*) base;
	_tmp0_ = g_strdup ("Layer");
	result = _tmp0_;
	return result;
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static gchar* tiled_layer_real_to_string (GXmlSerializableObjectModel* base) {
	TiledLayer * self;
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	self = (TiledLayer*) base;
	_tmp0_ = self->priv->_name;
	_tmp1_ = string_to_string (_tmp0_);
	_tmp2_ = self->priv->_width;
	_tmp3_ = g_strdup_printf ("%i", _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = self->priv->_height;
	_tmp6_ = g_strdup_printf ("%i", _tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strconcat ("Layer: ", _tmp1_, " ", _tmp4_, " ", _tmp7_, NULL);
	_tmp9_ = _tmp8_;
	_g_free0 (_tmp7_);
	_g_free0 (_tmp4_);
	result = _tmp9_;
	return result;
}


TiledLayer* tiled_layer_construct (GType object_type) {
	TiledLayer * self = NULL;
	self = (TiledLayer*) gxml_serializable_object_model_construct (object_type);
	return self;
}


TiledLayer* tiled_layer_new (void) {
	return tiled_layer_construct (TILED_TYPE_LAYER);
}


const gchar* tiled_layer_get_name (TiledLayer* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}


void tiled_layer_set_name (TiledLayer* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp1_;
	g_object_notify ((GObject *) self, "name");
}


gint tiled_layer_get_width (TiledLayer* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_width;
	result = _tmp0_;
	return result;
}


void tiled_layer_set_width (TiledLayer* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_width = _tmp0_;
	g_object_notify ((GObject *) self, "width");
}


gint tiled_layer_get_height (TiledLayer* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_height;
	result = _tmp0_;
	return result;
}


void tiled_layer_set_height (TiledLayer* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_height = _tmp0_;
	g_object_notify ((GObject *) self, "height");
}


TiledData* tiled_layer_get_data (TiledLayer* self) {
	TiledData* result;
	TiledData* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_data;
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void tiled_layer_set_data (TiledLayer* self, TiledData* value) {
	TiledData* _tmp0_ = NULL;
	TiledData* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_data);
	self->priv->_data = _tmp1_;
	g_object_notify ((GObject *) self, "data");
}


static void tiled_layer_class_init (TiledLayerClass * klass) {
	tiled_layer_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TiledLayerPrivate));
	((GXmlSerializableObjectModelClass *) klass)->node_name = tiled_layer_real_node_name;
	((GXmlSerializableObjectModelClass *) klass)->to_string = tiled_layer_real_to_string;
	G_OBJECT_CLASS (klass)->get_property = _vala_tiled_layer_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_tiled_layer_set_property;
	G_OBJECT_CLASS (klass)->finalize = tiled_layer_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_LAYER_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_LAYER_WIDTH, g_param_spec_int ("width", "width", "width", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_LAYER_HEIGHT, g_param_spec_int ("height", "height", "height", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_LAYER_DATA, g_param_spec_object ("data", "data", "data", TILED_TYPE_DATA, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void tiled_layer_instance_init (TiledLayer * self) {
	self->priv = TILED_LAYER_GET_PRIVATE (self);
}


static void tiled_layer_finalize (GObject* obj) {
	TiledLayer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TILED_TYPE_LAYER, TiledLayer);
	_g_free0 (self->priv->_name);
	_g_object_unref0 (self->priv->_data);
	G_OBJECT_CLASS (tiled_layer_parent_class)->finalize (obj);
}


GType tiled_layer_get_type (void) {
	static volatile gsize tiled_layer_type_id__volatile = 0;
	if (g_once_init_enter (&tiled_layer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TiledLayerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tiled_layer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TiledLayer), 0, (GInstanceInitFunc) tiled_layer_instance_init, NULL };
		GType tiled_layer_type_id;
		tiled_layer_type_id = g_type_register_static (GXML_TYPE_SERIALIZABLE_OBJECT_MODEL, "TiledLayer", &g_define_type_info, 0);
		g_once_init_leave (&tiled_layer_type_id__volatile, tiled_layer_type_id);
	}
	return tiled_layer_type_id__volatile;
}


static void _vala_tiled_layer_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	TiledLayer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TILED_TYPE_LAYER, TiledLayer);
	switch (property_id) {
		case TILED_LAYER_NAME:
		g_value_set_string (value, tiled_layer_get_name (self));
		break;
		case TILED_LAYER_WIDTH:
		g_value_set_int (value, tiled_layer_get_width (self));
		break;
		case TILED_LAYER_HEIGHT:
		g_value_set_int (value, tiled_layer_get_height (self));
		break;
		case TILED_LAYER_DATA:
		g_value_set_object (value, tiled_layer_get_data (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_tiled_layer_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	TiledLayer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TILED_TYPE_LAYER, TiledLayer);
	switch (property_id) {
		case TILED_LAYER_NAME:
		tiled_layer_set_name (self, g_value_get_string (value));
		break;
		case TILED_LAYER_WIDTH:
		tiled_layer_set_width (self, g_value_get_int (value));
		break;
		case TILED_LAYER_HEIGHT:
		tiled_layer_set_height (self, g_value_get_int (value));
		break;
		case TILED_LAYER_DATA:
		tiled_layer_set_data (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



