/* map.c generated by valac 0.32.0, the Vala compiler
 * generated from map.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gxml/gxml.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_rect.h>
#include <gee.h>


#define TILED_TYPE_MAP (tiled_map_get_type ())
#define TILED_MAP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_MAP, TiledMap))
#define TILED_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_MAP, TiledMapClass))
#define TILED_IS_MAP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_MAP))
#define TILED_IS_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_MAP))
#define TILED_MAP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_MAP, TiledMapClass))

typedef struct _TiledMap TiledMap;
typedef struct _TiledMapClass TiledMapClass;
typedef struct _TiledMapPrivate TiledMapPrivate;

#define TILED_MAP_TYPE_ORIENTATION (tiled_map_orientation_get_type ())

#define TILED_TYPE_TILESET (tiled_tileset_get_type ())
#define TILED_TILESET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_TILESET, TiledTileset))
#define TILED_TILESET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_TILESET, TiledTilesetClass))
#define TILED_IS_TILESET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_TILESET))
#define TILED_IS_TILESET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_TILESET))
#define TILED_TILESET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_TILESET, TiledTilesetClass))

typedef struct _TiledTileset TiledTileset;
typedef struct _TiledTilesetClass TiledTilesetClass;

#define TILED_TYPE_LAYER (tiled_layer_get_type ())
#define TILED_LAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_LAYER, TiledLayer))
#define TILED_LAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_LAYER, TiledLayerClass))
#define TILED_IS_LAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_LAYER))
#define TILED_IS_LAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_LAYER))
#define TILED_LAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_LAYER, TiledLayerClass))

typedef struct _TiledLayer TiledLayer;
typedef struct _TiledLayerClass TiledLayerClass;

#define TILED_TYPE_OBJECTGROUP (tiled_objectgroup_get_type ())
#define TILED_OBJECTGROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_OBJECTGROUP, TiledObjectgroup))
#define TILED_OBJECTGROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_OBJECTGROUP, TiledObjectgroupClass))
#define TILED_IS_OBJECTGROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_OBJECTGROUP))
#define TILED_IS_OBJECTGROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_OBJECTGROUP))
#define TILED_OBJECTGROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_OBJECTGROUP, TiledObjectgroupClass))

typedef struct _TiledObjectgroup TiledObjectgroup;
typedef struct _TiledObjectgroupClass TiledObjectgroupClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TILED_TYPE_TILE (tiled_tile_get_type ())
#define TILED_TILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_TILE, TiledTile))
#define TILED_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_TILE, TiledTileClass))
#define TILED_IS_TILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_TILE))
#define TILED_IS_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_TILE))
#define TILED_TILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_TILE, TiledTileClass))

typedef struct _TiledTile TiledTile;
typedef struct _TiledTileClass TiledTileClass;

#define TILED_TYPE_DATA (tiled_data_get_type ())
#define TILED_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_DATA, TiledData))
#define TILED_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_DATA, TiledDataClass))
#define TILED_IS_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_DATA))
#define TILED_IS_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_DATA))
#define TILED_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_DATA, TiledDataClass))

typedef struct _TiledData TiledData;
typedef struct _TiledDataClass TiledDataClass;

struct _TiledMap {
	GXmlSerializableObjectModel parent_instance;
	TiledMapPrivate * priv;
};

struct _TiledMapClass {
	GXmlSerializableObjectModelClass parent_class;
};

typedef enum  {
	TILED_MAP_ORIENTATION_ORTHOGONAL,
	TILED_MAP_ORIENTATION_ISOMETRIC,
	TILED_MAP_ORIENTATION_STAGGERED,
	TILED_MAP_ORIENTATION_HEXAGONAL
} TiledMapOrientation;

struct _TiledMapPrivate {
	gchar* _version;
	TiledMapOrientation _orientation;
	gchar* _renderorder;
	gint _width;
	gint _height;
	gint _tilewidth;
	gint _tileheight;
	GXmlSerializableArrayList* _tileset;
	GXmlSerializableArrayList* _layer;
	GXmlSerializableArrayList* _objectgroup;
};


static gpointer tiled_map_parent_class = NULL;

GType tiled_map_get_type (void) G_GNUC_CONST;
GType tiled_map_orientation_get_type (void) G_GNUC_CONST;
GType tiled_tileset_get_type (void) G_GNUC_CONST;
GType tiled_layer_get_type (void) G_GNUC_CONST;
GType tiled_objectgroup_get_type (void) G_GNUC_CONST;
#define TILED_MAP_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TILED_TYPE_MAP, TiledMapPrivate))
enum  {
	TILED_MAP_DUMMY_PROPERTY,
	TILED_MAP_VERSION,
	TILED_MAP_ORIENTATION,
	TILED_MAP_RENDERORDER,
	TILED_MAP_WIDTH,
	TILED_MAP_HEIGHT,
	TILED_MAP_TILEWIDTH,
	TILED_MAP_TILEHEIGHT,
	TILED_MAP_TILESET,
	TILED_MAP_LAYER,
	TILED_MAP_OBJECTGROUP
};
static gboolean tiled_map_real_deserialize_property (GXmlSerializableObjectModel* base, GXmlNode* property_node, GError** error);
void tiled_map_set_orientation (TiledMap* self, TiledMapOrientation value);
static gchar* tiled_map_real_node_name (GXmlSerializableObjectModel* base);
static gchar* tiled_map_real_to_string (GXmlSerializableObjectModel* base);
const gchar* tiled_map_get_version (TiledMap* self);
TiledMapOrientation tiled_map_get_orientation (TiledMap* self);
const gchar* tiled_map_orientation_to_string (TiledMapOrientation self);
const gchar* tiled_map_get_renderorder (TiledMap* self);
gint tiled_map_get_width (TiledMap* self);
gint tiled_map_get_height (TiledMap* self);
gint tiled_map_get_tilewidth (TiledMap* self);
gint tiled_map_get_tileheight (TiledMap* self);
gboolean tiled_map_collidesHorizontal (TiledMap* self, SDL_Rect* box);
GType tiled_tile_get_type (void) G_GNUC_CONST;
TiledTile* tiled_map_getTileAt (TiledMap* self, gint x, gint y);
gint tiled_tile_get_gid (TiledTile* self);
gboolean tiled_map_collidesWith (TiledMap* self, SDL_Rect* box);
GXmlSerializableArrayList* tiled_map_get_layer (TiledMap* self);
GType tiled_data_get_type (void) G_GNUC_CONST;
TiledData* tiled_layer_get_data (TiledLayer* self);
GXmlSerializableArrayList* tiled_data_get_tiles (TiledData* self);
static gchar* tiled_map_getRectAsString (TiledMap* self, SDL_Rect* rect);
TiledMap* tiled_map_new (void);
TiledMap* tiled_map_construct (GType object_type);
void tiled_map_set_version (TiledMap* self, const gchar* value);
void tiled_map_set_renderorder (TiledMap* self, const gchar* value);
void tiled_map_set_width (TiledMap* self, gint value);
void tiled_map_set_height (TiledMap* self, gint value);
void tiled_map_set_tilewidth (TiledMap* self, gint value);
void tiled_map_set_tileheight (TiledMap* self, gint value);
GXmlSerializableArrayList* tiled_map_get_tileset (TiledMap* self);
void tiled_map_set_tileset (TiledMap* self, GXmlSerializableArrayList* value);
void tiled_map_set_layer (TiledMap* self, GXmlSerializableArrayList* value);
GXmlSerializableArrayList* tiled_map_get_objectgroup (TiledMap* self);
void tiled_map_set_objectgroup (TiledMap* self, GXmlSerializableArrayList* value);
static void tiled_map_finalize (GObject* obj);
static void _vala_tiled_map_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_tiled_map_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GType tiled_map_orientation_get_type (void) {
	static volatile gsize tiled_map_orientation_type_id__volatile = 0;
	if (g_once_init_enter (&tiled_map_orientation_type_id__volatile)) {
		static const GEnumValue values[] = {{TILED_MAP_ORIENTATION_ORTHOGONAL, "TILED_MAP_ORIENTATION_ORTHOGONAL", "orthogonal"}, {TILED_MAP_ORIENTATION_ISOMETRIC, "TILED_MAP_ORIENTATION_ISOMETRIC", "isometric"}, {TILED_MAP_ORIENTATION_STAGGERED, "TILED_MAP_ORIENTATION_STAGGERED", "staggered"}, {TILED_MAP_ORIENTATION_HEXAGONAL, "TILED_MAP_ORIENTATION_HEXAGONAL", "hexagonal"}, {0, NULL, NULL}};
		GType tiled_map_orientation_type_id;
		tiled_map_orientation_type_id = g_enum_register_static ("TiledMapOrientation", values);
		g_once_init_leave (&tiled_map_orientation_type_id__volatile, tiled_map_orientation_type_id);
	}
	return tiled_map_orientation_type_id__volatile;
}


static gboolean tiled_map_real_deserialize_property (GXmlSerializableObjectModel* base, GXmlNode* property_node, GError** error) {
	TiledMap * self;
	gboolean result = FALSE;
	GXmlNode* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp11_ = FALSE;
	GXmlNode* _tmp12_ = NULL;
	gboolean _tmp13_ = FALSE;
	GError * _inner_error_ = NULL;
	self = (TiledMap*) base;
	g_return_val_if_fail (property_node != NULL, FALSE);
	_tmp0_ = property_node;
	_tmp1_ = gxml_node_get_name (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strcmp0 (_tmp3_, "orientation") == 0;
	_g_free0 (_tmp3_);
	if (_tmp4_) {
		GXmlNode* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		GQuark _tmp10_ = 0U;
		static GQuark _tmp9_label0 = 0;
		_tmp5_ = property_node;
		_tmp6_ = gxml_node_get_value (_tmp5_);
		_tmp7_ = _tmp6_;
		_tmp8_ = _tmp7_;
		_tmp10_ = (NULL == _tmp8_) ? 0 : g_quark_from_string (_tmp8_);
		g_free (_tmp8_);
		if (_tmp10_ == ((0 != _tmp9_label0) ? _tmp9_label0 : (_tmp9_label0 = g_quark_from_static_string ("orthogonal")))) {
			switch (0) {
				default:
				{
					tiled_map_set_orientation (self, TILED_MAP_ORIENTATION_ORTHOGONAL);
					break;
				}
			}
		}
	}
	_tmp12_ = property_node;
	_tmp13_ = GXML_SERIALIZABLE_OBJECT_MODEL_CLASS (tiled_map_parent_class)->deserialize_property (G_TYPE_CHECK_INSTANCE_CAST (self, GXML_TYPE_SERIALIZABLE_OBJECT_MODEL, GXmlSerializableObjectModel), _tmp12_, &_inner_error_);
	_tmp11_ = _tmp13_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_propagate_error (error, _inner_error_);
		return FALSE;
	}
	result = _tmp11_;
	return result;
}


static gchar* tiled_map_real_node_name (GXmlSerializableObjectModel* base) {
	TiledMap * self;
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	self = (TiledMap*) base;
	_tmp0_ = g_strdup ("Map");
	result = _tmp0_;
	return result;
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static gchar* tiled_map_real_to_string (GXmlSerializableObjectModel* base) {
	TiledMap * self;
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	TiledMapOrientation _tmp2_ = 0;
	GEnumValue* _tmp3_;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gint _tmp15_ = 0;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	self = (TiledMap*) base;
	_tmp0_ = self->priv->_version;
	_tmp1_ = string_to_string (_tmp0_);
	_tmp2_ = self->priv->_orientation;
	_tmp3_ = g_enum_get_value (g_type_class_ref (TILED_MAP_TYPE_ORIENTATION), _tmp2_);
	_tmp4_ = self->priv->_renderorder;
	_tmp5_ = string_to_string (_tmp4_);
	_tmp6_ = self->priv->_width;
	_tmp7_ = g_strdup_printf ("%i", _tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = self->priv->_height;
	_tmp10_ = g_strdup_printf ("%i", _tmp9_);
	_tmp11_ = _tmp10_;
	_tmp12_ = self->priv->_tilewidth;
	_tmp13_ = g_strdup_printf ("%i", _tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = self->priv->_tileheight;
	_tmp16_ = g_strdup_printf ("%i", _tmp15_);
	_tmp17_ = _tmp16_;
	_tmp18_ = g_strconcat ("Map: ", _tmp1_, " ", (_tmp3_ != NULL) ? _tmp3_->value_name : NULL, " ", _tmp5_, " ", _tmp8_, " ", _tmp11_, " ", _tmp14_, " ", _tmp17_, NULL);
	_tmp19_ = _tmp18_;
	_g_free0 (_tmp17_);
	_g_free0 (_tmp14_);
	_g_free0 (_tmp11_);
	_g_free0 (_tmp8_);
	result = _tmp19_;
	return result;
}


gboolean tiled_map_collidesHorizontal (TiledMap* self, SDL_Rect* box) {
	gboolean result = FALSE;
	gint bottom = 0;
	SDL_Rect _tmp0_ = {0};
	gint _tmp1_ = 0;
	SDL_Rect _tmp2_ = {0};
	guint _tmp3_ = 0U;
	TiledTile* t = NULL;
	SDL_Rect _tmp4_ = {0};
	gint _tmp5_ = 0;
	SDL_Rect _tmp6_ = {0};
	guint _tmp7_ = 0U;
	gint _tmp8_ = 0;
	TiledTile* _tmp9_ = NULL;
	gboolean _tmp10_ = FALSE;
	TiledTile* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	gint _tmp13_ = 0;
	SDL_Rect _tmp30_ = {0};
	gint _tmp31_ = 0;
	gint _tmp32_ = 0;
	TiledTile* _tmp33_ = NULL;
	gboolean _tmp34_ = FALSE;
	TiledTile* _tmp35_ = NULL;
	gint _tmp36_ = 0;
	gint _tmp37_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (box != NULL, FALSE);
	_tmp0_ = *box;
	_tmp1_ = _tmp0_.y;
	_tmp2_ = *box;
	_tmp3_ = _tmp2_.h;
	bottom = _tmp1_ + ((gint) _tmp3_);
	_tmp4_ = *box;
	_tmp5_ = _tmp4_.x;
	_tmp6_ = *box;
	_tmp7_ = _tmp6_.w;
	_tmp8_ = bottom;
	_tmp9_ = tiled_map_getTileAt (self, _tmp5_ + ((gint) _tmp7_), _tmp8_);
	t = _tmp9_;
	_tmp11_ = t;
	_tmp12_ = tiled_tile_get_gid (_tmp11_);
	_tmp13_ = _tmp12_;
	if (_tmp13_ < 128) {
		TiledTile* _tmp14_ = NULL;
		gint _tmp15_ = 0;
		gint _tmp16_ = 0;
		_tmp14_ = t;
		_tmp15_ = tiled_tile_get_gid (_tmp14_);
		_tmp16_ = _tmp15_;
		_tmp10_ = _tmp16_ > 0;
	} else {
		_tmp10_ = FALSE;
	}
	if (_tmp10_) {
		SDL_Rect tilebox = {0};
		SDL_Rect _tmp17_ = {0};
		gint _tmp18_ = 0;
		gint _tmp19_ = 0;
		gint _tmp20_ = 0;
		SDL_Rect _tmp21_ = {0};
		gint _tmp22_ = 0;
		gint _tmp23_ = 0;
		gint _tmp24_ = 0;
		gint _tmp25_ = 0;
		gint _tmp26_ = 0;
		SDL_Rect _tmp27_ = {0};
		SDL_Rect _tmp28_ = {0};
		gboolean _tmp29_ = FALSE;
		_tmp17_ = *box;
		_tmp18_ = _tmp17_.x;
		_tmp19_ = self->priv->_tilewidth;
		_tmp20_ = self->priv->_tilewidth;
		_tmp21_ = *box;
		_tmp22_ = _tmp21_.y;
		_tmp23_ = self->priv->_tileheight;
		_tmp24_ = self->priv->_tileheight;
		_tmp25_ = self->priv->_tilewidth;
		_tmp26_ = self->priv->_tileheight;
		memset (&_tmp27_, 0, sizeof (SDL_Rect));
		_tmp27_.x = (_tmp18_ / _tmp19_) * _tmp20_;
		_tmp27_.y = (_tmp22_ / _tmp23_) * _tmp24_;
		_tmp27_.w = (guint) _tmp25_;
		_tmp27_.h = (guint) _tmp26_;
		tilebox = _tmp27_;
		_tmp28_ = tilebox;
		_tmp29_ = SDL_HasIntersection (box, &_tmp28_);
		if (_tmp29_) {
			result = TRUE;
			_g_object_unref0 (t);
			return result;
		}
	}
	_tmp30_ = *box;
	_tmp31_ = _tmp30_.x;
	_tmp32_ = bottom;
	_tmp33_ = tiled_map_getTileAt (self, _tmp31_, _tmp32_);
	_g_object_unref0 (t);
	t = _tmp33_;
	_tmp35_ = t;
	_tmp36_ = tiled_tile_get_gid (_tmp35_);
	_tmp37_ = _tmp36_;
	if (_tmp37_ < 128) {
		TiledTile* _tmp38_ = NULL;
		gint _tmp39_ = 0;
		gint _tmp40_ = 0;
		_tmp38_ = t;
		_tmp39_ = tiled_tile_get_gid (_tmp38_);
		_tmp40_ = _tmp39_;
		_tmp34_ = _tmp40_ > 0;
	} else {
		_tmp34_ = FALSE;
	}
	if (_tmp34_) {
		SDL_Rect tilebox = {0};
		SDL_Rect _tmp41_ = {0};
		gint _tmp42_ = 0;
		gint _tmp43_ = 0;
		gint _tmp44_ = 0;
		SDL_Rect _tmp45_ = {0};
		gint _tmp46_ = 0;
		gint _tmp47_ = 0;
		gint _tmp48_ = 0;
		gint _tmp49_ = 0;
		gint _tmp50_ = 0;
		SDL_Rect _tmp51_ = {0};
		SDL_Rect _tmp52_ = {0};
		gboolean _tmp53_ = FALSE;
		_tmp41_ = *box;
		_tmp42_ = _tmp41_.x;
		_tmp43_ = self->priv->_tilewidth;
		_tmp44_ = self->priv->_tilewidth;
		_tmp45_ = *box;
		_tmp46_ = _tmp45_.y;
		_tmp47_ = self->priv->_tileheight;
		_tmp48_ = self->priv->_tileheight;
		_tmp49_ = self->priv->_tilewidth;
		_tmp50_ = self->priv->_tileheight;
		memset (&_tmp51_, 0, sizeof (SDL_Rect));
		_tmp51_.x = (_tmp42_ / _tmp43_) * _tmp44_;
		_tmp51_.y = (_tmp46_ / _tmp47_) * _tmp48_;
		_tmp51_.w = (guint) _tmp49_;
		_tmp51_.h = (guint) _tmp50_;
		tilebox = _tmp51_;
		_tmp52_ = tilebox;
		_tmp53_ = SDL_HasIntersection (box, &_tmp52_);
		if (_tmp53_) {
			result = TRUE;
			_g_object_unref0 (t);
			return result;
		}
	}
	result = FALSE;
	_g_object_unref0 (t);
	return result;
}


gboolean tiled_map_collidesWith (TiledMap* self, SDL_Rect* box) {
	gboolean result = FALSE;
	gint bottom = 0;
	SDL_Rect _tmp0_ = {0};
	gint _tmp1_ = 0;
	SDL_Rect _tmp2_ = {0};
	guint _tmp3_ = 0U;
	TiledTile* t = NULL;
	SDL_Rect _tmp4_ = {0};
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	TiledTile* _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	TiledTile* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	gint _tmp11_ = 0;
	SDL_Rect _tmp28_ = {0};
	gint _tmp29_ = 0;
	SDL_Rect _tmp30_ = {0};
	guint _tmp31_ = 0U;
	gint _tmp32_ = 0;
	TiledTile* _tmp33_ = NULL;
	gboolean _tmp34_ = FALSE;
	TiledTile* _tmp35_ = NULL;
	gint _tmp36_ = 0;
	gint _tmp37_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (box != NULL, FALSE);
	_tmp0_ = *box;
	_tmp1_ = _tmp0_.y;
	_tmp2_ = *box;
	_tmp3_ = _tmp2_.h;
	bottom = _tmp1_ + ((gint) _tmp3_);
	_tmp4_ = *box;
	_tmp5_ = _tmp4_.x;
	_tmp6_ = bottom;
	_tmp7_ = tiled_map_getTileAt (self, _tmp5_, _tmp6_);
	t = _tmp7_;
	_tmp9_ = t;
	_tmp10_ = tiled_tile_get_gid (_tmp9_);
	_tmp11_ = _tmp10_;
	if (_tmp11_ < 128) {
		TiledTile* _tmp12_ = NULL;
		gint _tmp13_ = 0;
		gint _tmp14_ = 0;
		_tmp12_ = t;
		_tmp13_ = tiled_tile_get_gid (_tmp12_);
		_tmp14_ = _tmp13_;
		_tmp8_ = _tmp14_ > 0;
	} else {
		_tmp8_ = FALSE;
	}
	if (_tmp8_) {
		SDL_Rect tilebox = {0};
		SDL_Rect _tmp15_ = {0};
		gint _tmp16_ = 0;
		gint _tmp17_ = 0;
		gint _tmp18_ = 0;
		SDL_Rect _tmp19_ = {0};
		gint _tmp20_ = 0;
		gint _tmp21_ = 0;
		gint _tmp22_ = 0;
		gint _tmp23_ = 0;
		gint _tmp24_ = 0;
		SDL_Rect _tmp25_ = {0};
		SDL_Rect _tmp26_ = {0};
		gboolean _tmp27_ = FALSE;
		_tmp15_ = *box;
		_tmp16_ = _tmp15_.x;
		_tmp17_ = self->priv->_tilewidth;
		_tmp18_ = self->priv->_tilewidth;
		_tmp19_ = *box;
		_tmp20_ = _tmp19_.y;
		_tmp21_ = self->priv->_tileheight;
		_tmp22_ = self->priv->_tileheight;
		_tmp23_ = self->priv->_tilewidth;
		_tmp24_ = self->priv->_tileheight;
		memset (&_tmp25_, 0, sizeof (SDL_Rect));
		_tmp25_.x = (_tmp16_ / _tmp17_) * _tmp18_;
		_tmp25_.y = ((_tmp20_ / _tmp21_) * _tmp22_) + 2;
		_tmp25_.w = (guint) _tmp23_;
		_tmp25_.h = (guint) _tmp24_;
		tilebox = _tmp25_;
		_tmp26_ = tilebox;
		_tmp27_ = SDL_HasIntersection (box, &_tmp26_);
		if (_tmp27_) {
			result = TRUE;
			_g_object_unref0 (t);
			return result;
		}
	}
	_tmp28_ = *box;
	_tmp29_ = _tmp28_.x;
	_tmp30_ = *box;
	_tmp31_ = _tmp30_.w;
	_tmp32_ = bottom;
	_tmp33_ = tiled_map_getTileAt (self, _tmp29_ + ((gint) _tmp31_), _tmp32_);
	_g_object_unref0 (t);
	t = _tmp33_;
	_tmp35_ = t;
	_tmp36_ = tiled_tile_get_gid (_tmp35_);
	_tmp37_ = _tmp36_;
	if (_tmp37_ < 128) {
		TiledTile* _tmp38_ = NULL;
		gint _tmp39_ = 0;
		gint _tmp40_ = 0;
		_tmp38_ = t;
		_tmp39_ = tiled_tile_get_gid (_tmp38_);
		_tmp40_ = _tmp39_;
		_tmp34_ = _tmp40_ > 0;
	} else {
		_tmp34_ = FALSE;
	}
	if (_tmp34_) {
		SDL_Rect tilebox = {0};
		SDL_Rect _tmp41_ = {0};
		gint _tmp42_ = 0;
		gint _tmp43_ = 0;
		gint _tmp44_ = 0;
		SDL_Rect _tmp45_ = {0};
		gint _tmp46_ = 0;
		gint _tmp47_ = 0;
		gint _tmp48_ = 0;
		gint _tmp49_ = 0;
		gint _tmp50_ = 0;
		SDL_Rect _tmp51_ = {0};
		SDL_Rect _tmp52_ = {0};
		gboolean _tmp53_ = FALSE;
		_tmp41_ = *box;
		_tmp42_ = _tmp41_.x;
		_tmp43_ = self->priv->_tilewidth;
		_tmp44_ = self->priv->_tilewidth;
		_tmp45_ = *box;
		_tmp46_ = _tmp45_.y;
		_tmp47_ = self->priv->_tileheight;
		_tmp48_ = self->priv->_tileheight;
		_tmp49_ = self->priv->_tilewidth;
		_tmp50_ = self->priv->_tileheight;
		memset (&_tmp51_, 0, sizeof (SDL_Rect));
		_tmp51_.x = (_tmp42_ / _tmp43_) * _tmp44_;
		_tmp51_.y = ((_tmp46_ / _tmp47_) * _tmp48_) + 2;
		_tmp51_.w = (guint) _tmp49_;
		_tmp51_.h = (guint) _tmp50_;
		tilebox = _tmp51_;
		_tmp52_ = tilebox;
		_tmp53_ = SDL_HasIntersection (box, &_tmp52_);
		if (_tmp53_) {
			result = TRUE;
			_g_object_unref0 (t);
			return result;
		}
	}
	result = FALSE;
	_g_object_unref0 (t);
	return result;
}


TiledTile* tiled_map_getTileAt (TiledMap* self, gint x, gint y) {
	TiledTile* result = NULL;
	gint xnum = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint ynum = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint tilenumber = 0;
	gint _tmp4_ = 0;
	GXmlSerializableArrayList* _tmp5_ = NULL;
	gpointer _tmp6_ = NULL;
	TiledLayer* _tmp7_ = NULL;
	TiledData* _tmp8_ = NULL;
	TiledData* _tmp9_ = NULL;
	GXmlSerializableArrayList* _tmp10_ = NULL;
	GXmlSerializableArrayList* _tmp11_ = NULL;
	gpointer _tmp12_ = NULL;
	TiledTile* _tmp13_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = x;
	_tmp1_ = self->priv->_tilewidth;
	xnum = _tmp0_ / _tmp1_;
	_tmp2_ = y;
	_tmp3_ = self->priv->_tileheight;
	ynum = _tmp2_ / _tmp3_;
	_tmp4_ = self->priv->_width;
	tilenumber = xnum + (ynum * _tmp4_);
	_tmp5_ = self->priv->_layer;
	_tmp6_ = gee_abstract_list_get ((GeeAbstractList*) _tmp5_, 0);
	_tmp7_ = (TiledLayer*) _tmp6_;
	_tmp8_ = tiled_layer_get_data (_tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = tiled_data_get_tiles (_tmp9_);
	_tmp11_ = _tmp10_;
	_tmp12_ = gee_abstract_list_get ((GeeAbstractList*) _tmp11_, tilenumber);
	_tmp13_ = (TiledTile*) _tmp12_;
	_g_object_unref0 (_tmp7_);
	result = _tmp13_;
	return result;
}


static gchar* tiled_map_getRectAsString (TiledMap* self, SDL_Rect* rect) {
	gchar* result = NULL;
	SDL_Rect _tmp0_ = {0};
	gint _tmp1_ = 0;
	SDL_Rect _tmp2_ = {0};
	gint _tmp3_ = 0;
	SDL_Rect _tmp4_ = {0};
	guint _tmp5_ = 0U;
	SDL_Rect _tmp6_ = {0};
	guint _tmp7_ = 0U;
	gchar* _tmp8_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (rect != NULL, NULL);
	_tmp0_ = *rect;
	_tmp1_ = _tmp0_.x;
	_tmp2_ = *rect;
	_tmp3_ = _tmp2_.y;
	_tmp4_ = *rect;
	_tmp5_ = _tmp4_.w;
	_tmp6_ = *rect;
	_tmp7_ = _tmp6_.h;
	_tmp8_ = g_strdup_printf ("%d, %d, %u, %u\n", _tmp1_, _tmp3_, _tmp5_, _tmp7_);
	result = _tmp8_;
	return result;
}


TiledMap* tiled_map_construct (GType object_type) {
	TiledMap * self = NULL;
	self = (TiledMap*) gxml_serializable_object_model_construct (object_type);
	return self;
}


TiledMap* tiled_map_new (void) {
	return tiled_map_construct (TILED_TYPE_MAP);
}


const gchar* tiled_map_get_version (TiledMap* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_version;
	result = _tmp0_;
	return result;
}


void tiled_map_set_version (TiledMap* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_version);
	self->priv->_version = _tmp1_;
	g_object_notify ((GObject *) self, "version");
}


TiledMapOrientation tiled_map_get_orientation (TiledMap* self) {
	TiledMapOrientation result;
	TiledMapOrientation _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_orientation;
	result = _tmp0_;
	return result;
}


void tiled_map_set_orientation (TiledMap* self, TiledMapOrientation value) {
	TiledMapOrientation _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_orientation = _tmp0_;
	g_object_notify ((GObject *) self, "orientation");
}


const gchar* tiled_map_get_renderorder (TiledMap* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_renderorder;
	result = _tmp0_;
	return result;
}


void tiled_map_set_renderorder (TiledMap* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_renderorder);
	self->priv->_renderorder = _tmp1_;
	g_object_notify ((GObject *) self, "renderorder");
}


gint tiled_map_get_width (TiledMap* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_width;
	result = _tmp0_;
	return result;
}


void tiled_map_set_width (TiledMap* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_width = _tmp0_;
	g_object_notify ((GObject *) self, "width");
}


gint tiled_map_get_height (TiledMap* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_height;
	result = _tmp0_;
	return result;
}


void tiled_map_set_height (TiledMap* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_height = _tmp0_;
	g_object_notify ((GObject *) self, "height");
}


gint tiled_map_get_tilewidth (TiledMap* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_tilewidth;
	result = _tmp0_;
	return result;
}


void tiled_map_set_tilewidth (TiledMap* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_tilewidth = _tmp0_;
	g_object_notify ((GObject *) self, "tilewidth");
}


gint tiled_map_get_tileheight (TiledMap* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_tileheight;
	result = _tmp0_;
	return result;
}


void tiled_map_set_tileheight (TiledMap* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_tileheight = _tmp0_;
	g_object_notify ((GObject *) self, "tileheight");
}


GXmlSerializableArrayList* tiled_map_get_tileset (TiledMap* self) {
	GXmlSerializableArrayList* result;
	GXmlSerializableArrayList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tileset;
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void tiled_map_set_tileset (TiledMap* self, GXmlSerializableArrayList* value) {
	GXmlSerializableArrayList* _tmp0_ = NULL;
	GXmlSerializableArrayList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_tileset);
	self->priv->_tileset = _tmp1_;
	g_object_notify ((GObject *) self, "tileset");
}


GXmlSerializableArrayList* tiled_map_get_layer (TiledMap* self) {
	GXmlSerializableArrayList* result;
	GXmlSerializableArrayList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_layer;
	result = _tmp0_;
	return result;
}


void tiled_map_set_layer (TiledMap* self, GXmlSerializableArrayList* value) {
	GXmlSerializableArrayList* _tmp0_ = NULL;
	GXmlSerializableArrayList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_layer);
	self->priv->_layer = _tmp1_;
	g_object_notify ((GObject *) self, "layer");
}


GXmlSerializableArrayList* tiled_map_get_objectgroup (TiledMap* self) {
	GXmlSerializableArrayList* result;
	GXmlSerializableArrayList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_objectgroup;
	result = _tmp0_;
	return result;
}


void tiled_map_set_objectgroup (TiledMap* self, GXmlSerializableArrayList* value) {
	GXmlSerializableArrayList* _tmp0_ = NULL;
	GXmlSerializableArrayList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_objectgroup);
	self->priv->_objectgroup = _tmp1_;
	g_object_notify ((GObject *) self, "objectgroup");
}


static void tiled_map_class_init (TiledMapClass * klass) {
	tiled_map_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TiledMapPrivate));
	((GXmlSerializableObjectModelClass *) klass)->deserialize_property = tiled_map_real_deserialize_property;
	((GXmlSerializableObjectModelClass *) klass)->node_name = tiled_map_real_node_name;
	((GXmlSerializableObjectModelClass *) klass)->to_string = tiled_map_real_to_string;
	G_OBJECT_CLASS (klass)->get_property = _vala_tiled_map_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_tiled_map_set_property;
	G_OBJECT_CLASS (klass)->finalize = tiled_map_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_MAP_VERSION, g_param_spec_string ("version", "version", "version", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_MAP_ORIENTATION, g_param_spec_enum ("orientation", "orientation", "orientation", TILED_MAP_TYPE_ORIENTATION, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_MAP_RENDERORDER, g_param_spec_string ("renderorder", "renderorder", "renderorder", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_MAP_WIDTH, g_param_spec_int ("width", "width", "width", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_MAP_HEIGHT, g_param_spec_int ("height", "height", "height", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_MAP_TILEWIDTH, g_param_spec_int ("tilewidth", "tilewidth", "tilewidth", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_MAP_TILEHEIGHT, g_param_spec_int ("tileheight", "tileheight", "tileheight", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_MAP_TILESET, g_param_spec_object ("tileset", "tileset", "tileset", GXML_TYPE_SERIALIZABLE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_MAP_LAYER, g_param_spec_object ("layer", "layer", "layer", GXML_TYPE_SERIALIZABLE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_MAP_OBJECTGROUP, g_param_spec_object ("objectgroup", "objectgroup", "objectgroup", GXML_TYPE_SERIALIZABLE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void tiled_map_instance_init (TiledMap * self) {
	GXmlSerializableArrayList* _tmp0_ = NULL;
	GXmlSerializableArrayList* _tmp1_ = NULL;
	GXmlSerializableArrayList* _tmp2_ = NULL;
	self->priv = TILED_MAP_GET_PRIVATE (self);
	_tmp0_ = gxml_serializable_array_list_new (TILED_TYPE_TILESET, (GBoxedCopyFunc) g_object_ref, g_object_unref);
	self->priv->_tileset = _tmp0_;
	_tmp1_ = gxml_serializable_array_list_new (TILED_TYPE_LAYER, (GBoxedCopyFunc) g_object_ref, g_object_unref);
	self->priv->_layer = _tmp1_;
	_tmp2_ = gxml_serializable_array_list_new (TILED_TYPE_OBJECTGROUP, (GBoxedCopyFunc) g_object_ref, g_object_unref);
	self->priv->_objectgroup = _tmp2_;
}


static void tiled_map_finalize (GObject* obj) {
	TiledMap * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TILED_TYPE_MAP, TiledMap);
	_g_free0 (self->priv->_version);
	_g_free0 (self->priv->_renderorder);
	_g_object_unref0 (self->priv->_tileset);
	_g_object_unref0 (self->priv->_layer);
	_g_object_unref0 (self->priv->_objectgroup);
	G_OBJECT_CLASS (tiled_map_parent_class)->finalize (obj);
}


GType tiled_map_get_type (void) {
	static volatile gsize tiled_map_type_id__volatile = 0;
	if (g_once_init_enter (&tiled_map_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TiledMapClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tiled_map_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TiledMap), 0, (GInstanceInitFunc) tiled_map_instance_init, NULL };
		GType tiled_map_type_id;
		tiled_map_type_id = g_type_register_static (GXML_TYPE_SERIALIZABLE_OBJECT_MODEL, "TiledMap", &g_define_type_info, 0);
		g_once_init_leave (&tiled_map_type_id__volatile, tiled_map_type_id);
	}
	return tiled_map_type_id__volatile;
}


static void _vala_tiled_map_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	TiledMap * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TILED_TYPE_MAP, TiledMap);
	switch (property_id) {
		case TILED_MAP_VERSION:
		g_value_set_string (value, tiled_map_get_version (self));
		break;
		case TILED_MAP_ORIENTATION:
		g_value_set_enum (value, tiled_map_get_orientation (self));
		break;
		case TILED_MAP_RENDERORDER:
		g_value_set_string (value, tiled_map_get_renderorder (self));
		break;
		case TILED_MAP_WIDTH:
		g_value_set_int (value, tiled_map_get_width (self));
		break;
		case TILED_MAP_HEIGHT:
		g_value_set_int (value, tiled_map_get_height (self));
		break;
		case TILED_MAP_TILEWIDTH:
		g_value_set_int (value, tiled_map_get_tilewidth (self));
		break;
		case TILED_MAP_TILEHEIGHT:
		g_value_set_int (value, tiled_map_get_tileheight (self));
		break;
		case TILED_MAP_TILESET:
		g_value_set_object (value, tiled_map_get_tileset (self));
		break;
		case TILED_MAP_LAYER:
		g_value_set_object (value, tiled_map_get_layer (self));
		break;
		case TILED_MAP_OBJECTGROUP:
		g_value_set_object (value, tiled_map_get_objectgroup (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_tiled_map_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	TiledMap * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TILED_TYPE_MAP, TiledMap);
	switch (property_id) {
		case TILED_MAP_VERSION:
		tiled_map_set_version (self, g_value_get_string (value));
		break;
		case TILED_MAP_ORIENTATION:
		tiled_map_set_orientation (self, g_value_get_enum (value));
		break;
		case TILED_MAP_RENDERORDER:
		tiled_map_set_renderorder (self, g_value_get_string (value));
		break;
		case TILED_MAP_WIDTH:
		tiled_map_set_width (self, g_value_get_int (value));
		break;
		case TILED_MAP_HEIGHT:
		tiled_map_set_height (self, g_value_get_int (value));
		break;
		case TILED_MAP_TILEWIDTH:
		tiled_map_set_tilewidth (self, g_value_get_int (value));
		break;
		case TILED_MAP_TILEHEIGHT:
		tiled_map_set_tileheight (self, g_value_get_int (value));
		break;
		case TILED_MAP_TILESET:
		tiled_map_set_tileset (self, g_value_get_object (value));
		break;
		case TILED_MAP_LAYER:
		tiled_map_set_layer (self, g_value_get_object (value));
		break;
		case TILED_MAP_OBJECTGROUP:
		tiled_map_set_objectgroup (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



