/* objectgroup.c generated by valac 0.32.0, the Vala compiler
 * generated from objectgroup.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gxml/gxml.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <stdio.h>


#define TILED_TYPE_OBJECTGROUP (tiled_objectgroup_get_type ())
#define TILED_OBJECTGROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_OBJECTGROUP, TiledObjectgroup))
#define TILED_OBJECTGROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_OBJECTGROUP, TiledObjectgroupClass))
#define TILED_IS_OBJECTGROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_OBJECTGROUP))
#define TILED_IS_OBJECTGROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_OBJECTGROUP))
#define TILED_OBJECTGROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_OBJECTGROUP, TiledObjectgroupClass))

typedef struct _TiledObjectgroup TiledObjectgroup;
typedef struct _TiledObjectgroupClass TiledObjectgroupClass;
typedef struct _TiledObjectgroupPrivate TiledObjectgroupPrivate;

#define TILED_TYPE_OBJECT (tiled_object_get_type ())
#define TILED_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_OBJECT, TiledObject))
#define TILED_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_OBJECT, TiledObjectClass))
#define TILED_IS_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_OBJECT))
#define TILED_IS_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_OBJECT))
#define TILED_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_OBJECT, TiledObjectClass))

typedef struct _TiledObject TiledObject;
typedef struct _TiledObjectClass TiledObjectClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _TiledObjectgroup {
	GXmlSerializableObjectModel parent_instance;
	TiledObjectgroupPrivate * priv;
};

struct _TiledObjectgroupClass {
	GXmlSerializableObjectModelClass parent_class;
};

struct _TiledObjectgroupPrivate {
	gchar* _name;
	GXmlSerializableArrayList* _objects;
};


static gpointer tiled_objectgroup_parent_class = NULL;

GType tiled_objectgroup_get_type (void) G_GNUC_CONST;
GType tiled_object_get_type (void) G_GNUC_CONST;
#define TILED_OBJECTGROUP_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TILED_TYPE_OBJECTGROUP, TiledObjectgroupPrivate))
enum  {
	TILED_OBJECTGROUP_DUMMY_PROPERTY,
	TILED_OBJECTGROUP_NAME,
	TILED_OBJECTGROUP_OBJECTS
};
static gchar* tiled_objectgroup_real_node_name (GXmlSerializableObjectModel* base);
static gchar* tiled_objectgroup_real_to_string (GXmlSerializableObjectModel* base);
const gchar* tiled_objectgroup_get_name (TiledObjectgroup* self);
void tiled_objectgroup_show (TiledObjectgroup* self);
GXmlSerializableArrayList* tiled_objectgroup_get_objects (TiledObjectgroup* self);
TiledObjectgroup* tiled_objectgroup_new (void);
TiledObjectgroup* tiled_objectgroup_construct (GType object_type);
void tiled_objectgroup_set_name (TiledObjectgroup* self, const gchar* value);
void tiled_objectgroup_set_objects (TiledObjectgroup* self, GXmlSerializableArrayList* value);
static void tiled_objectgroup_finalize (GObject* obj);
static void _vala_tiled_objectgroup_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_tiled_objectgroup_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gchar* tiled_objectgroup_real_node_name (GXmlSerializableObjectModel* base) {
	TiledObjectgroup * self;
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	self = (TiledObjectgroup*) base;
	_tmp0_ = g_strdup ("Objectgroup");
	result = _tmp0_;
	return result;
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static gchar* tiled_objectgroup_real_to_string (GXmlSerializableObjectModel* base) {
	TiledObjectgroup * self;
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	self = (TiledObjectgroup*) base;
	_tmp0_ = self->priv->_name;
	_tmp1_ = string_to_string (_tmp0_);
	_tmp2_ = g_strconcat ("Objectgroup: ", _tmp1_, NULL);
	result = _tmp2_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void tiled_objectgroup_show (TiledObjectgroup* self) {
	g_return_if_fail (self != NULL);
	{
		GXmlSerializableArrayList* _o_list = NULL;
		GXmlSerializableArrayList* _tmp0_ = NULL;
		GXmlSerializableArrayList* _tmp1_ = NULL;
		gint _o_size = 0;
		GXmlSerializableArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _o_index = 0;
		_tmp0_ = self->priv->_objects;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_o_list = _tmp1_;
		_tmp2_ = _o_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_o_size = _tmp4_;
		_o_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			TiledObject* o = NULL;
			GXmlSerializableArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			FILE* _tmp11_ = NULL;
			TiledObject* _tmp12_ = NULL;
			gchar* _tmp13_ = NULL;
			gchar* _tmp14_ = NULL;
			_tmp5_ = _o_index;
			_o_index = _tmp5_ + 1;
			_tmp6_ = _o_index;
			_tmp7_ = _o_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _o_list;
			_tmp9_ = _o_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			o = (TiledObject*) _tmp10_;
			_tmp11_ = stdout;
			_tmp12_ = o;
			_tmp13_ = gxml_serializable_object_model_to_string ((GXmlSerializableObjectModel*) _tmp12_);
			_tmp14_ = _tmp13_;
			fprintf (_tmp11_, "%s", _tmp14_);
			_g_free0 (_tmp14_);
			_g_object_unref0 (o);
		}
		_g_object_unref0 (_o_list);
	}
}


TiledObjectgroup* tiled_objectgroup_construct (GType object_type) {
	TiledObjectgroup * self = NULL;
	self = (TiledObjectgroup*) gxml_serializable_object_model_construct (object_type);
	return self;
}


TiledObjectgroup* tiled_objectgroup_new (void) {
	return tiled_objectgroup_construct (TILED_TYPE_OBJECTGROUP);
}


const gchar* tiled_objectgroup_get_name (TiledObjectgroup* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}


void tiled_objectgroup_set_name (TiledObjectgroup* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp1_;
	g_object_notify ((GObject *) self, "name");
}


GXmlSerializableArrayList* tiled_objectgroup_get_objects (TiledObjectgroup* self) {
	GXmlSerializableArrayList* result;
	GXmlSerializableArrayList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_objects;
	result = _tmp0_;
	return result;
}


void tiled_objectgroup_set_objects (TiledObjectgroup* self, GXmlSerializableArrayList* value) {
	GXmlSerializableArrayList* _tmp0_ = NULL;
	GXmlSerializableArrayList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_objects);
	self->priv->_objects = _tmp1_;
	g_object_notify ((GObject *) self, "objects");
}


static void tiled_objectgroup_class_init (TiledObjectgroupClass * klass) {
	tiled_objectgroup_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TiledObjectgroupPrivate));
	((GXmlSerializableObjectModelClass *) klass)->node_name = tiled_objectgroup_real_node_name;
	((GXmlSerializableObjectModelClass *) klass)->to_string = tiled_objectgroup_real_to_string;
	G_OBJECT_CLASS (klass)->get_property = _vala_tiled_objectgroup_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_tiled_objectgroup_set_property;
	G_OBJECT_CLASS (klass)->finalize = tiled_objectgroup_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_OBJECTGROUP_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_OBJECTGROUP_OBJECTS, g_param_spec_object ("objects", "objects", "objects", GXML_TYPE_SERIALIZABLE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void tiled_objectgroup_instance_init (TiledObjectgroup * self) {
	GXmlSerializableArrayList* _tmp0_ = NULL;
	self->priv = TILED_OBJECTGROUP_GET_PRIVATE (self);
	_tmp0_ = gxml_serializable_array_list_new (TILED_TYPE_OBJECT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
	self->priv->_objects = _tmp0_;
}


static void tiled_objectgroup_finalize (GObject* obj) {
	TiledObjectgroup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TILED_TYPE_OBJECTGROUP, TiledObjectgroup);
	_g_free0 (self->priv->_name);
	_g_object_unref0 (self->priv->_objects);
	G_OBJECT_CLASS (tiled_objectgroup_parent_class)->finalize (obj);
}


GType tiled_objectgroup_get_type (void) {
	static volatile gsize tiled_objectgroup_type_id__volatile = 0;
	if (g_once_init_enter (&tiled_objectgroup_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TiledObjectgroupClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tiled_objectgroup_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TiledObjectgroup), 0, (GInstanceInitFunc) tiled_objectgroup_instance_init, NULL };
		GType tiled_objectgroup_type_id;
		tiled_objectgroup_type_id = g_type_register_static (GXML_TYPE_SERIALIZABLE_OBJECT_MODEL, "TiledObjectgroup", &g_define_type_info, 0);
		g_once_init_leave (&tiled_objectgroup_type_id__volatile, tiled_objectgroup_type_id);
	}
	return tiled_objectgroup_type_id__volatile;
}


static void _vala_tiled_objectgroup_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	TiledObjectgroup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TILED_TYPE_OBJECTGROUP, TiledObjectgroup);
	switch (property_id) {
		case TILED_OBJECTGROUP_NAME:
		g_value_set_string (value, tiled_objectgroup_get_name (self));
		break;
		case TILED_OBJECTGROUP_OBJECTS:
		g_value_set_object (value, tiled_objectgroup_get_objects (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_tiled_objectgroup_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	TiledObjectgroup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TILED_TYPE_OBJECTGROUP, TiledObjectgroup);
	switch (property_id) {
		case TILED_OBJECTGROUP_NAME:
		tiled_objectgroup_set_name (self, g_value_get_string (value));
		break;
		case TILED_OBJECTGROUP_OBJECTS:
		tiled_objectgroup_set_objects (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



