/* tile.c generated by valac 0.32.0, the Vala compiler
 * generated from tile.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gxml/gxml.h>
#include <stdlib.h>
#include <string.h>


#define TILED_TYPE_TILE (tiled_tile_get_type ())
#define TILED_TILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_TILE, TiledTile))
#define TILED_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_TILE, TiledTileClass))
#define TILED_IS_TILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_TILE))
#define TILED_IS_TILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_TILE))
#define TILED_TILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_TILE, TiledTileClass))

typedef struct _TiledTile TiledTile;
typedef struct _TiledTileClass TiledTileClass;
typedef struct _TiledTilePrivate TiledTilePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _TiledTile {
	GXmlSerializableObjectModel parent_instance;
	TiledTilePrivate * priv;
};

struct _TiledTileClass {
	GXmlSerializableObjectModelClass parent_class;
};

struct _TiledTilePrivate {
	gint _gid;
};


static gpointer tiled_tile_parent_class = NULL;

GType tiled_tile_get_type (void) G_GNUC_CONST;
#define TILED_TILE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TILED_TYPE_TILE, TiledTilePrivate))
enum  {
	TILED_TILE_DUMMY_PROPERTY,
	TILED_TILE_GID
};
static gchar* tiled_tile_real_node_name (GXmlSerializableObjectModel* base);
static gchar* tiled_tile_real_to_string (GXmlSerializableObjectModel* base);
gint tiled_tile_get_gid (TiledTile* self);
TiledTile* tiled_tile_new (void);
TiledTile* tiled_tile_construct (GType object_type);
void tiled_tile_set_gid (TiledTile* self, gint value);
static void tiled_tile_finalize (GObject* obj);
static void _vala_tiled_tile_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_tiled_tile_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gchar* tiled_tile_real_node_name (GXmlSerializableObjectModel* base) {
	TiledTile * self;
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	self = (TiledTile*) base;
	_tmp0_ = g_strdup ("Tile");
	result = _tmp0_;
	return result;
}


static gchar* tiled_tile_real_to_string (GXmlSerializableObjectModel* base) {
	TiledTile * self;
	gchar* result = NULL;
	gint _tmp0_ = 0;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	self = (TiledTile*) base;
	_tmp0_ = self->priv->_gid;
	_tmp1_ = g_strdup_printf ("%i", _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat ("Tile: ", _tmp2_, NULL);
	_tmp4_ = _tmp3_;
	_g_free0 (_tmp2_);
	result = _tmp4_;
	return result;
}


TiledTile* tiled_tile_construct (GType object_type) {
	TiledTile * self = NULL;
	self = (TiledTile*) gxml_serializable_object_model_construct (object_type);
	return self;
}


TiledTile* tiled_tile_new (void) {
	return tiled_tile_construct (TILED_TYPE_TILE);
}


gint tiled_tile_get_gid (TiledTile* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_gid;
	result = _tmp0_;
	return result;
}


void tiled_tile_set_gid (TiledTile* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_gid = _tmp0_;
	g_object_notify ((GObject *) self, "gid");
}


static void tiled_tile_class_init (TiledTileClass * klass) {
	tiled_tile_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TiledTilePrivate));
	((GXmlSerializableObjectModelClass *) klass)->node_name = tiled_tile_real_node_name;
	((GXmlSerializableObjectModelClass *) klass)->to_string = tiled_tile_real_to_string;
	G_OBJECT_CLASS (klass)->get_property = _vala_tiled_tile_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_tiled_tile_set_property;
	G_OBJECT_CLASS (klass)->finalize = tiled_tile_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), TILED_TILE_GID, g_param_spec_int ("gid", "gid", "gid", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void tiled_tile_instance_init (TiledTile * self) {
	self->priv = TILED_TILE_GET_PRIVATE (self);
}


static void tiled_tile_finalize (GObject* obj) {
	TiledTile * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TILED_TYPE_TILE, TiledTile);
	G_OBJECT_CLASS (tiled_tile_parent_class)->finalize (obj);
}


GType tiled_tile_get_type (void) {
	static volatile gsize tiled_tile_type_id__volatile = 0;
	if (g_once_init_enter (&tiled_tile_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TiledTileClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tiled_tile_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TiledTile), 0, (GInstanceInitFunc) tiled_tile_instance_init, NULL };
		GType tiled_tile_type_id;
		tiled_tile_type_id = g_type_register_static (GXML_TYPE_SERIALIZABLE_OBJECT_MODEL, "TiledTile", &g_define_type_info, 0);
		g_once_init_leave (&tiled_tile_type_id__volatile, tiled_tile_type_id);
	}
	return tiled_tile_type_id__volatile;
}


static void _vala_tiled_tile_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	TiledTile * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TILED_TYPE_TILE, TiledTile);
	switch (property_id) {
		case TILED_TILE_GID:
		g_value_set_int (value, tiled_tile_get_gid (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_tiled_tile_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	TiledTile * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TILED_TYPE_TILE, TiledTile);
	switch (property_id) {
		case TILED_TILE_GID:
		tiled_tile_set_gid (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



