/* tiled.c generated by valac 0.32.0, the Vala compiler
 * generated from tiled.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gxml/gxml.h>


#define TILED_TYPE_MAP (tiled_map_get_type ())
#define TILED_MAP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TILED_TYPE_MAP, TiledMap))
#define TILED_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TILED_TYPE_MAP, TiledMapClass))
#define TILED_IS_MAP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TILED_TYPE_MAP))
#define TILED_IS_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TILED_TYPE_MAP))
#define TILED_MAP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TILED_TYPE_MAP, TiledMapClass))

typedef struct _TiledMap TiledMap;
typedef struct _TiledMapClass TiledMapClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))



GType tiled_map_get_type (void) G_GNUC_CONST;
TiledMap* tiled_loadMap (const gchar* filename);
TiledMap* tiled_map_new (void);
TiledMap* tiled_map_construct (GType object_type);


TiledMap* tiled_loadMap (const gchar* filename) {
	TiledMap* result = NULL;
	TiledMap* map = NULL;
	TiledMap* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (filename != NULL, NULL);
	_tmp0_ = tiled_map_new ();
	map = _tmp0_;
	{
		GXmlGDocument* doc = NULL;
		const gchar* _tmp1_ = NULL;
		GXmlGDocument* _tmp2_ = NULL;
		TiledMap* _tmp3_ = NULL;
		GXmlGDocument* _tmp4_ = NULL;
		_tmp1_ = filename;
		_tmp2_ = gxml_gdocument_new_from_path (_tmp1_, 0, &_inner_error_);
		doc = _tmp2_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp3_ = map;
		_tmp4_ = doc;
		gxml_serializable_object_model_deserialize ((GXmlSerializableObjectModel*) _tmp3_, (GXmlNode*) _tmp4_, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (doc);
			goto __catch0_g_error;
		}
		_g_object_unref0 (doc);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = e;
		_tmp6_ = _tmp5_->message;
		g_message ("tiled.vala:11: Map loading failed: %s\n", _tmp6_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (map);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	result = map;
	return result;
}



