/* component.c generated by valac 0.32.0, the Vala compiler
 * generated from component.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define ENGINE_TYPE_COMPONENT (engine_component_get_type ())
#define ENGINE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENGINE_TYPE_COMPONENT, EngineComponent))
#define ENGINE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENGINE_TYPE_COMPONENT, EngineComponentClass))
#define ENGINE_IS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENGINE_TYPE_COMPONENT))
#define ENGINE_IS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENGINE_TYPE_COMPONENT))
#define ENGINE_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENGINE_TYPE_COMPONENT, EngineComponentClass))

typedef struct _EngineComponent EngineComponent;
typedef struct _EngineComponentClass EngineComponentClass;
typedef struct _EngineComponentPrivate EngineComponentPrivate;

#define ENGINE_TYPE_ENTITY (engine_entity_get_type ())
#define ENGINE_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENGINE_TYPE_ENTITY, EngineEntity))
#define ENGINE_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENGINE_TYPE_ENTITY, EngineEntityClass))
#define ENGINE_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENGINE_TYPE_ENTITY))
#define ENGINE_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENGINE_TYPE_ENTITY))
#define ENGINE_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENGINE_TYPE_ENTITY, EngineEntityClass))

typedef struct _EngineEntity EngineEntity;
typedef struct _EngineEntityClass EngineEntityClass;

#define ENGINE_TYPE_UPDATE_COMPONENT (engine_update_component_get_type ())
#define ENGINE_UPDATE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENGINE_TYPE_UPDATE_COMPONENT, EngineUpdateComponent))
#define ENGINE_UPDATE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENGINE_TYPE_UPDATE_COMPONENT, EngineUpdateComponentClass))
#define ENGINE_IS_UPDATE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENGINE_TYPE_UPDATE_COMPONENT))
#define ENGINE_IS_UPDATE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENGINE_TYPE_UPDATE_COMPONENT))
#define ENGINE_UPDATE_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENGINE_TYPE_UPDATE_COMPONENT, EngineUpdateComponentClass))

typedef struct _EngineUpdateComponent EngineUpdateComponent;
typedef struct _EngineUpdateComponentClass EngineUpdateComponentClass;
typedef struct _EngineUpdateComponentPrivate EngineUpdateComponentPrivate;

struct _EngineComponent {
	GObject parent_instance;
	EngineComponentPrivate * priv;
};

struct _EngineComponentClass {
	GObjectClass parent_class;
};

struct _EngineComponentPrivate {
	EngineEntity* _entity;
};

struct _EngineUpdateComponent {
	EngineComponent parent_instance;
	EngineUpdateComponentPrivate * priv;
};

struct _EngineUpdateComponentClass {
	EngineComponentClass parent_class;
	void (*update) (EngineUpdateComponent* self);
};


static gpointer engine_component_parent_class = NULL;
static gpointer engine_update_component_parent_class = NULL;

GType engine_component_get_type (void) G_GNUC_CONST;
GType engine_entity_get_type (void) G_GNUC_CONST;
#define ENGINE_COMPONENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ENGINE_TYPE_COMPONENT, EngineComponentPrivate))
enum  {
	ENGINE_COMPONENT_DUMMY_PROPERTY,
	ENGINE_COMPONENT_ENTITY
};
EngineComponent* engine_component_construct (GType object_type);
EngineEntity* engine_component_get_entity (EngineComponent* self);
void engine_component_set_entity (EngineComponent* self, EngineEntity* value);
static void engine_component_finalize (GObject* obj);
static void _vala_engine_component_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_engine_component_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType engine_update_component_get_type (void) G_GNUC_CONST;
enum  {
	ENGINE_UPDATE_COMPONENT_DUMMY_PROPERTY
};
void engine_update_component_update (EngineUpdateComponent* self);
static void engine_update_component_real_update (EngineUpdateComponent* self);
EngineUpdateComponent* engine_update_component_construct (GType object_type);


EngineComponent* engine_component_construct (GType object_type) {
	EngineComponent * self = NULL;
	self = (EngineComponent*) g_object_new (object_type, NULL);
	return self;
}


EngineEntity* engine_component_get_entity (EngineComponent* self) {
	EngineEntity* result;
	EngineEntity* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_entity;
	result = _tmp0_;
	return result;
}


void engine_component_set_entity (EngineComponent* self, EngineEntity* value) {
	EngineEntity* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_entity = _tmp0_;
	g_object_notify ((GObject *) self, "entity");
}


static void engine_component_class_init (EngineComponentClass * klass) {
	engine_component_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (EngineComponentPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_engine_component_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_engine_component_set_property;
	G_OBJECT_CLASS (klass)->finalize = engine_component_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENGINE_COMPONENT_ENTITY, g_param_spec_object ("entity", "entity", "entity", ENGINE_TYPE_ENTITY, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void engine_component_instance_init (EngineComponent * self) {
	self->priv = ENGINE_COMPONENT_GET_PRIVATE (self);
}


static void engine_component_finalize (GObject* obj) {
	EngineComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENGINE_TYPE_COMPONENT, EngineComponent);
	G_OBJECT_CLASS (engine_component_parent_class)->finalize (obj);
}


GType engine_component_get_type (void) {
	static volatile gsize engine_component_type_id__volatile = 0;
	if (g_once_init_enter (&engine_component_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EngineComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) engine_component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EngineComponent), 0, (GInstanceInitFunc) engine_component_instance_init, NULL };
		GType engine_component_type_id;
		engine_component_type_id = g_type_register_static (G_TYPE_OBJECT, "EngineComponent", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&engine_component_type_id__volatile, engine_component_type_id);
	}
	return engine_component_type_id__volatile;
}


static void _vala_engine_component_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	EngineComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENGINE_TYPE_COMPONENT, EngineComponent);
	switch (property_id) {
		case ENGINE_COMPONENT_ENTITY:
		g_value_set_object (value, engine_component_get_entity (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_engine_component_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	EngineComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENGINE_TYPE_COMPONENT, EngineComponent);
	switch (property_id) {
		case ENGINE_COMPONENT_ENTITY:
		engine_component_set_entity (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void engine_update_component_real_update (EngineUpdateComponent* self) {
	g_critical ("Type `%s' does not implement abstract method `engine_update_component_update'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void engine_update_component_update (EngineUpdateComponent* self) {
	g_return_if_fail (self != NULL);
	ENGINE_UPDATE_COMPONENT_GET_CLASS (self)->update (self);
}


EngineUpdateComponent* engine_update_component_construct (GType object_type) {
	EngineUpdateComponent * self = NULL;
	self = (EngineUpdateComponent*) engine_component_construct (object_type);
	return self;
}


static void engine_update_component_class_init (EngineUpdateComponentClass * klass) {
	engine_update_component_parent_class = g_type_class_peek_parent (klass);
	((EngineUpdateComponentClass *) klass)->update = engine_update_component_real_update;
}


static void engine_update_component_instance_init (EngineUpdateComponent * self) {
}


GType engine_update_component_get_type (void) {
	static volatile gsize engine_update_component_type_id__volatile = 0;
	if (g_once_init_enter (&engine_update_component_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EngineUpdateComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) engine_update_component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EngineUpdateComponent), 0, (GInstanceInitFunc) engine_update_component_instance_init, NULL };
		GType engine_update_component_type_id;
		engine_update_component_type_id = g_type_register_static (ENGINE_TYPE_COMPONENT, "EngineUpdateComponent", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&engine_update_component_type_id__volatile, engine_update_component_type_id);
	}
	return engine_update_component_type_id__volatile;
}



