/* systemmanager.c generated by valac 0.32.0, the Vala compiler
 * generated from systemmanager.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <gobject/gvaluecollector.h>


#define ENGINE_TYPE_SYSTEM_MANAGER (engine_system_manager_get_type ())
#define ENGINE_SYSTEM_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENGINE_TYPE_SYSTEM_MANAGER, EngineSystemManager))
#define ENGINE_SYSTEM_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENGINE_TYPE_SYSTEM_MANAGER, EngineSystemManagerClass))
#define ENGINE_IS_SYSTEM_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENGINE_TYPE_SYSTEM_MANAGER))
#define ENGINE_IS_SYSTEM_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENGINE_TYPE_SYSTEM_MANAGER))
#define ENGINE_SYSTEM_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENGINE_TYPE_SYSTEM_MANAGER, EngineSystemManagerClass))

typedef struct _EngineSystemManager EngineSystemManager;
typedef struct _EngineSystemManagerClass EngineSystemManagerClass;
typedef struct _EngineSystemManagerPrivate EngineSystemManagerPrivate;

#define ENGINE_TYPE_SYSTEM (engine_system_get_type ())
#define ENGINE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENGINE_TYPE_SYSTEM, EngineSystem))
#define ENGINE_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENGINE_TYPE_SYSTEM, EngineSystemClass))
#define ENGINE_IS_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENGINE_TYPE_SYSTEM))
#define ENGINE_IS_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENGINE_TYPE_SYSTEM))
#define ENGINE_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENGINE_TYPE_SYSTEM, EngineSystemClass))

typedef struct _EngineSystem EngineSystem;
typedef struct _EngineSystemClass EngineSystemClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _EngineParamSpecSystemManager EngineParamSpecSystemManager;

struct _EngineSystemManager {
	GTypeInstance parent_instance;
	volatile int ref_count;
	EngineSystemManagerPrivate * priv;
};

struct _EngineSystemManagerClass {
	GTypeClass parent_class;
	void (*finalize) (EngineSystemManager *self);
};

struct _EngineSystemManagerPrivate {
	GeeList* systems;
	GeeMap* systemsByType;
};

struct _EngineParamSpecSystemManager {
	GParamSpec parent_instance;
};


static gpointer engine_system_manager_parent_class = NULL;

gpointer engine_system_manager_ref (gpointer instance);
void engine_system_manager_unref (gpointer instance);
GParamSpec* engine_param_spec_system_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void engine_value_set_system_manager (GValue* value, gpointer v_object);
void engine_value_take_system_manager (GValue* value, gpointer v_object);
gpointer engine_value_get_system_manager (const GValue* value);
GType engine_system_manager_get_type (void) G_GNUC_CONST;
GType engine_system_get_type (void) G_GNUC_CONST;
#define ENGINE_SYSTEM_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ENGINE_TYPE_SYSTEM_MANAGER, EngineSystemManagerPrivate))
enum  {
	ENGINE_SYSTEM_MANAGER_DUMMY_PROPERTY
};
EngineSystemManager* engine_system_manager_new (void);
EngineSystemManager* engine_system_manager_construct (GType object_type);
void engine_system_manager_addSystem (EngineSystemManager* self, EngineSystem* system);
EngineSystem* engine_system_manager_getSystem (EngineSystemManager* self, GType t);
void engine_system_manager_removeSystem (EngineSystemManager* self, EngineSystem* system);
GeeList* engine_system_manager_getSystems (EngineSystemManager* self);
static void engine_system_manager_finalize (EngineSystemManager* obj);


EngineSystemManager* engine_system_manager_construct (GType object_type) {
	EngineSystemManager* self = NULL;
	self = (EngineSystemManager*) g_type_create_instance (object_type);
	return self;
}


EngineSystemManager* engine_system_manager_new (void) {
	return engine_system_manager_construct (ENGINE_TYPE_SYSTEM_MANAGER);
}


void engine_system_manager_addSystem (EngineSystemManager* self, EngineSystem* system) {
	GType t = 0UL;
	EngineSystem* _tmp0_ = NULL;
	GType _tmp1_ = 0UL;
	EngineSystem* oldSystem = NULL;
	GType _tmp2_ = 0UL;
	EngineSystem* _tmp3_ = NULL;
	EngineSystem* _tmp4_ = NULL;
	GeeList* _tmp6_ = NULL;
	EngineSystem* _tmp7_ = NULL;
	GeeMap* _tmp8_ = NULL;
	GType _tmp9_ = 0UL;
	EngineSystem* _tmp10_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (system != NULL);
	_tmp0_ = system;
	_tmp1_ = G_TYPE_FROM_INSTANCE ((GObject*) _tmp0_);
	t = _tmp1_;
	_tmp2_ = t;
	_tmp3_ = engine_system_manager_getSystem (self, _tmp2_);
	oldSystem = _tmp3_;
	_tmp4_ = oldSystem;
	if (_tmp4_ != NULL) {
		EngineSystem* _tmp5_ = NULL;
		_tmp5_ = oldSystem;
		engine_system_manager_removeSystem (self, _tmp5_);
	}
	_tmp6_ = self->priv->systems;
	_tmp7_ = system;
	gee_collection_add ((GeeCollection*) _tmp6_, _tmp7_);
	_tmp8_ = self->priv->systemsByType;
	_tmp9_ = t;
	_tmp10_ = system;
	gee_map_set (_tmp8_, (gpointer) ((gintptr) _tmp9_), _tmp10_);
	_g_object_unref0 (oldSystem);
}


void engine_system_manager_removeSystem (EngineSystemManager* self, EngineSystem* system) {
	GeeList* _tmp0_ = NULL;
	EngineSystem* _tmp1_ = NULL;
	GeeMap* _tmp2_ = NULL;
	EngineSystem* _tmp3_ = NULL;
	GType _tmp4_ = 0UL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (system != NULL);
	_tmp0_ = self->priv->systems;
	_tmp1_ = system;
	gee_collection_remove ((GeeCollection*) _tmp0_, _tmp1_);
	_tmp2_ = self->priv->systemsByType;
	_tmp3_ = system;
	_tmp4_ = G_TYPE_FROM_INSTANCE ((GObject*) _tmp3_);
	gee_map_unset (_tmp2_, (gpointer) ((gintptr) _tmp4_), NULL);
}


EngineSystem* engine_system_manager_getSystem (EngineSystemManager* self, GType t) {
	EngineSystem* result = NULL;
	GeeMap* _tmp0_ = NULL;
	GType _tmp1_ = 0UL;
	gpointer _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->systemsByType;
	_tmp1_ = t;
	_tmp2_ = gee_map_get (_tmp0_, (gpointer) ((gintptr) _tmp1_));
	result = (EngineSystem*) _tmp2_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GeeList* engine_system_manager_getSystems (EngineSystemManager* self) {
	GeeList* result = NULL;
	GeeList* _tmp0_ = NULL;
	GeeList* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->systems;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


static void engine_value_system_manager_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void engine_value_system_manager_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		engine_system_manager_unref (value->data[0].v_pointer);
	}
}


static void engine_value_system_manager_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = engine_system_manager_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer engine_value_system_manager_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* engine_value_system_manager_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		EngineSystemManager* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = engine_system_manager_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* engine_value_system_manager_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	EngineSystemManager** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = engine_system_manager_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* engine_param_spec_system_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	EngineParamSpecSystemManager* spec;
	g_return_val_if_fail (g_type_is_a (object_type, ENGINE_TYPE_SYSTEM_MANAGER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer engine_value_get_system_manager (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, ENGINE_TYPE_SYSTEM_MANAGER), NULL);
	return value->data[0].v_pointer;
}


void engine_value_set_system_manager (GValue* value, gpointer v_object) {
	EngineSystemManager* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, ENGINE_TYPE_SYSTEM_MANAGER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, ENGINE_TYPE_SYSTEM_MANAGER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		engine_system_manager_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		engine_system_manager_unref (old);
	}
}


void engine_value_take_system_manager (GValue* value, gpointer v_object) {
	EngineSystemManager* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, ENGINE_TYPE_SYSTEM_MANAGER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, ENGINE_TYPE_SYSTEM_MANAGER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		engine_system_manager_unref (old);
	}
}


static void engine_system_manager_class_init (EngineSystemManagerClass * klass) {
	engine_system_manager_parent_class = g_type_class_peek_parent (klass);
	((EngineSystemManagerClass *) klass)->finalize = engine_system_manager_finalize;
	g_type_class_add_private (klass, sizeof (EngineSystemManagerPrivate));
}


static void engine_system_manager_instance_init (EngineSystemManager * self) {
	GeeArrayList* _tmp0_ = NULL;
	GeeHashMap* _tmp1_ = NULL;
	self->priv = ENGINE_SYSTEM_MANAGER_GET_PRIVATE (self);
	_tmp0_ = gee_array_list_new (ENGINE_TYPE_SYSTEM, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	self->priv->systems = (GeeList*) _tmp0_;
	_tmp1_ = gee_hash_map_new (G_TYPE_GTYPE, NULL, NULL, ENGINE_TYPE_SYSTEM, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	self->priv->systemsByType = (GeeMap*) _tmp1_;
	self->ref_count = 1;
}


static void engine_system_manager_finalize (EngineSystemManager* obj) {
	EngineSystemManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENGINE_TYPE_SYSTEM_MANAGER, EngineSystemManager);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->priv->systems);
	_g_object_unref0 (self->priv->systemsByType);
}


GType engine_system_manager_get_type (void) {
	static volatile gsize engine_system_manager_type_id__volatile = 0;
	if (g_once_init_enter (&engine_system_manager_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { engine_value_system_manager_init, engine_value_system_manager_free_value, engine_value_system_manager_copy_value, engine_value_system_manager_peek_pointer, "p", engine_value_system_manager_collect_value, "p", engine_value_system_manager_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (EngineSystemManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) engine_system_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EngineSystemManager), 0, (GInstanceInitFunc) engine_system_manager_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType engine_system_manager_type_id;
		engine_system_manager_type_id = g_type_register_fundamental (g_type_fundamental_next (), "EngineSystemManager", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&engine_system_manager_type_id__volatile, engine_system_manager_type_id);
	}
	return engine_system_manager_type_id__volatile;
}


gpointer engine_system_manager_ref (gpointer instance) {
	EngineSystemManager* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void engine_system_manager_unref (gpointer instance) {
	EngineSystemManager* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		ENGINE_SYSTEM_MANAGER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



