/* collisionsystem.c generated by valac 0.32.0, the Vala compiler
 * generated from collisionsystem.vala, do not modify */

/* modules: sdl2 engine gee-0.8*/
/* vapidirs: ../../engine*/

#include <glib.h>
#include <glib-object.h>
#include <engine.h>
#include <gee.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_render.h>
#include <tiled.h>
#include <SDL2/SDL_rect.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_pixels.h>


#define TYPE_COLLISION_SYSTEM (collision_system_get_type ())
#define COLLISION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COLLISION_SYSTEM, CollisionSystem))
#define COLLISION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COLLISION_SYSTEM, CollisionSystemClass))
#define IS_COLLISION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COLLISION_SYSTEM))
#define IS_COLLISION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COLLISION_SYSTEM))
#define COLLISION_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COLLISION_SYSTEM, CollisionSystemClass))

typedef struct _CollisionSystem CollisionSystem;
typedef struct _CollisionSystemClass CollisionSystemClass;
typedef struct _CollisionSystemPrivate CollisionSystemPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_TILEMAP_COMPONENT2 (tilemap_component2_get_type ())
#define TILEMAP_COMPONENT2(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TILEMAP_COMPONENT2, TilemapComponent2))
#define TILEMAP_COMPONENT2_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TILEMAP_COMPONENT2, TilemapComponent2Class))
#define IS_TILEMAP_COMPONENT2(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TILEMAP_COMPONENT2))
#define IS_TILEMAP_COMPONENT2_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TILEMAP_COMPONENT2))
#define TILEMAP_COMPONENT2_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TILEMAP_COMPONENT2, TilemapComponent2Class))

typedef struct _TilemapComponent2 TilemapComponent2;
typedef struct _TilemapComponent2Class TilemapComponent2Class;

#define TYPE_COLLISION_COMPONENT (collision_component_get_type ())
#define COLLISION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COLLISION_COMPONENT, CollisionComponent))
#define COLLISION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COLLISION_COMPONENT, CollisionComponentClass))
#define IS_COLLISION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COLLISION_COMPONENT))
#define IS_COLLISION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COLLISION_COMPONENT))
#define COLLISION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COLLISION_COMPONENT, CollisionComponentClass))

typedef struct _CollisionComponent CollisionComponent;
typedef struct _CollisionComponentClass CollisionComponentClass;

#define TYPE_POSITION_COMPONENT (position_component_get_type ())
#define POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_POSITION_COMPONENT, PositionComponent))
#define POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_POSITION_COMPONENT, PositionComponentClass))
#define IS_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_POSITION_COMPONENT))
#define IS_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_POSITION_COMPONENT))
#define POSITION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_POSITION_COMPONENT, PositionComponentClass))

typedef struct _PositionComponent PositionComponent;
typedef struct _PositionComponentClass PositionComponentClass;

#define TYPE_MOVEMENT_COMPONENT (movement_component_get_type ())
#define MOVEMENT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MOVEMENT_COMPONENT, MovementComponent))
#define MOVEMENT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MOVEMENT_COMPONENT, MovementComponentClass))
#define IS_MOVEMENT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MOVEMENT_COMPONENT))
#define IS_MOVEMENT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MOVEMENT_COMPONENT))
#define MOVEMENT_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MOVEMENT_COMPONENT, MovementComponentClass))

typedef struct _MovementComponent MovementComponent;
typedef struct _MovementComponentClass MovementComponentClass;
typedef struct _PositionComponentPrivate PositionComponentPrivate;

#define POSITION_COMPONENT_TYPE_ENTITY_STATE (position_component_entity_state_get_type ())
typedef struct _TilemapComponent2Private TilemapComponent2Private;

#define TYPE_TEXT_COMPONENT (text_component_get_type ())
#define TEXT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXT_COMPONENT, TextComponent))
#define TEXT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXT_COMPONENT, TextComponentClass))
#define IS_TEXT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXT_COMPONENT))
#define IS_TEXT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXT_COMPONENT))
#define TEXT_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXT_COMPONENT, TextComponentClass))

typedef struct _TextComponent TextComponent;
typedef struct _TextComponentClass TextComponentClass;

#define TYPE_ANIMATION_COMPONENT (animation_component_get_type ())
#define ANIMATION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ANIMATION_COMPONENT, AnimationComponent))
#define ANIMATION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ANIMATION_COMPONENT, AnimationComponentClass))
#define IS_ANIMATION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ANIMATION_COMPONENT))
#define IS_ANIMATION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ANIMATION_COMPONENT))
#define ANIMATION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ANIMATION_COMPONENT, AnimationComponentClass))

typedef struct _AnimationComponent AnimationComponent;
typedef struct _AnimationComponentClass AnimationComponentClass;
typedef struct _TextComponentPrivate TextComponentPrivate;
typedef struct _AnimationComponentPrivate AnimationComponentPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _CollisionSystem {
	EngineEntitySystem parent_instance;
	CollisionSystemPrivate * priv;
};

struct _CollisionSystemClass {
	EngineEntitySystemClass parent_class;
};

struct _CollisionSystemPrivate {
	EngineEntity* mapentity;
};

typedef enum  {
	POSITION_COMPONENT_ENTITY_STATE_GROUND,
	POSITION_COMPONENT_ENTITY_STATE_AIR
} PositionComponentEntityState;

struct _PositionComponent {
	EngineComponent parent_instance;
	PositionComponentPrivate * priv;
	gint x;
	gint y;
	gint velocity_x;
	gint velocity_y;
	PositionComponentEntityState state;
	SDL_RendererFlip flip;
};

struct _PositionComponentClass {
	EngineComponentClass parent_class;
};

struct _TilemapComponent2 {
	EngineComponent parent_instance;
	TilemapComponent2Private * priv;
	TiledMap* map;
};

struct _TilemapComponent2Class {
	EngineComponentClass parent_class;
};

struct _TextComponent {
	EngineComponent parent_instance;
	TextComponentPrivate * priv;
	gchar* font;
	gchar* text;
	gboolean visible;
	gint timer;
	SDL_Color color;
};

struct _TextComponentClass {
	EngineComponentClass parent_class;
};

struct _AnimationComponent {
	EngineComponent parent_instance;
	AnimationComponentPrivate * priv;
	gchar* current_animation;
	gint sprite_width;
};

struct _AnimationComponentClass {
	EngineComponentClass parent_class;
};


static gpointer collision_system_parent_class = NULL;

GType collision_system_get_type (void) G_GNUC_CONST;
#define COLLISION_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_COLLISION_SYSTEM, CollisionSystemPrivate))
enum  {
	COLLISION_SYSTEM_DUMMY_PROPERTY
};
static void collision_system_real_addedToEngine (EngineSystem* base, EngineEngine* engine);
GType tilemap_component2_get_type (void) G_GNUC_CONST;
static GType* collision_system_real_getEntityTypes (EngineEntitySystem* base, int* result_length1);
GType collision_component_get_type (void) G_GNUC_CONST;
GType position_component_get_type (void) G_GNUC_CONST;
static void collision_system_real_update (EngineSystem* base, gfloat deltaTime);
GType movement_component_get_type (void) G_GNUC_CONST;
GType position_component_entity_state_get_type (void) G_GNUC_CONST;
void collision_component_getHAbsoluteBox (CollisionComponent* self, SDL_Rect* result);
void collision_component_getAbsoluteBox (CollisionComponent* self, SDL_Rect* result);
GType text_component_get_type (void) G_GNUC_CONST;
GType animation_component_get_type (void) G_GNUC_CONST;
CollisionSystem* collision_system_new (void);
CollisionSystem* collision_system_construct (GType object_type);
static void collision_system_finalize (GObject* obj);


static void collision_system_real_addedToEngine (EngineSystem* base, EngineEngine* engine) {
	CollisionSystem * self;
	EngineEngine* _tmp0_ = NULL;
	EngineEngine* _tmp1_ = NULL;
	GType* _tmp2_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
	GeeArrayList* _tmp4_ = NULL;
	GeeList* _tmp5_ = NULL;
	GeeList* _tmp6_ = NULL;
	gpointer _tmp7_ = NULL;
	self = (CollisionSystem*) base;
	g_return_if_fail (engine != NULL);
	_tmp0_ = engine;
	ENGINE_SYSTEM_CLASS (collision_system_parent_class)->addedToEngine ((EngineSystem*) G_TYPE_CHECK_INSTANCE_CAST (self, ENGINE_TYPE_ENTITY_SYSTEM, EngineEntitySystem), _tmp0_);
	_tmp1_ = engine;
	_tmp2_ = g_new0 (GType, 1);
	_tmp2_[0] = TYPE_TILEMAP_COMPONENT2;
	_tmp3_ = gee_array_list_new_wrap (G_TYPE_GTYPE, NULL, NULL, _tmp2_, 1, NULL, NULL, NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = engine_engine_getEntitiesFor (_tmp1_, (GeeList*) _tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = gee_list_get (_tmp6_, 0);
	_g_object_unref0 (self->priv->mapentity);
	self->priv->mapentity = (EngineEntity*) _tmp7_;
	_g_object_unref0 (_tmp6_);
	_g_object_unref0 (_tmp4_);
}


static GType* collision_system_real_getEntityTypes (EngineEntitySystem* base, int* result_length1) {
	CollisionSystem * self;
	GType* result = NULL;
	GType* _tmp0_ = NULL;
	GType* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	self = (CollisionSystem*) base;
	_tmp0_ = g_new0 (GType, 2);
	_tmp0_[0] = TYPE_COLLISION_COMPONENT;
	_tmp0_[1] = TYPE_POSITION_COMPONENT;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = 2;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void collision_system_real_update (EngineSystem* base, gfloat deltaTime) {
	CollisionSystem * self;
	EngineEngine* _tmp0_ = NULL;
	EngineState _tmp1_ = 0;
	self = (CollisionSystem*) base;
	_tmp0_ = ((EngineSystem*) self)->engine;
	_tmp1_ = _tmp0_->state;
	if (_tmp1_ != ENGINE_STATE_PAUSED) {
		{
			GeeList* _e_list = NULL;
			GeeList* _tmp2_ = NULL;
			GeeList* _tmp3_ = NULL;
			gint _e_size = 0;
			GeeList* _tmp4_ = NULL;
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _e_index = 0;
			_tmp2_ = ((EngineEntitySystem*) self)->entities;
			_tmp3_ = _g_object_ref0 (_tmp2_);
			_e_list = _tmp3_;
			_tmp4_ = _e_list;
			_tmp5_ = gee_collection_get_size ((GeeCollection*) _tmp4_);
			_tmp6_ = _tmp5_;
			_e_size = _tmp6_;
			_e_index = -1;
			while (TRUE) {
				gint _tmp7_ = 0;
				gint _tmp8_ = 0;
				gint _tmp9_ = 0;
				EngineEntity* e = NULL;
				GeeList* _tmp10_ = NULL;
				gint _tmp11_ = 0;
				gpointer _tmp12_ = NULL;
				PositionComponent* pos = NULL;
				EngineEntity* _tmp13_ = NULL;
				gpointer _tmp14_ = NULL;
				CollisionComponent* collision = NULL;
				EngineEntity* _tmp15_ = NULL;
				gpointer _tmp16_ = NULL;
				MovementComponent* move = NULL;
				EngineEntity* _tmp17_ = NULL;
				gpointer _tmp18_ = NULL;
				MovementComponent* _tmp19_ = NULL;
				TilemapComponent2* mapcomponent = NULL;
				EngineEntity* _tmp25_ = NULL;
				gpointer _tmp26_ = NULL;
				TilemapComponent2* _tmp27_ = NULL;
				TiledMap* _tmp28_ = NULL;
				CollisionComponent* _tmp29_ = NULL;
				SDL_Rect _tmp30_ = {0};
				gboolean _tmp31_ = FALSE;
				TilemapComponent2* _tmp33_ = NULL;
				TiledMap* _tmp34_ = NULL;
				CollisionComponent* _tmp35_ = NULL;
				SDL_Rect _tmp36_ = {0};
				gboolean _tmp37_ = FALSE;
				_tmp7_ = _e_index;
				_e_index = _tmp7_ + 1;
				_tmp8_ = _e_index;
				_tmp9_ = _e_size;
				if (!(_tmp8_ < _tmp9_)) {
					break;
				}
				_tmp10_ = _e_list;
				_tmp11_ = _e_index;
				_tmp12_ = gee_list_get (_tmp10_, _tmp11_);
				e = (EngineEntity*) _tmp12_;
				_tmp13_ = e;
				_tmp14_ = engine_entity_get_component (_tmp13_, TYPE_POSITION_COMPONENT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
				pos = (PositionComponent*) _tmp14_;
				_tmp15_ = e;
				_tmp16_ = engine_entity_get_component (_tmp15_, TYPE_COLLISION_COMPONENT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
				collision = (CollisionComponent*) _tmp16_;
				_tmp17_ = e;
				_tmp18_ = engine_entity_get_component (_tmp17_, TYPE_MOVEMENT_COMPONENT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
				move = (MovementComponent*) _tmp18_;
				_tmp19_ = move;
				if (_tmp19_ != NULL) {
					PositionComponent* _tmp20_ = NULL;
					gint _tmp21_ = 0;
					_tmp20_ = pos;
					_tmp21_ = _tmp20_->velocity_y;
					if (_tmp21_ < 4) {
						PositionComponent* _tmp22_ = NULL;
						PositionComponent* _tmp23_ = NULL;
						gint _tmp24_ = 0;
						_tmp22_ = pos;
						_tmp23_ = pos;
						_tmp24_ = _tmp23_->velocity_y;
						_tmp23_->velocity_y = _tmp24_ + 1;
					}
				}
				_tmp25_ = self->priv->mapentity;
				_tmp26_ = engine_entity_get_component (_tmp25_, TYPE_TILEMAP_COMPONENT2, (GBoxedCopyFunc) g_object_ref, g_object_unref);
				mapcomponent = (TilemapComponent2*) _tmp26_;
				_tmp27_ = mapcomponent;
				_tmp28_ = _tmp27_->map;
				_tmp29_ = collision;
				collision_component_getHAbsoluteBox (_tmp29_, &_tmp30_);
				_tmp31_ = tiled_map_collidesHorizontal (_tmp28_, &_tmp30_);
				if (_tmp31_) {
					PositionComponent* _tmp32_ = NULL;
					_tmp32_ = pos;
					_tmp32_->velocity_x = 0;
				}
				_tmp33_ = mapcomponent;
				_tmp34_ = _tmp33_->map;
				_tmp35_ = collision;
				collision_component_getAbsoluteBox (_tmp35_, &_tmp36_);
				_tmp37_ = tiled_map_collidesWith (_tmp34_, &_tmp36_);
				if (_tmp37_) {
					PositionComponent* _tmp38_ = NULL;
					PositionComponent* _tmp39_ = NULL;
					_tmp38_ = pos;
					_tmp38_->velocity_y = 0;
					_tmp39_ = pos;
					_tmp39_->state = POSITION_COMPONENT_ENTITY_STATE_GROUND;
				}
				{
					GeeList* _e2_list = NULL;
					GeeList* _tmp40_ = NULL;
					GeeList* _tmp41_ = NULL;
					gint _e2_size = 0;
					GeeList* _tmp42_ = NULL;
					gint _tmp43_ = 0;
					gint _tmp44_ = 0;
					gint _e2_index = 0;
					_tmp40_ = ((EngineEntitySystem*) self)->entities;
					_tmp41_ = _g_object_ref0 (_tmp40_);
					_e2_list = _tmp41_;
					_tmp42_ = _e2_list;
					_tmp43_ = gee_collection_get_size ((GeeCollection*) _tmp42_);
					_tmp44_ = _tmp43_;
					_e2_size = _tmp44_;
					_e2_index = -1;
					while (TRUE) {
						gint _tmp45_ = 0;
						gint _tmp46_ = 0;
						gint _tmp47_ = 0;
						EngineEntity* e2 = NULL;
						GeeList* _tmp48_ = NULL;
						gint _tmp49_ = 0;
						gpointer _tmp50_ = NULL;
						EngineEntity* _tmp51_ = NULL;
						EngineEntity* _tmp52_ = NULL;
						_tmp45_ = _e2_index;
						_e2_index = _tmp45_ + 1;
						_tmp46_ = _e2_index;
						_tmp47_ = _e2_size;
						if (!(_tmp46_ < _tmp47_)) {
							break;
						}
						_tmp48_ = _e2_list;
						_tmp49_ = _e2_index;
						_tmp50_ = gee_list_get (_tmp48_, _tmp49_);
						e2 = (EngineEntity*) _tmp50_;
						_tmp51_ = e2;
						_tmp52_ = e;
						if (_tmp51_ != _tmp52_) {
							CollisionComponent* collision2 = NULL;
							EngineEntity* _tmp53_ = NULL;
							gpointer _tmp54_ = NULL;
							TextComponent* textc = NULL;
							EngineEntity* _tmp55_ = NULL;
							gpointer _tmp56_ = NULL;
							AnimationComponent* ani = NULL;
							EngineEntity* _tmp57_ = NULL;
							gpointer _tmp58_ = NULL;
							CollisionComponent* _tmp59_ = NULL;
							SDL_Rect _tmp60_ = {0};
							CollisionComponent* _tmp61_ = NULL;
							SDL_Rect _tmp62_ = {0};
							gboolean _tmp63_ = FALSE;
							CollisionComponent* _tmp65_ = NULL;
							SDL_Rect _tmp66_ = {0};
							CollisionComponent* _tmp67_ = NULL;
							SDL_Rect _tmp68_ = {0};
							gboolean _tmp69_ = FALSE;
							_tmp53_ = e2;
							_tmp54_ = engine_entity_get_component (_tmp53_, TYPE_COLLISION_COMPONENT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
							collision2 = (CollisionComponent*) _tmp54_;
							_tmp55_ = e2;
							_tmp56_ = engine_entity_get_component (_tmp55_, TYPE_TEXT_COMPONENT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
							textc = (TextComponent*) _tmp56_;
							_tmp57_ = e2;
							_tmp58_ = engine_entity_get_component (_tmp57_, TYPE_ANIMATION_COMPONENT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
							ani = (AnimationComponent*) _tmp58_;
							_tmp59_ = collision;
							collision_component_getHAbsoluteBox (_tmp59_, &_tmp60_);
							_tmp61_ = collision2;
							collision_component_getHAbsoluteBox (_tmp61_, &_tmp62_);
							_tmp63_ = SDL_HasIntersection (&_tmp60_, &_tmp62_);
							if (_tmp63_) {
								PositionComponent* _tmp64_ = NULL;
								_tmp64_ = pos;
								_tmp64_->velocity_x = 0;
							}
							_tmp65_ = collision;
							collision_component_getAbsoluteBox (_tmp65_, &_tmp66_);
							_tmp67_ = collision2;
							collision_component_getAbsoluteBox (_tmp67_, &_tmp68_);
							_tmp69_ = SDL_HasIntersection (&_tmp66_, &_tmp68_);
							if (_tmp69_) {
								PositionComponent* _tmp70_ = NULL;
								PositionComponent* _tmp71_ = NULL;
								TextComponent* _tmp72_ = NULL;
								_tmp70_ = pos;
								_tmp70_->velocity_y = 0;
								_tmp71_ = pos;
								_tmp71_->state = POSITION_COMPONENT_ENTITY_STATE_GROUND;
								_tmp72_ = textc;
								if (_tmp72_ != NULL) {
									TextComponent* _tmp73_ = NULL;
									TextComponent* _tmp74_ = NULL;
									AnimationComponent* _tmp75_ = NULL;
									_tmp73_ = textc;
									_tmp73_->visible = TRUE;
									_tmp74_ = textc;
									_tmp74_->timer = 60;
									_tmp75_ = ani;
									if (_tmp75_ != NULL) {
										AnimationComponent* _tmp76_ = NULL;
										gchar* _tmp77_ = NULL;
										_tmp76_ = ani;
										_tmp77_ = g_strdup ("touched");
										_g_free0 (_tmp76_->current_animation);
										_tmp76_->current_animation = _tmp77_;
									}
								}
							} else {
								TextComponent* _tmp78_ = NULL;
								_tmp78_ = textc;
								if (_tmp78_ != NULL) {
									TextComponent* _tmp79_ = NULL;
									TextComponent* _tmp80_ = NULL;
									gint _tmp81_ = 0;
									TextComponent* _tmp82_ = NULL;
									gint _tmp83_ = 0;
									_tmp79_ = textc;
									_tmp80_ = textc;
									_tmp81_ = _tmp80_->timer;
									_tmp80_->timer = _tmp81_ - 1;
									_tmp82_ = textc;
									_tmp83_ = _tmp82_->timer;
									if (_tmp83_ == 0) {
										TextComponent* _tmp84_ = NULL;
										_tmp84_ = textc;
										_tmp84_->visible = FALSE;
									}
								}
							}
							_g_object_unref0 (ani);
							_g_object_unref0 (textc);
							_g_object_unref0 (collision2);
						}
						_g_object_unref0 (e2);
					}
					_g_object_unref0 (_e2_list);
				}
				_g_object_unref0 (mapcomponent);
				_g_object_unref0 (move);
				_g_object_unref0 (collision);
				_g_object_unref0 (pos);
				_g_object_unref0 (e);
			}
			_g_object_unref0 (_e_list);
		}
	}
}


CollisionSystem* collision_system_construct (GType object_type) {
	CollisionSystem * self = NULL;
	self = (CollisionSystem*) engine_entity_system_construct (object_type);
	return self;
}


CollisionSystem* collision_system_new (void) {
	return collision_system_construct (TYPE_COLLISION_SYSTEM);
}


static void collision_system_class_init (CollisionSystemClass * klass) {
	collision_system_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CollisionSystemPrivate));
	((EngineSystemClass *) klass)->addedToEngine = collision_system_real_addedToEngine;
	((EngineEntitySystemClass *) klass)->getEntityTypes = collision_system_real_getEntityTypes;
	((EngineSystemClass *) klass)->update = collision_system_real_update;
	G_OBJECT_CLASS (klass)->finalize = collision_system_finalize;
}


static void collision_system_instance_init (CollisionSystem * self) {
	self->priv = COLLISION_SYSTEM_GET_PRIVATE (self);
}


static void collision_system_finalize (GObject* obj) {
	CollisionSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_COLLISION_SYSTEM, CollisionSystem);
	_g_object_unref0 (self->priv->mapentity);
	G_OBJECT_CLASS (collision_system_parent_class)->finalize (obj);
}


GType collision_system_get_type (void) {
	static volatile gsize collision_system_type_id__volatile = 0;
	if (g_once_init_enter (&collision_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CollisionSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) collision_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CollisionSystem), 0, (GInstanceInitFunc) collision_system_instance_init, NULL };
		GType collision_system_type_id;
		collision_system_type_id = g_type_register_static (ENGINE_TYPE_ENTITY_SYSTEM, "CollisionSystem", &g_define_type_info, 0);
		g_once_init_leave (&collision_system_type_id__volatile, collision_system_type_id);
	}
	return collision_system_type_id__volatile;
}



