/* textrendersystem.c generated by valac 0.32.0, the Vala compiler
 * generated from textrendersystem.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <engine.h>
#include <SDL2/SDL_render.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_pixels.h>
#include <SDL2/SDL_ttf.h>
#include <SDL2/SDL_surface.h>
#include <SDL2/SDL_rect.h>


#define TYPE_TEXT_RENDER_SYSTEM (text_render_system_get_type ())
#define TEXT_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXT_RENDER_SYSTEM, TextRenderSystem))
#define TEXT_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXT_RENDER_SYSTEM, TextRenderSystemClass))
#define IS_TEXT_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXT_RENDER_SYSTEM))
#define IS_TEXT_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXT_RENDER_SYSTEM))
#define TEXT_RENDER_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXT_RENDER_SYSTEM, TextRenderSystemClass))

typedef struct _TextRenderSystem TextRenderSystem;
typedef struct _TextRenderSystemClass TextRenderSystemClass;
typedef struct _TextRenderSystemPrivate TextRenderSystemPrivate;

#define TYPE_FONT_MANAGER (font_manager_get_type ())
#define FONT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FONT_MANAGER, FontManager))
#define FONT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FONT_MANAGER, FontManagerClass))
#define IS_FONT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FONT_MANAGER))
#define IS_FONT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FONT_MANAGER))
#define FONT_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FONT_MANAGER, FontManagerClass))

typedef struct _FontManager FontManager;
typedef struct _FontManagerClass FontManagerClass;

#define TYPE_TEXT_COMPONENT (text_component_get_type ())
#define TEXT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXT_COMPONENT, TextComponent))
#define TEXT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXT_COMPONENT, TextComponentClass))
#define IS_TEXT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXT_COMPONENT))
#define IS_TEXT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXT_COMPONENT))
#define TEXT_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXT_COMPONENT, TextComponentClass))

typedef struct _TextComponent TextComponent;
typedef struct _TextComponentClass TextComponentClass;
typedef struct _TextComponentPrivate TextComponentPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _SDL_DestroyTexture0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyTexture (var), NULL)))
#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))

struct _TextRenderSystem {
	EngineIteratingEntitySystem parent_instance;
	TextRenderSystemPrivate * priv;
};

struct _TextRenderSystemClass {
	EngineIteratingEntitySystemClass parent_class;
};

struct _TextRenderSystemPrivate {
	FontManager* fontManager;
	SDL_Renderer* renderer;
};

struct _TextComponent {
	EngineComponent parent_instance;
	TextComponentPrivate * priv;
	gchar* font;
	gchar* text;
	gboolean visible;
	gint timer;
	SDL_Color color;
};

struct _TextComponentClass {
	EngineComponentClass parent_class;
};


static gpointer text_render_system_parent_class = NULL;

GType text_render_system_get_type (void) G_GNUC_CONST;
GType font_manager_get_type (void) G_GNUC_CONST;
#define TEXT_RENDER_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_TEXT_RENDER_SYSTEM, TextRenderSystemPrivate))
enum  {
	TEXT_RENDER_SYSTEM_DUMMY_PROPERTY
};
TextRenderSystem* text_render_system_new (FontManager* fontManager, SDL_Renderer* renderer);
TextRenderSystem* text_render_system_construct (GType object_type, FontManager* fontManager, SDL_Renderer* renderer);
static GType* text_render_system_real_getEntityTypes (EngineEntitySystem* base, int* result_length1);
GType text_component_get_type (void) G_GNUC_CONST;
static void text_render_system_real_processEntity (EngineIteratingEntitySystem* base, gfloat deltaTime, EngineEntity* e);
TTF_Font* font_manager_getFont (FontManager* self, const gchar* identifier);
static void text_render_system_finalize (GObject* obj);


TextRenderSystem* text_render_system_construct (GType object_type, FontManager* fontManager, SDL_Renderer* renderer) {
	TextRenderSystem * self = NULL;
	FontManager* _tmp0_ = NULL;
	SDL_Renderer* _tmp1_ = NULL;
	g_return_val_if_fail (fontManager != NULL, NULL);
	g_return_val_if_fail (renderer != NULL, NULL);
	self = (TextRenderSystem*) engine_iterating_entity_system_construct (object_type);
	_tmp0_ = fontManager;
	self->priv->fontManager = _tmp0_;
	_tmp1_ = renderer;
	self->priv->renderer = _tmp1_;
	return self;
}


TextRenderSystem* text_render_system_new (FontManager* fontManager, SDL_Renderer* renderer) {
	return text_render_system_construct (TYPE_TEXT_RENDER_SYSTEM, fontManager, renderer);
}


static GType* text_render_system_real_getEntityTypes (EngineEntitySystem* base, int* result_length1) {
	TextRenderSystem * self;
	GType* result = NULL;
	GType* _tmp0_ = NULL;
	GType* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	self = (TextRenderSystem*) base;
	_tmp0_ = g_new0 (GType, 1);
	_tmp0_[0] = TYPE_TEXT_COMPONENT;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = 1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static void text_render_system_real_processEntity (EngineIteratingEntitySystem* base, gfloat deltaTime, EngineEntity* e) {
	TextRenderSystem * self;
	TextComponent* textc = NULL;
	EngineEntity* _tmp0_ = NULL;
	gpointer _tmp1_ = NULL;
	TextComponent* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	self = (TextRenderSystem*) base;
	g_return_if_fail (e != NULL);
	_tmp0_ = e;
	_tmp1_ = engine_entity_get_component (_tmp0_, TYPE_TEXT_COMPONENT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
	textc = (TextComponent*) _tmp1_;
	_tmp2_ = textc;
	_tmp3_ = _tmp2_->visible;
	if (_tmp3_) {
		TextComponent* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		TTF_Font* font = NULL;
		FontManager* _tmp6_ = NULL;
		TextComponent* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		TTF_Font* _tmp9_ = NULL;
		TTF_Font* _tmp10_ = NULL;
		SDL_Surface* surface = NULL;
		TTF_Font* _tmp11_ = NULL;
		TextComponent* _tmp12_ = NULL;
		const gchar* _tmp13_ = NULL;
		TextComponent* _tmp14_ = NULL;
		SDL_Color _tmp15_ = {0};
		SDL_Surface* _tmp16_ = NULL;
		SDL_Surface* _tmp17_ = NULL;
		SDL_Texture* texture = NULL;
		SDL_Renderer* _tmp18_ = NULL;
		SDL_Surface* _tmp19_ = NULL;
		SDL_Texture* _tmp20_ = NULL;
		SDL_Rect dst = {0};
		SDL_Surface* _tmp21_ = NULL;
		gint _tmp22_ = 0;
		SDL_Surface* _tmp23_ = NULL;
		gint _tmp24_ = 0;
		SDL_Rect _tmp25_ = {0};
		SDL_Renderer* _tmp26_ = NULL;
		SDL_Texture* _tmp27_ = NULL;
		SDL_Rect _tmp28_ = {0};
		_tmp4_ = textc;
		_tmp5_ = _tmp4_->text;
		g_debug ("textrendersystem.vala:22: RENDER STRING %s", _tmp5_);
		_tmp6_ = self->priv->fontManager;
		_tmp7_ = textc;
		_tmp8_ = _tmp7_->font;
		_tmp9_ = font_manager_getFont (_tmp6_, _tmp8_);
		font = _tmp9_;
		_tmp10_ = font;
		if (_tmp10_ == NULL) {
			g_debug ("textrendersystem.vala:25: Font is null");
			_g_object_unref0 (textc);
			return;
		}
		_tmp11_ = font;
		_tmp12_ = textc;
		_tmp13_ = _tmp12_->text;
		_tmp14_ = textc;
		_tmp15_ = _tmp14_->color;
		_tmp16_ = TTF_RenderUTF8_Blended (_tmp11_, _tmp13_, _tmp15_);
		surface = _tmp16_;
		_tmp17_ = surface;
		if (_tmp17_ == NULL) {
			g_debug ("textrendersystem.vala:30: Surface is null");
		}
		_tmp18_ = self->priv->renderer;
		_tmp19_ = surface;
		_tmp20_ = SDL_CreateTextureFromSurface (_tmp18_, _tmp19_);
		texture = _tmp20_;
		_tmp21_ = surface;
		_tmp22_ = _tmp21_->w;
		_tmp23_ = surface;
		_tmp24_ = _tmp23_->h;
		memset (&_tmp25_, 0, sizeof (SDL_Rect));
		_tmp25_.x = 0;
		_tmp25_.y = 0;
		_tmp25_.w = (guint) _tmp22_;
		_tmp25_.h = (guint) _tmp24_;
		dst = _tmp25_;
		_tmp26_ = self->priv->renderer;
		_tmp27_ = texture;
		_tmp28_ = dst;
		SDL_RenderCopy (_tmp26_, _tmp27_, NULL, &_tmp28_);
		_SDL_DestroyTexture0 (texture);
		_SDL_FreeSurface0 (surface);
	}
	_g_object_unref0 (textc);
}


static void text_render_system_class_init (TextRenderSystemClass * klass) {
	text_render_system_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TextRenderSystemPrivate));
	((EngineEntitySystemClass *) klass)->getEntityTypes = text_render_system_real_getEntityTypes;
	((EngineIteratingEntitySystemClass *) klass)->processEntity = text_render_system_real_processEntity;
	G_OBJECT_CLASS (klass)->finalize = text_render_system_finalize;
}


static void text_render_system_instance_init (TextRenderSystem * self) {
	self->priv = TEXT_RENDER_SYSTEM_GET_PRIVATE (self);
}


static void text_render_system_finalize (GObject* obj) {
	TextRenderSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TEXT_RENDER_SYSTEM, TextRenderSystem);
	G_OBJECT_CLASS (text_render_system_parent_class)->finalize (obj);
}


GType text_render_system_get_type (void) {
	static volatile gsize text_render_system_type_id__volatile = 0;
	if (g_once_init_enter (&text_render_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TextRenderSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) text_render_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TextRenderSystem), 0, (GInstanceInitFunc) text_render_system_instance_init, NULL };
		GType text_render_system_type_id;
		text_render_system_type_id = g_type_register_static (ENGINE_TYPE_ITERATING_ENTITY_SYSTEM, "TextRenderSystem", &g_define_type_info, 0);
		g_once_init_leave (&text_render_system_type_id__volatile, text_render_system_type_id);
	}
	return text_render_system_type_id__volatile;
}



