/* texturesystem.c generated by valac 0.32.0, the Vala compiler
 * generated from texturesystem.vala, do not modify */

/* modules: sdl2 engine gee-0.8*/
/* vapidirs: ../../engine*/

#include <glib.h>
#include <glib-object.h>
#include <engine.h>
#include <SDL2/SDL_render.h>
#include <float.h>
#include <math.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_TEXTURE_SYSTEM (texture_system_get_type ())
#define TEXTURE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXTURE_SYSTEM, TextureSystem))
#define TEXTURE_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXTURE_SYSTEM, TextureSystemClass))
#define IS_TEXTURE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXTURE_SYSTEM))
#define IS_TEXTURE_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXTURE_SYSTEM))
#define TEXTURE_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXTURE_SYSTEM, TextureSystemClass))

typedef struct _TextureSystem TextureSystem;
typedef struct _TextureSystemClass TextureSystemClass;
typedef struct _TextureSystemPrivate TextureSystemPrivate;

#define TYPE_TEXTURE_MANAGER (texture_manager_get_type ())
#define TEXTURE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXTURE_MANAGER, TextureManager))
#define TEXTURE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXTURE_MANAGER, TextureManagerClass))
#define IS_TEXTURE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXTURE_MANAGER))
#define IS_TEXTURE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXTURE_MANAGER))
#define TEXTURE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXTURE_MANAGER, TextureManagerClass))

typedef struct _TextureManager TextureManager;
typedef struct _TextureManagerClass TextureManagerClass;

#define TYPE_RENDER_COMPONENT (render_component_get_type ())
#define RENDER_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RENDER_COMPONENT, RenderComponent))
#define RENDER_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RENDER_COMPONENT, RenderComponentClass))
#define IS_RENDER_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RENDER_COMPONENT))
#define IS_RENDER_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RENDER_COMPONENT))
#define RENDER_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RENDER_COMPONENT, RenderComponentClass))

typedef struct _RenderComponent RenderComponent;
typedef struct _RenderComponentClass RenderComponentClass;
typedef struct _RenderComponentPrivate RenderComponentPrivate;

#define TYPE_TEXTURE (texture_get_type ())
#define TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXTURE, Texture))
#define TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXTURE, TextureClass))
#define IS_TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXTURE))
#define IS_TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXTURE))
#define TEXTURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXTURE, TextureClass))

typedef struct _Texture Texture;
typedef struct _TextureClass TextureClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _TextureSystem {
	EngineEntitySystem parent_instance;
	TextureSystemPrivate * priv;
};

struct _TextureSystemClass {
	EngineEntitySystemClass parent_class;
};

struct _TextureSystemPrivate {
	SDL_Renderer* renderer;
	TextureManager* textureManager;
};

struct _RenderComponent {
	EngineComponent parent_instance;
	RenderComponentPrivate * priv;
	gchar* identifier;
	gchar* sprite_filename;
	guint w;
	guint h;
};

struct _RenderComponentClass {
	EngineComponentClass parent_class;
};


static gpointer texture_system_parent_class = NULL;

GType texture_system_get_type (void) G_GNUC_CONST;
GType texture_manager_get_type (void) G_GNUC_CONST;
#define TEXTURE_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_TEXTURE_SYSTEM, TextureSystemPrivate))
enum  {
	TEXTURE_SYSTEM_DUMMY_PROPERTY
};
TextureSystem* texture_system_new (SDL_Renderer* renderer, TextureManager* textureManager);
TextureSystem* texture_system_construct (GType object_type, SDL_Renderer* renderer, TextureManager* textureManager);
static GType* texture_system_real_getEntityTypes (EngineEntitySystem* base, int* result_length1);
GType render_component_get_type (void) G_GNUC_CONST;
static void texture_system_real_update (EngineSystem* base, gfloat deltaTime);
gboolean texture_manager_texture_loaded (TextureManager* self, const gchar* identifier);
GType texture_get_type (void) G_GNUC_CONST;
Texture* texture_manager_load (TextureManager* self, const gchar* identifier, const gchar* filename, SDL_Renderer* renderer);
static void texture_system_finalize (GObject* obj);


TextureSystem* texture_system_construct (GType object_type, SDL_Renderer* renderer, TextureManager* textureManager) {
	TextureSystem * self = NULL;
	SDL_Renderer* _tmp0_ = NULL;
	TextureManager* _tmp1_ = NULL;
	g_return_val_if_fail (renderer != NULL, NULL);
	g_return_val_if_fail (textureManager != NULL, NULL);
	self = (TextureSystem*) engine_entity_system_construct (object_type);
	_tmp0_ = renderer;
	self->priv->renderer = _tmp0_;
	_tmp1_ = textureManager;
	self->priv->textureManager = _tmp1_;
	return self;
}


TextureSystem* texture_system_new (SDL_Renderer* renderer, TextureManager* textureManager) {
	return texture_system_construct (TYPE_TEXTURE_SYSTEM, renderer, textureManager);
}


static GType* texture_system_real_getEntityTypes (EngineEntitySystem* base, int* result_length1) {
	TextureSystem * self;
	GType* result = NULL;
	GType* _tmp0_ = NULL;
	GType* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	self = (TextureSystem*) base;
	_tmp0_ = g_new0 (GType, 1);
	_tmp0_[0] = TYPE_RENDER_COMPONENT;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = 1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void texture_system_real_update (EngineSystem* base, gfloat deltaTime) {
	TextureSystem * self;
	self = (TextureSystem*) base;
	{
		GeeList* _e_list = NULL;
		GeeList* _tmp0_ = NULL;
		GeeList* _tmp1_ = NULL;
		gint _e_size = 0;
		GeeList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _e_index = 0;
		_tmp0_ = ((EngineEntitySystem*) self)->entities;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_e_list = _tmp1_;
		_tmp2_ = _e_list;
		_tmp3_ = gee_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_e_size = _tmp4_;
		_e_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			EngineEntity* e = NULL;
			GeeList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			RenderComponent* rendcomp = NULL;
			EngineEntity* _tmp11_ = NULL;
			gpointer _tmp12_ = NULL;
			RenderComponent* _tmp13_ = NULL;
			const gchar* _tmp14_ = NULL;
			TextureManager* _tmp15_ = NULL;
			RenderComponent* _tmp16_ = NULL;
			const gchar* _tmp17_ = NULL;
			gboolean _tmp18_ = FALSE;
			_tmp5_ = _e_index;
			_e_index = _tmp5_ + 1;
			_tmp6_ = _e_index;
			_tmp7_ = _e_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _e_list;
			_tmp9_ = _e_index;
			_tmp10_ = gee_list_get (_tmp8_, _tmp9_);
			e = (EngineEntity*) _tmp10_;
			_tmp11_ = e;
			_tmp12_ = engine_entity_get_component (_tmp11_, TYPE_RENDER_COMPONENT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
			rendcomp = (RenderComponent*) _tmp12_;
			_tmp13_ = rendcomp;
			_tmp14_ = _tmp13_->identifier;
			g_debug ("texturesystem.vala:23: CHECK TEXTURE: %s", _tmp14_);
			_tmp15_ = self->priv->textureManager;
			_tmp16_ = rendcomp;
			_tmp17_ = _tmp16_->identifier;
			_tmp18_ = texture_manager_texture_loaded (_tmp15_, _tmp17_);
			if (!_tmp18_) {
				TextureManager* _tmp19_ = NULL;
				RenderComponent* _tmp20_ = NULL;
				const gchar* _tmp21_ = NULL;
				RenderComponent* _tmp22_ = NULL;
				const gchar* _tmp23_ = NULL;
				SDL_Renderer* _tmp24_ = NULL;
				Texture* _tmp25_ = NULL;
				Texture* _tmp26_ = NULL;
				_tmp19_ = self->priv->textureManager;
				_tmp20_ = rendcomp;
				_tmp21_ = _tmp20_->identifier;
				_tmp22_ = rendcomp;
				_tmp23_ = _tmp22_->sprite_filename;
				_tmp24_ = self->priv->renderer;
				_tmp25_ = texture_manager_load (_tmp19_, _tmp21_, _tmp23_, _tmp24_);
				_tmp26_ = _tmp25_;
				_g_object_unref0 (_tmp26_);
			}
			_g_object_unref0 (rendcomp);
			_g_object_unref0 (e);
		}
		_g_object_unref0 (_e_list);
	}
}


static void texture_system_class_init (TextureSystemClass * klass) {
	texture_system_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TextureSystemPrivate));
	((EngineEntitySystemClass *) klass)->getEntityTypes = texture_system_real_getEntityTypes;
	((EngineSystemClass *) klass)->update = texture_system_real_update;
	G_OBJECT_CLASS (klass)->finalize = texture_system_finalize;
}


static void texture_system_instance_init (TextureSystem * self) {
	self->priv = TEXTURE_SYSTEM_GET_PRIVATE (self);
}


static void texture_system_finalize (GObject* obj) {
	TextureSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TEXTURE_SYSTEM, TextureSystem);
	G_OBJECT_CLASS (texture_system_parent_class)->finalize (obj);
}


GType texture_system_get_type (void) {
	static volatile gsize texture_system_type_id__volatile = 0;
	if (g_once_init_enter (&texture_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TextureSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) texture_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TextureSystem), 0, (GInstanceInitFunc) texture_system_instance_init, NULL };
		GType texture_system_type_id;
		texture_system_type_id = g_type_register_static (ENGINE_TYPE_ENTITY_SYSTEM, "TextureSystem", &g_define_type_info, 0);
		g_once_init_leave (&texture_system_type_id__volatile, texture_system_type_id);
	}
	return texture_system_type_id__volatile;
}



