/* animationcomponent.c generated by valac 0.32.0, the Vala compiler
 * generated from animationcomponent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <engine.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define TYPE_ANIMATION_COMPONENT (animation_component_get_type ())
#define ANIMATION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ANIMATION_COMPONENT, AnimationComponent))
#define ANIMATION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ANIMATION_COMPONENT, AnimationComponentClass))
#define IS_ANIMATION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ANIMATION_COMPONENT))
#define IS_ANIMATION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ANIMATION_COMPONENT))
#define ANIMATION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ANIMATION_COMPONENT, AnimationComponentClass))

typedef struct _AnimationComponent AnimationComponent;
typedef struct _AnimationComponentClass AnimationComponentClass;
typedef struct _AnimationComponentPrivate AnimationComponentPrivate;

#define TYPE_ANIMATION (animation_get_type ())
#define ANIMATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ANIMATION, Animation))
#define ANIMATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ANIMATION, AnimationClass))
#define IS_ANIMATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ANIMATION))
#define IS_ANIMATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ANIMATION))
#define ANIMATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ANIMATION, AnimationClass))

typedef struct _Animation Animation;
typedef struct _AnimationClass AnimationClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _AnimationPrivate AnimationPrivate;

struct _AnimationComponent {
	EngineComponent parent_instance;
	AnimationComponentPrivate * priv;
	gchar* current_animation;
	gint sprite_width;
};

struct _AnimationComponentClass {
	EngineComponentClass parent_class;
};

struct _AnimationComponentPrivate {
	GeeMap* animations;
};

struct _Animation {
	GObject parent_instance;
	AnimationPrivate * priv;
};

struct _AnimationClass {
	GObjectClass parent_class;
};

struct _AnimationPrivate {
	gchar* name;
	gint begin;
	gint end;
	gint frames_between;
	gint current_frame;
	gint current_sprite;
	gboolean endless;
	gboolean removeAfterAnimation;
};


static gpointer animation_component_parent_class = NULL;
static gpointer animation_parent_class = NULL;

GType animation_component_get_type (void) G_GNUC_CONST;
GType animation_get_type (void) G_GNUC_CONST;
#define ANIMATION_COMPONENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_ANIMATION_COMPONENT, AnimationComponentPrivate))
enum  {
	ANIMATION_COMPONENT_DUMMY_PROPERTY
};
AnimationComponent* animation_component_new (void);
AnimationComponent* animation_component_construct (GType object_type);
AnimationComponent* animation_component_new_with_width (gint sprite_width);
AnimationComponent* animation_component_construct_with_width (GType object_type, gint sprite_width);
void animation_component_add_animation (AnimationComponent* self, Animation* a);
gchar* animation_get_name (Animation* self);
gboolean animation_component_next_animation (AnimationComponent* self);
gboolean animation_is_endless (Animation* self);
gint animation_play_animation_endless (Animation* self);
gboolean animation_play_animation (Animation* self);
gboolean animation_removeAnimation (Animation* self);
gint animation_component_get_animation_number (AnimationComponent* self);
gint animation_get_current_sprite (Animation* self);
gint animation_component_get_animation_sprite (AnimationComponent* self);
static void animation_component_finalize (GObject* obj);
#define ANIMATION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_ANIMATION, AnimationPrivate))
enum  {
	ANIMATION_DUMMY_PROPERTY
};
Animation* animation_new (const gchar* name, gint begin, gint end, gint frames_between, gboolean endless, gboolean removeAfterAnimation);
Animation* animation_construct (GType object_type, const gchar* name, gint begin, gint end, gint frames_between, gboolean endless, gboolean removeAfterAnimation);
static void animation_finalize (GObject* obj);


AnimationComponent* animation_component_construct (GType object_type) {
	AnimationComponent * self = NULL;
	GeeHashMap* _tmp0_ = NULL;
	self = (AnimationComponent*) engine_component_construct (object_type);
	_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, TYPE_ANIMATION, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->animations);
	self->priv->animations = (GeeMap*) _tmp0_;
	return self;
}


AnimationComponent* animation_component_new (void) {
	return animation_component_construct (TYPE_ANIMATION_COMPONENT);
}


AnimationComponent* animation_component_construct_with_width (GType object_type, gint sprite_width) {
	AnimationComponent * self = NULL;
	gint _tmp0_ = 0;
	self = (AnimationComponent*) animation_component_construct (object_type);
	_tmp0_ = sprite_width;
	self->sprite_width = _tmp0_;
	return self;
}


AnimationComponent* animation_component_new_with_width (gint sprite_width) {
	return animation_component_construct_with_width (TYPE_ANIMATION_COMPONENT, sprite_width);
}


void animation_component_add_animation (AnimationComponent* self, Animation* a) {
	const gchar* _tmp0_ = NULL;
	GeeMap* _tmp3_ = NULL;
	Animation* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	Animation* _tmp7_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (a != NULL);
	_tmp0_ = self->current_animation;
	if (_tmp0_ == NULL) {
		Animation* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		_tmp1_ = a;
		_tmp2_ = animation_get_name (_tmp1_);
		_g_free0 (self->current_animation);
		self->current_animation = _tmp2_;
	}
	_tmp3_ = self->priv->animations;
	_tmp4_ = a;
	_tmp5_ = animation_get_name (_tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = a;
	gee_map_set (_tmp3_, _tmp6_, _tmp7_);
	_g_free0 (_tmp6_);
}


gboolean animation_component_next_animation (AnimationComponent* self) {
	gboolean result = FALSE;
	Animation* a = NULL;
	GeeMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	Animation* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->animations;
	_tmp1_ = self->current_animation;
	_tmp2_ = gee_map_get (_tmp0_, _tmp1_);
	a = (Animation*) _tmp2_;
	_tmp3_ = a;
	_tmp4_ = animation_is_endless (_tmp3_);
	if (_tmp4_) {
		Animation* _tmp5_ = NULL;
		_tmp5_ = a;
		animation_play_animation_endless (_tmp5_);
	} else {
		gboolean done = FALSE;
		Animation* _tmp6_ = NULL;
		gboolean _tmp7_ = FALSE;
		gboolean _tmp8_ = FALSE;
		_tmp6_ = a;
		_tmp7_ = animation_play_animation (_tmp6_);
		done = _tmp7_;
		_tmp8_ = done;
		if (_tmp8_) {
			gchar* _tmp9_ = NULL;
			Animation* _tmp10_ = NULL;
			gboolean _tmp11_ = FALSE;
			_tmp9_ = g_strdup ("still");
			_g_free0 (self->current_animation);
			self->current_animation = _tmp9_;
			_tmp10_ = a;
			_tmp11_ = animation_removeAnimation (_tmp10_);
			if (_tmp11_) {
				result = TRUE;
				_g_object_unref0 (a);
				return result;
			}
		}
	}
	result = FALSE;
	_g_object_unref0 (a);
	return result;
}


gint animation_component_get_animation_number (AnimationComponent* self) {
	gint result = 0;
	GeeMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	Animation* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->animations;
	_tmp1_ = self->current_animation;
	_tmp2_ = gee_map_get (_tmp0_, _tmp1_);
	_tmp3_ = (Animation*) _tmp2_;
	_tmp4_ = animation_get_current_sprite (_tmp3_);
	_tmp5_ = _tmp4_;
	_g_object_unref0 (_tmp3_);
	result = _tmp5_;
	return result;
}


gint animation_component_get_animation_sprite (AnimationComponent* self) {
	gint result = 0;
	gint ret = 0;
	GeeMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	Animation* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->animations;
	_tmp1_ = self->current_animation;
	_tmp2_ = gee_map_get (_tmp0_, _tmp1_);
	_tmp3_ = (Animation*) _tmp2_;
	_tmp4_ = animation_play_animation_endless (_tmp3_);
	_tmp5_ = _tmp4_;
	_g_object_unref0 (_tmp3_);
	ret = _tmp5_;
	result = ret;
	return result;
}


static void animation_component_class_init (AnimationComponentClass * klass) {
	animation_component_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (AnimationComponentPrivate));
	G_OBJECT_CLASS (klass)->finalize = animation_component_finalize;
}


static void animation_component_instance_init (AnimationComponent * self) {
	self->priv = ANIMATION_COMPONENT_GET_PRIVATE (self);
}


static void animation_component_finalize (GObject* obj) {
	AnimationComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_ANIMATION_COMPONENT, AnimationComponent);
	_g_free0 (self->current_animation);
	_g_object_unref0 (self->priv->animations);
	G_OBJECT_CLASS (animation_component_parent_class)->finalize (obj);
}


GType animation_component_get_type (void) {
	static volatile gsize animation_component_type_id__volatile = 0;
	if (g_once_init_enter (&animation_component_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AnimationComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) animation_component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AnimationComponent), 0, (GInstanceInitFunc) animation_component_instance_init, NULL };
		GType animation_component_type_id;
		animation_component_type_id = g_type_register_static (ENGINE_TYPE_COMPONENT, "AnimationComponent", &g_define_type_info, 0);
		g_once_init_leave (&animation_component_type_id__volatile, animation_component_type_id);
	}
	return animation_component_type_id__volatile;
}


Animation* animation_construct (GType object_type, const gchar* name, gint begin, gint end, gint frames_between, gboolean endless, gboolean removeAfterAnimation) {
	Animation * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	gboolean _tmp6_ = FALSE;
	gboolean _tmp7_ = FALSE;
	g_return_val_if_fail (name != NULL, NULL);
	self = (Animation*) g_object_new (object_type, NULL);
	_tmp0_ = name;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->name);
	self->priv->name = _tmp1_;
	_tmp2_ = begin;
	self->priv->begin = _tmp2_;
	_tmp3_ = end;
	self->priv->end = _tmp3_;
	_tmp4_ = frames_between;
	self->priv->frames_between = _tmp4_;
	self->priv->current_frame = 0;
	_tmp5_ = begin;
	self->priv->current_sprite = _tmp5_;
	_tmp6_ = endless;
	self->priv->endless = _tmp6_;
	_tmp7_ = removeAfterAnimation;
	self->priv->removeAfterAnimation = _tmp7_;
	return self;
}


Animation* animation_new (const gchar* name, gint begin, gint end, gint frames_between, gboolean endless, gboolean removeAfterAnimation) {
	return animation_construct (TYPE_ANIMATION, name, begin, end, frames_between, endless, removeAfterAnimation);
}


gboolean animation_play_animation (Animation* self) {
	gboolean result = FALSE;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->current_frame;
	_tmp1_ = self->priv->frames_between;
	if (_tmp0_ >= _tmp1_) {
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
		self->priv->current_frame = 0;
		_tmp2_ = self->priv->current_sprite;
		_tmp3_ = self->priv->end;
		if (_tmp2_ >= _tmp3_) {
			gint _tmp4_ = 0;
			self->priv->current_frame = 0;
			_tmp4_ = self->priv->begin;
			self->priv->current_sprite = _tmp4_;
			result = TRUE;
			return result;
		} else {
			gint _tmp5_ = 0;
			_tmp5_ = self->priv->current_sprite;
			self->priv->current_sprite = _tmp5_ + 1;
		}
	} else {
		gint _tmp6_ = 0;
		_tmp6_ = self->priv->current_frame;
		self->priv->current_frame = _tmp6_ + 1;
	}
	result = FALSE;
	return result;
}


gint animation_play_animation_endless (Animation* self) {
	gint result = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp7_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->current_frame;
	_tmp1_ = self->priv->frames_between;
	if (_tmp0_ >= _tmp1_) {
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
		self->priv->current_frame = 0;
		_tmp2_ = self->priv->current_sprite;
		_tmp3_ = self->priv->end;
		if (_tmp2_ >= _tmp3_) {
			gint _tmp4_ = 0;
			_tmp4_ = self->priv->begin;
			self->priv->current_sprite = _tmp4_;
		} else {
			gint _tmp5_ = 0;
			_tmp5_ = self->priv->current_sprite;
			self->priv->current_sprite = _tmp5_ + 1;
		}
	} else {
		gint _tmp6_ = 0;
		_tmp6_ = self->priv->current_frame;
		self->priv->current_frame = _tmp6_ + 1;
	}
	_tmp7_ = self->priv->current_sprite;
	result = _tmp7_;
	return result;
}


gint animation_get_current_sprite (Animation* self) {
	gint result = 0;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->current_sprite;
	result = _tmp0_;
	return result;
}


gchar* animation_get_name (Animation* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->name;
	_tmp1_ = g_strdup (_tmp0_);
	result = _tmp1_;
	return result;
}


gboolean animation_is_endless (Animation* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->endless;
	result = _tmp0_;
	return result;
}


gboolean animation_removeAnimation (Animation* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->removeAfterAnimation;
	result = _tmp0_;
	return result;
}


static void animation_class_init (AnimationClass * klass) {
	animation_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (AnimationPrivate));
	G_OBJECT_CLASS (klass)->finalize = animation_finalize;
}


static void animation_instance_init (Animation * self) {
	self->priv = ANIMATION_GET_PRIVATE (self);
}


static void animation_finalize (GObject* obj) {
	Animation * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_ANIMATION, Animation);
	_g_free0 (self->priv->name);
	G_OBJECT_CLASS (animation_parent_class)->finalize (obj);
}


GType animation_get_type (void) {
	static volatile gsize animation_type_id__volatile = 0;
	if (g_once_init_enter (&animation_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AnimationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) animation_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Animation), 0, (GInstanceInitFunc) animation_instance_init, NULL };
		GType animation_type_id;
		animation_type_id = g_type_register_static (G_TYPE_OBJECT, "Animation", &g_define_type_info, 0);
		g_once_init_leave (&animation_type_id__volatile, animation_type_id);
	}
	return animation_type_id__volatile;
}



