/* cameracomponent.c generated by valac 0.32.0, the Vala compiler
 * generated from cameracomponent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <engine.h>


#define TYPE_CAMERA_COMPONENT (camera_component_get_type ())
#define CAMERA_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CAMERA_COMPONENT, CameraComponent))
#define CAMERA_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CAMERA_COMPONENT, CameraComponentClass))
#define IS_CAMERA_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CAMERA_COMPONENT))
#define IS_CAMERA_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CAMERA_COMPONENT))
#define CAMERA_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CAMERA_COMPONENT, CameraComponentClass))

typedef struct _CameraComponent CameraComponent;
typedef struct _CameraComponentClass CameraComponentClass;
typedef struct _CameraComponentPrivate CameraComponentPrivate;

struct _CameraComponent {
	EngineComponent parent_instance;
	CameraComponentPrivate * priv;
	guint w;
	guint h;
};

struct _CameraComponentClass {
	EngineComponentClass parent_class;
};


static gpointer camera_component_parent_class = NULL;

GType camera_component_get_type (void) G_GNUC_CONST;
enum  {
	CAMERA_COMPONENT_DUMMY_PROPERTY
};
CameraComponent* camera_component_new (guint w, guint h);
CameraComponent* camera_component_construct (GType object_type, guint w, guint h);
static void camera_component_finalize (GObject* obj);


CameraComponent* camera_component_construct (GType object_type, guint w, guint h) {
	CameraComponent * self = NULL;
	guint _tmp0_ = 0U;
	guint _tmp1_ = 0U;
	self = (CameraComponent*) engine_component_construct (object_type);
	_tmp0_ = w;
	self->w = _tmp0_;
	_tmp1_ = h;
	self->h = _tmp1_;
	return self;
}


CameraComponent* camera_component_new (guint w, guint h) {
	return camera_component_construct (TYPE_CAMERA_COMPONENT, w, h);
}


static void camera_component_class_init (CameraComponentClass * klass) {
	camera_component_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = camera_component_finalize;
}


static void camera_component_instance_init (CameraComponent * self) {
}


static void camera_component_finalize (GObject* obj) {
	CameraComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_CAMERA_COMPONENT, CameraComponent);
	G_OBJECT_CLASS (camera_component_parent_class)->finalize (obj);
}


GType camera_component_get_type (void) {
	static volatile gsize camera_component_type_id__volatile = 0;
	if (g_once_init_enter (&camera_component_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CameraComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) camera_component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CameraComponent), 0, (GInstanceInitFunc) camera_component_instance_init, NULL };
		GType camera_component_type_id;
		camera_component_type_id = g_type_register_static (ENGINE_TYPE_COMPONENT, "CameraComponent", &g_define_type_info, 0);
		g_once_init_leave (&camera_component_type_id__volatile, camera_component_type_id);
	}
	return camera_component_type_id__volatile;
}



