/* collisioncomponent.c generated by valac 0.32.0, the Vala compiler
 * generated from collisioncomponent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <engine.h>
#include <SDL2/SDL_rect.h>
#include <string.h>
#include <SDL2/SDL_render.h>


#define TYPE_COLLISION_COMPONENT (collision_component_get_type ())
#define COLLISION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COLLISION_COMPONENT, CollisionComponent))
#define COLLISION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COLLISION_COMPONENT, CollisionComponentClass))
#define IS_COLLISION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COLLISION_COMPONENT))
#define IS_COLLISION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COLLISION_COMPONENT))
#define COLLISION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COLLISION_COMPONENT, CollisionComponentClass))

typedef struct _CollisionComponent CollisionComponent;
typedef struct _CollisionComponentClass CollisionComponentClass;
typedef struct _CollisionComponentPrivate CollisionComponentPrivate;

#define TYPE_POSITION_COMPONENT (position_component_get_type ())
#define POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_POSITION_COMPONENT, PositionComponent))
#define POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_POSITION_COMPONENT, PositionComponentClass))
#define IS_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_POSITION_COMPONENT))
#define IS_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_POSITION_COMPONENT))
#define POSITION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_POSITION_COMPONENT, PositionComponentClass))

typedef struct _PositionComponent PositionComponent;
typedef struct _PositionComponentClass PositionComponentClass;
typedef struct _PositionComponentPrivate PositionComponentPrivate;

#define POSITION_COMPONENT_TYPE_ENTITY_STATE (position_component_entity_state_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

typedef void (*CollisionComponentcollisionFunc) (void* user_data);
struct _CollisionComponent {
	EngineComponent parent_instance;
	CollisionComponentPrivate * priv;
	CollisionComponentcollisionFunc collision;
	gpointer collision_target;
	GDestroyNotify collision_target_destroy_notify;
};

struct _CollisionComponentClass {
	EngineComponentClass parent_class;
};

struct _CollisionComponentPrivate {
	SDL_Rect _box;
};

typedef enum  {
	POSITION_COMPONENT_ENTITY_STATE_GROUND,
	POSITION_COMPONENT_ENTITY_STATE_AIR
} PositionComponentEntityState;

struct _PositionComponent {
	EngineComponent parent_instance;
	PositionComponentPrivate * priv;
	gint x;
	gint y;
	gint velocity_x;
	gint velocity_y;
	PositionComponentEntityState state;
	SDL_RendererFlip flip;
};

struct _PositionComponentClass {
	EngineComponentClass parent_class;
};


static gpointer collision_component_parent_class = NULL;

GType collision_component_get_type (void) G_GNUC_CONST;
#define COLLISION_COMPONENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_COLLISION_COMPONENT, CollisionComponentPrivate))
enum  {
	COLLISION_COMPONENT_DUMMY_PROPERTY
};
CollisionComponent* collision_component_new (gint x, gint y, guint w, guint h);
CollisionComponent* collision_component_construct (GType object_type, gint x, gint y, guint w, guint h);
void collision_component_set_box (CollisionComponent* self, SDL_Rect* value);
void collision_component_getAbsoluteBox (CollisionComponent* self, SDL_Rect* result);
GType position_component_get_type (void) G_GNUC_CONST;
GType position_component_entity_state_get_type (void) G_GNUC_CONST;
void collision_component_get_box (CollisionComponent* self, SDL_Rect* result);
void collision_component_getHAbsoluteBox (CollisionComponent* self, SDL_Rect* result);
static void collision_component_finalize (GObject* obj);
static void _vala_collision_component_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_collision_component_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


CollisionComponent* collision_component_construct (GType object_type, gint x, gint y, guint w, guint h) {
	CollisionComponent * self = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	guint _tmp2_ = 0U;
	guint _tmp3_ = 0U;
	SDL_Rect _tmp4_ = {0};
	self = (CollisionComponent*) engine_component_construct (object_type);
	_tmp0_ = x;
	_tmp1_ = y;
	_tmp2_ = w;
	_tmp3_ = h;
	memset (&_tmp4_, 0, sizeof (SDL_Rect));
	_tmp4_.x = _tmp0_;
	_tmp4_.y = _tmp1_;
	_tmp4_.w = _tmp2_;
	_tmp4_.h = _tmp3_;
	collision_component_set_box (self, &_tmp4_);
	return self;
}


CollisionComponent* collision_component_new (gint x, gint y, guint w, guint h) {
	return collision_component_construct (TYPE_COLLISION_COMPONENT, x, y, w, h);
}


void collision_component_getAbsoluteBox (CollisionComponent* self, SDL_Rect* result) {
	PositionComponent* pos = NULL;
	EngineEntity* _tmp0_ = NULL;
	EngineEntity* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	SDL_Rect _tmp5_ = {0};
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	SDL_Rect _tmp9_ = {0};
	gint _tmp10_ = 0;
	SDL_Rect _tmp11_ = {0};
	guint _tmp12_ = 0U;
	SDL_Rect _tmp13_ = {0};
	guint _tmp14_ = 0U;
	SDL_Rect _tmp15_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = engine_component_get_entity ((EngineComponent*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = engine_entity_get_component (_tmp1_, TYPE_POSITION_COMPONENT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
	pos = (PositionComponent*) _tmp2_;
	_tmp3_ = pos->x;
	_tmp4_ = pos->velocity_x;
	_tmp5_ = self->priv->_box;
	_tmp6_ = _tmp5_.x;
	_tmp7_ = pos->y;
	_tmp8_ = pos->velocity_y;
	_tmp9_ = self->priv->_box;
	_tmp10_ = _tmp9_.y;
	_tmp11_ = self->priv->_box;
	_tmp12_ = _tmp11_.w;
	_tmp13_ = self->priv->_box;
	_tmp14_ = _tmp13_.h;
	memset (&_tmp15_, 0, sizeof (SDL_Rect));
	_tmp15_.x = (_tmp3_ + _tmp4_) + _tmp6_;
	_tmp15_.y = (_tmp7_ + _tmp8_) + _tmp10_;
	_tmp15_.w = _tmp12_;
	_tmp15_.h = _tmp14_;
	*result = _tmp15_;
	_g_object_unref0 (pos);
	return;
}


void collision_component_getHAbsoluteBox (CollisionComponent* self, SDL_Rect* result) {
	PositionComponent* pos = NULL;
	EngineEntity* _tmp0_ = NULL;
	EngineEntity* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	SDL_Rect _tmp5_ = {0};
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	SDL_Rect _tmp8_ = {0};
	gint _tmp9_ = 0;
	SDL_Rect _tmp10_ = {0};
	guint _tmp11_ = 0U;
	SDL_Rect _tmp12_ = {0};
	guint _tmp13_ = 0U;
	SDL_Rect _tmp14_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = engine_component_get_entity ((EngineComponent*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = engine_entity_get_component (_tmp1_, TYPE_POSITION_COMPONENT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
	pos = (PositionComponent*) _tmp2_;
	_tmp3_ = pos->x;
	_tmp4_ = pos->velocity_x;
	_tmp5_ = self->priv->_box;
	_tmp6_ = _tmp5_.x;
	_tmp7_ = pos->y;
	_tmp8_ = self->priv->_box;
	_tmp9_ = _tmp8_.y;
	_tmp10_ = self->priv->_box;
	_tmp11_ = _tmp10_.w;
	_tmp12_ = self->priv->_box;
	_tmp13_ = _tmp12_.h;
	memset (&_tmp14_, 0, sizeof (SDL_Rect));
	_tmp14_.x = (_tmp3_ + _tmp4_) + _tmp6_;
	_tmp14_.y = _tmp7_ + _tmp9_;
	_tmp14_.w = _tmp11_;
	_tmp14_.h = _tmp13_;
	*result = _tmp14_;
	_g_object_unref0 (pos);
	return;
}


void collision_component_get_box (CollisionComponent* self, SDL_Rect* result) {
	SDL_Rect _tmp0_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_box;
	*result = _tmp0_;
	return;
}


void collision_component_set_box (CollisionComponent* self, SDL_Rect* value) {
	SDL_Rect _tmp0_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = *value;
	self->priv->_box = _tmp0_;
}


static void collision_component_class_init (CollisionComponentClass * klass) {
	collision_component_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CollisionComponentPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_collision_component_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_collision_component_set_property;
	G_OBJECT_CLASS (klass)->finalize = collision_component_finalize;
}


static void collision_component_instance_init (CollisionComponent * self) {
	self->priv = COLLISION_COMPONENT_GET_PRIVATE (self);
}


static void collision_component_finalize (GObject* obj) {
	CollisionComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_COLLISION_COMPONENT, CollisionComponent);
	(self->collision_target_destroy_notify == NULL) ? NULL : (self->collision_target_destroy_notify (self->collision_target), NULL);
	self->collision = NULL;
	self->collision_target = NULL;
	self->collision_target_destroy_notify = NULL;
	G_OBJECT_CLASS (collision_component_parent_class)->finalize (obj);
}


GType collision_component_get_type (void) {
	static volatile gsize collision_component_type_id__volatile = 0;
	if (g_once_init_enter (&collision_component_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CollisionComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) collision_component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CollisionComponent), 0, (GInstanceInitFunc) collision_component_instance_init, NULL };
		GType collision_component_type_id;
		collision_component_type_id = g_type_register_static (ENGINE_TYPE_COMPONENT, "CollisionComponent", &g_define_type_info, 0);
		g_once_init_leave (&collision_component_type_id__volatile, collision_component_type_id);
	}
	return collision_component_type_id__volatile;
}


static void _vala_collision_component_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CollisionComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_COLLISION_COMPONENT, CollisionComponent);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_collision_component_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	CollisionComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_COLLISION_COMPONENT, CollisionComponent);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



