/* gravitycomponent.c generated by valac 0.32.0, the Vala compiler
 * generated from gravitycomponent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <engine.h>
#include <SDL2/SDL_render.h>


#define TYPE_GRAVITY_COMPONENT (gravity_component_get_type ())
#define GRAVITY_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GRAVITY_COMPONENT, GravityComponent))
#define GRAVITY_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GRAVITY_COMPONENT, GravityComponentClass))
#define IS_GRAVITY_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GRAVITY_COMPONENT))
#define IS_GRAVITY_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GRAVITY_COMPONENT))
#define GRAVITY_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GRAVITY_COMPONENT, GravityComponentClass))

typedef struct _GravityComponent GravityComponent;
typedef struct _GravityComponentClass GravityComponentClass;
typedef struct _GravityComponentPrivate GravityComponentPrivate;

#define TYPE_POSITION_COMPONENT (position_component_get_type ())
#define POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_POSITION_COMPONENT, PositionComponent))
#define POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_POSITION_COMPONENT, PositionComponentClass))
#define IS_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_POSITION_COMPONENT))
#define IS_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_POSITION_COMPONENT))
#define POSITION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_POSITION_COMPONENT, PositionComponentClass))

typedef struct _PositionComponent PositionComponent;
typedef struct _PositionComponentClass PositionComponentClass;
typedef struct _PositionComponentPrivate PositionComponentPrivate;

#define POSITION_COMPONENT_TYPE_ENTITY_STATE (position_component_entity_state_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GravityComponent {
	EngineUpdateComponent parent_instance;
	GravityComponentPrivate * priv;
};

struct _GravityComponentClass {
	EngineUpdateComponentClass parent_class;
};

typedef enum  {
	POSITION_COMPONENT_ENTITY_STATE_GROUND,
	POSITION_COMPONENT_ENTITY_STATE_AIR
} PositionComponentEntityState;

struct _PositionComponent {
	EngineComponent parent_instance;
	PositionComponentPrivate * priv;
	gint x;
	gint y;
	gint velocity_x;
	gint velocity_y;
	gint next_x;
	gint next_y;
	PositionComponentEntityState state;
	SDL_RendererFlip flip;
};

struct _PositionComponentClass {
	EngineComponentClass parent_class;
};


static gpointer gravity_component_parent_class = NULL;

GType gravity_component_get_type (void) G_GNUC_CONST;
enum  {
	GRAVITY_COMPONENT_DUMMY_PROPERTY
};
static void gravity_component_real_update (EngineUpdateComponent* base);
GType position_component_get_type (void) G_GNUC_CONST;
GType position_component_entity_state_get_type (void) G_GNUC_CONST;
GravityComponent* gravity_component_new (void);
GravityComponent* gravity_component_construct (GType object_type);


static void gravity_component_real_update (EngineUpdateComponent* base) {
	GravityComponent * self;
	PositionComponent* pos = NULL;
	EngineEntity* _tmp0_ = NULL;
	EngineEntity* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	PositionComponent* _tmp3_ = NULL;
#line 3 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	self = (GravityComponent*) base;
#line 4 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	_tmp0_ = engine_component_get_entity ((EngineComponent*) self);
#line 4 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	_tmp1_ = _tmp0_;
#line 4 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	_tmp2_ = engine_entity_get_component (_tmp1_, TYPE_POSITION_COMPONENT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
#line 4 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	pos = (PositionComponent*) _tmp2_;
#line 5 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	_tmp3_ = pos;
#line 5 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	if (_tmp3_ != NULL) {
#line 103 "gravitycomponent.c"
		PositionComponent* _tmp4_ = NULL;
		PositionComponent* _tmp5_ = NULL;
		gint _tmp6_ = 0;
#line 6 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
		_tmp4_ = pos;
#line 6 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
		_tmp5_ = pos;
#line 6 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
		_tmp6_ = _tmp5_->next_y;
#line 6 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
		_tmp5_->next_y = _tmp6_ + 1;
#line 115 "gravitycomponent.c"
	}
#line 3 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	_g_object_unref0 (pos);
#line 119 "gravitycomponent.c"
}


GravityComponent* gravity_component_construct (GType object_type) {
	GravityComponent * self = NULL;
#line 1 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	self = (GravityComponent*) engine_update_component_construct (object_type);
#line 1 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	return self;
#line 129 "gravitycomponent.c"
}


GravityComponent* gravity_component_new (void) {
#line 1 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	return gravity_component_construct (TYPE_GRAVITY_COMPONENT);
#line 136 "gravitycomponent.c"
}


static void gravity_component_class_init (GravityComponentClass * klass) {
#line 1 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	gravity_component_parent_class = g_type_class_peek_parent (klass);
#line 1 "/home/gunibert/Projects/yviland2/src/components/gravitycomponent.vala"
	((EngineUpdateComponentClass *) klass)->update = gravity_component_real_update;
#line 145 "gravitycomponent.c"
}


static void gravity_component_instance_init (GravityComponent * self) {
}


GType gravity_component_get_type (void) {
	static volatile gsize gravity_component_type_id__volatile = 0;
	if (g_once_init_enter (&gravity_component_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GravityComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gravity_component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GravityComponent), 0, (GInstanceInitFunc) gravity_component_instance_init, NULL };
		GType gravity_component_type_id;
		gravity_component_type_id = g_type_register_static (ENGINE_TYPE_UPDATE_COMPONENT, "GravityComponent", &g_define_type_info, 0);
		g_once_init_leave (&gravity_component_type_id__volatile, gravity_component_type_id);
	}
	return gravity_component_type_id__volatile;
}



