/* movementcomponent.c generated by valac 0.32.0, the Vala compiler
 * generated from movementcomponent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <engine.h>


#define TYPE_MOVEMENT_COMPONENT (movement_component_get_type ())
#define MOVEMENT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MOVEMENT_COMPONENT, MovementComponent))
#define MOVEMENT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MOVEMENT_COMPONENT, MovementComponentClass))
#define IS_MOVEMENT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MOVEMENT_COMPONENT))
#define IS_MOVEMENT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MOVEMENT_COMPONENT))
#define MOVEMENT_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MOVEMENT_COMPONENT, MovementComponentClass))

typedef struct _MovementComponent MovementComponent;
typedef struct _MovementComponentClass MovementComponentClass;
typedef struct _MovementComponentPrivate MovementComponentPrivate;

struct _MovementComponent {
	EngineComponent parent_instance;
	MovementComponentPrivate * priv;
};

struct _MovementComponentClass {
	EngineComponentClass parent_class;
};


static gpointer movement_component_parent_class = NULL;

GType movement_component_get_type (void) G_GNUC_CONST;
enum  {
	MOVEMENT_COMPONENT_DUMMY_PROPERTY
};
MovementComponent* movement_component_new (void);
MovementComponent* movement_component_construct (GType object_type);


MovementComponent* movement_component_construct (GType object_type) {
	MovementComponent * self = NULL;
	self = (MovementComponent*) engine_component_construct (object_type);
	return self;
}


MovementComponent* movement_component_new (void) {
	return movement_component_construct (TYPE_MOVEMENT_COMPONENT);
}


static void movement_component_class_init (MovementComponentClass * klass) {
	movement_component_parent_class = g_type_class_peek_parent (klass);
}


static void movement_component_instance_init (MovementComponent * self) {
}


GType movement_component_get_type (void) {
	static volatile gsize movement_component_type_id__volatile = 0;
	if (g_once_init_enter (&movement_component_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MovementComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) movement_component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MovementComponent), 0, (GInstanceInitFunc) movement_component_instance_init, NULL };
		GType movement_component_type_id;
		movement_component_type_id = g_type_register_static (ENGINE_TYPE_COMPONENT, "MovementComponent", &g_define_type_info, 0);
		g_once_init_leave (&movement_component_type_id__volatile, movement_component_type_id);
	}
	return movement_component_type_id__volatile;
}



