/* positioncomponent.c generated by valac 0.32.0, the Vala compiler
 * generated from positioncomponent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <engine.h>
#include <SDL2/SDL_render.h>


#define TYPE_POSITION_COMPONENT (position_component_get_type ())
#define POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_POSITION_COMPONENT, PositionComponent))
#define POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_POSITION_COMPONENT, PositionComponentClass))
#define IS_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_POSITION_COMPONENT))
#define IS_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_POSITION_COMPONENT))
#define POSITION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_POSITION_COMPONENT, PositionComponentClass))

typedef struct _PositionComponent PositionComponent;
typedef struct _PositionComponentClass PositionComponentClass;
typedef struct _PositionComponentPrivate PositionComponentPrivate;

#define POSITION_COMPONENT_TYPE_ENTITY_STATE (position_component_entity_state_get_type ())

typedef enum  {
	POSITION_COMPONENT_ENTITY_STATE_GROUND,
	POSITION_COMPONENT_ENTITY_STATE_AIR
} PositionComponentEntityState;

struct _PositionComponent {
	EngineComponent parent_instance;
	PositionComponentPrivate * priv;
	gint x;
	gint y;
	gint velocity_x;
	gint velocity_y;
	PositionComponentEntityState state;
	SDL_RendererFlip flip;
};

struct _PositionComponentClass {
	EngineComponentClass parent_class;
};


static gpointer position_component_parent_class = NULL;

GType position_component_get_type (void) G_GNUC_CONST;
GType position_component_entity_state_get_type (void) G_GNUC_CONST;
enum  {
	POSITION_COMPONENT_DUMMY_PROPERTY
};
PositionComponent* position_component_new (gint x, gint y);
PositionComponent* position_component_construct (GType object_type, gint x, gint y);
void position_component_update_position (PositionComponent* self);
static void position_component_finalize (GObject* obj);


GType position_component_entity_state_get_type (void) {
	static volatile gsize position_component_entity_state_type_id__volatile = 0;
	if (g_once_init_enter (&position_component_entity_state_type_id__volatile)) {
		static const GEnumValue values[] = {{POSITION_COMPONENT_ENTITY_STATE_GROUND, "POSITION_COMPONENT_ENTITY_STATE_GROUND", "ground"}, {POSITION_COMPONENT_ENTITY_STATE_AIR, "POSITION_COMPONENT_ENTITY_STATE_AIR", "air"}, {0, NULL, NULL}};
		GType position_component_entity_state_type_id;
		position_component_entity_state_type_id = g_enum_register_static ("PositionComponentEntityState", values);
		g_once_init_leave (&position_component_entity_state_type_id__volatile, position_component_entity_state_type_id);
	}
	return position_component_entity_state_type_id__volatile;
}


PositionComponent* position_component_construct (GType object_type, gint x, gint y) {
	PositionComponent * self = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	self = (PositionComponent*) engine_component_construct (object_type);
	_tmp0_ = x;
	self->x = _tmp0_;
	_tmp1_ = y;
	self->y = _tmp1_;
	return self;
}


PositionComponent* position_component_new (gint x, gint y) {
	return position_component_construct (TYPE_POSITION_COMPONENT, x, y);
}


void position_component_update_position (PositionComponent* self) {
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->x;
	_tmp1_ = self->velocity_x;
	self->x = _tmp0_ + _tmp1_;
	_tmp2_ = self->y;
	_tmp3_ = self->velocity_y;
	self->y = _tmp2_ + _tmp3_;
}


static void position_component_class_init (PositionComponentClass * klass) {
	position_component_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = position_component_finalize;
}


static void position_component_instance_init (PositionComponent * self) {
	self->velocity_x = 0;
	self->velocity_y = 0;
	self->state = POSITION_COMPONENT_ENTITY_STATE_AIR;
	self->flip = SDL_FLIP_NONE;
}


static void position_component_finalize (GObject* obj) {
	PositionComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_POSITION_COMPONENT, PositionComponent);
	G_OBJECT_CLASS (position_component_parent_class)->finalize (obj);
}


GType position_component_get_type (void) {
	static volatile gsize position_component_type_id__volatile = 0;
	if (g_once_init_enter (&position_component_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PositionComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) position_component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PositionComponent), 0, (GInstanceInitFunc) position_component_instance_init, NULL };
		GType position_component_type_id;
		position_component_type_id = g_type_register_static (ENGINE_TYPE_COMPONENT, "PositionComponent", &g_define_type_info, 0);
		g_once_init_leave (&position_component_type_id__volatile, position_component_type_id);
	}
	return position_component_type_id__volatile;
}



