/* rendercomponent.c generated by valac 0.32.0, the Vala compiler
 * generated from rendercomponent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <engine.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_render.h>


#define TYPE_RENDER_COMPONENT (render_component_get_type ())
#define RENDER_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RENDER_COMPONENT, RenderComponent))
#define RENDER_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RENDER_COMPONENT, RenderComponentClass))
#define IS_RENDER_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RENDER_COMPONENT))
#define IS_RENDER_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RENDER_COMPONENT))
#define RENDER_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RENDER_COMPONENT, RenderComponentClass))

typedef struct _RenderComponent RenderComponent;
typedef struct _RenderComponentClass RenderComponentClass;
typedef struct _RenderComponentPrivate RenderComponentPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_TEXTURE_MANAGER (texture_manager_get_type ())
#define TEXTURE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXTURE_MANAGER, TextureManager))
#define TEXTURE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXTURE_MANAGER, TextureManagerClass))
#define IS_TEXTURE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXTURE_MANAGER))
#define IS_TEXTURE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXTURE_MANAGER))
#define TEXTURE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXTURE_MANAGER, TextureManagerClass))

typedef struct _TextureManager TextureManager;
typedef struct _TextureManagerClass TextureManagerClass;

#define TYPE_TEXTURE (texture_get_type ())
#define TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXTURE, Texture))
#define TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXTURE, TextureClass))
#define IS_TEXTURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXTURE))
#define IS_TEXTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXTURE))
#define TEXTURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXTURE, TextureClass))

typedef struct _Texture Texture;
typedef struct _TextureClass TextureClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _RenderComponent {
	EngineComponent parent_instance;
	RenderComponentPrivate * priv;
	gchar* identifier;
	gchar* sprite_filename;
	guint w;
	guint h;
};

struct _RenderComponentClass {
	EngineComponentClass parent_class;
};


static gpointer render_component_parent_class = NULL;

GType render_component_get_type (void) G_GNUC_CONST;
enum  {
	RENDER_COMPONENT_DUMMY_PROPERTY
};
RenderComponent* render_component_new (const gchar* identifier, const gchar* sprite_filename, guint w, guint h);
RenderComponent* render_component_construct (GType object_type, const gchar* identifier, const gchar* sprite_filename, guint w, guint h);
GType texture_manager_get_type (void) G_GNUC_CONST;
RenderComponent* render_component_new_withTexture (const gchar* identifier, const gchar* sprite_filename, TextureManager* t, SDL_Renderer* renderer);
RenderComponent* render_component_construct_withTexture (GType object_type, const gchar* identifier, const gchar* sprite_filename, TextureManager* t, SDL_Renderer* renderer);
GType texture_get_type (void) G_GNUC_CONST;
Texture* texture_manager_load (TextureManager* self, const gchar* identifier, const gchar* filename, SDL_Renderer* renderer);
SDL_Texture* texture_get_texture (Texture* self);
RenderComponent* render_component_new_withTexture2 (const gchar* identifier, const gchar* sprite_filename);
RenderComponent* render_component_construct_withTexture2 (GType object_type, const gchar* identifier, const gchar* sprite_filename);
static void render_component_finalize (GObject* obj);


RenderComponent* render_component_construct (GType object_type, const gchar* identifier, const gchar* sprite_filename, guint w, guint h) {
	RenderComponent * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	guint _tmp4_ = 0U;
	guint _tmp5_ = 0U;
	g_return_val_if_fail (identifier != NULL, NULL);
	g_return_val_if_fail (sprite_filename != NULL, NULL);
	self = (RenderComponent*) engine_component_construct (object_type);
	_tmp0_ = identifier;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->identifier);
	self->identifier = _tmp1_;
	_tmp2_ = sprite_filename;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (self->sprite_filename);
	self->sprite_filename = _tmp3_;
	_tmp4_ = w;
	self->w = _tmp4_;
	_tmp5_ = h;
	self->h = _tmp5_;
	return self;
}


RenderComponent* render_component_new (const gchar* identifier, const gchar* sprite_filename, guint w, guint h) {
	return render_component_construct (TYPE_RENDER_COMPONENT, identifier, sprite_filename, w, h);
}


RenderComponent* render_component_construct_withTexture (GType object_type, const gchar* identifier, const gchar* sprite_filename, TextureManager* t, SDL_Renderer* renderer) {
	RenderComponent * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	Texture* texture = NULL;
	TextureManager* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	SDL_Renderer* _tmp5_ = NULL;
	Texture* _tmp6_ = NULL;
	SDL_Texture* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	g_return_val_if_fail (identifier != NULL, NULL);
	g_return_val_if_fail (sprite_filename != NULL, NULL);
	g_return_val_if_fail (t != NULL, NULL);
	g_return_val_if_fail (renderer != NULL, NULL);
	self = (RenderComponent*) engine_component_construct (object_type);
	_tmp0_ = identifier;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->identifier);
	self->identifier = _tmp1_;
	_tmp2_ = t;
	_tmp3_ = identifier;
	_tmp4_ = sprite_filename;
	_tmp5_ = renderer;
	_tmp6_ = texture_manager_load (_tmp2_, _tmp3_, _tmp4_, _tmp5_);
	texture = _tmp6_;
	_tmp7_ = texture_get_texture (texture);
	SDL_QueryTexture (_tmp7_, NULL, NULL, &_tmp8_, &_tmp9_);
	self->w = (guint) _tmp8_;
	self->h = (guint) _tmp9_;
	_g_object_unref0 (texture);
	return self;
}


RenderComponent* render_component_new_withTexture (const gchar* identifier, const gchar* sprite_filename, TextureManager* t, SDL_Renderer* renderer) {
	return render_component_construct_withTexture (TYPE_RENDER_COMPONENT, identifier, sprite_filename, t, renderer);
}


RenderComponent* render_component_construct_withTexture2 (GType object_type, const gchar* identifier, const gchar* sprite_filename) {
	RenderComponent * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (identifier != NULL, NULL);
	g_return_val_if_fail (sprite_filename != NULL, NULL);
	self = (RenderComponent*) engine_component_construct (object_type);
	_tmp0_ = identifier;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->identifier);
	self->identifier = _tmp1_;
	_tmp2_ = sprite_filename;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (self->sprite_filename);
	self->sprite_filename = _tmp3_;
	return self;
}


RenderComponent* render_component_new_withTexture2 (const gchar* identifier, const gchar* sprite_filename) {
	return render_component_construct_withTexture2 (TYPE_RENDER_COMPONENT, identifier, sprite_filename);
}


static void render_component_class_init (RenderComponentClass * klass) {
	render_component_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = render_component_finalize;
}


static void render_component_instance_init (RenderComponent * self) {
}


static void render_component_finalize (GObject* obj) {
	RenderComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_RENDER_COMPONENT, RenderComponent);
	_g_free0 (self->identifier);
	_g_free0 (self->sprite_filename);
	G_OBJECT_CLASS (render_component_parent_class)->finalize (obj);
}


GType render_component_get_type (void) {
	static volatile gsize render_component_type_id__volatile = 0;
	if (g_once_init_enter (&render_component_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RenderComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) render_component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RenderComponent), 0, (GInstanceInitFunc) render_component_instance_init, NULL };
		GType render_component_type_id;
		render_component_type_id = g_type_register_static (ENGINE_TYPE_COMPONENT, "RenderComponent", &g_define_type_info, 0);
		g_once_init_leave (&render_component_type_id__volatile, render_component_type_id);
	}
	return render_component_type_id__volatile;
}



