/* textcomponent.c generated by valac 0.32.0, the Vala compiler
 * generated from textcomponent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <engine.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_pixels.h>


#define TYPE_TEXT_COMPONENT (text_component_get_type ())
#define TEXT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXT_COMPONENT, TextComponent))
#define TEXT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXT_COMPONENT, TextComponentClass))
#define IS_TEXT_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXT_COMPONENT))
#define IS_TEXT_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXT_COMPONENT))
#define TEXT_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXT_COMPONENT, TextComponentClass))

typedef struct _TextComponent TextComponent;
typedef struct _TextComponentClass TextComponentClass;
typedef struct _TextComponentPrivate TextComponentPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _TextComponent {
	EngineComponent parent_instance;
	TextComponentPrivate * priv;
	gchar* font;
	gchar* text;
	gboolean visible;
	gint timer;
	SDL_Color color;
};

struct _TextComponentClass {
	EngineComponentClass parent_class;
};


static gpointer text_component_parent_class = NULL;

GType text_component_get_type (void) G_GNUC_CONST;
enum  {
	TEXT_COMPONENT_DUMMY_PROPERTY
};
TextComponent* text_component_new (const gchar* font, const gchar* text, SDL_Color color);
TextComponent* text_component_construct (GType object_type, const gchar* font, const gchar* text, SDL_Color color);
static void text_component_finalize (GObject* obj);


TextComponent* text_component_construct (GType object_type, const gchar* font, const gchar* text, SDL_Color color) {
	TextComponent * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	SDL_Color _tmp4_ = {0};
	g_return_val_if_fail (font != NULL, NULL);
	g_return_val_if_fail (text != NULL, NULL);
	self = (TextComponent*) engine_component_construct (object_type);
	_tmp0_ = font;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->font);
	self->font = _tmp1_;
	_tmp2_ = text;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (self->text);
	self->text = _tmp3_;
	_tmp4_ = color;
	self->color = _tmp4_;
	return self;
}


TextComponent* text_component_new (const gchar* font, const gchar* text, SDL_Color color) {
	return text_component_construct (TYPE_TEXT_COMPONENT, font, text, color);
}


static void text_component_class_init (TextComponentClass * klass) {
	text_component_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = text_component_finalize;
}


static void text_component_instance_init (TextComponent * self) {
	self->visible = FALSE;
	self->timer = 0;
}


static void text_component_finalize (GObject* obj) {
	TextComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TEXT_COMPONENT, TextComponent);
	_g_free0 (self->font);
	_g_free0 (self->text);
	G_OBJECT_CLASS (text_component_parent_class)->finalize (obj);
}


GType text_component_get_type (void) {
	static volatile gsize text_component_type_id__volatile = 0;
	if (g_once_init_enter (&text_component_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TextComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) text_component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TextComponent), 0, (GInstanceInitFunc) text_component_instance_init, NULL };
		GType text_component_type_id;
		text_component_type_id = g_type_register_static (ENGINE_TYPE_COMPONENT, "TextComponent", &g_define_type_info, 0);
		g_once_init_leave (&text_component_type_id__volatile, text_component_type_id);
	}
	return text_component_type_id__volatile;
}



