/* tilemapcomponent2.c generated by valac 0.32.0, the Vala compiler
 * generated from tilemapcomponent2.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <engine.h>
#include <tiled.h>


#define TYPE_TILEMAP_COMPONENT2 (tilemap_component2_get_type ())
#define TILEMAP_COMPONENT2(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TILEMAP_COMPONENT2, TilemapComponent2))
#define TILEMAP_COMPONENT2_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TILEMAP_COMPONENT2, TilemapComponent2Class))
#define IS_TILEMAP_COMPONENT2(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TILEMAP_COMPONENT2))
#define IS_TILEMAP_COMPONENT2_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TILEMAP_COMPONENT2))
#define TILEMAP_COMPONENT2_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TILEMAP_COMPONENT2, TilemapComponent2Class))

typedef struct _TilemapComponent2 TilemapComponent2;
typedef struct _TilemapComponent2Class TilemapComponent2Class;
typedef struct _TilemapComponent2Private TilemapComponent2Private;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _TilemapComponent2 {
	EngineComponent parent_instance;
	TilemapComponent2Private * priv;
	TiledMap* map;
};

struct _TilemapComponent2Class {
	EngineComponentClass parent_class;
};


static gpointer tilemap_component2_parent_class = NULL;

GType tilemap_component2_get_type (void) G_GNUC_CONST;
enum  {
	TILEMAP_COMPONENT2_DUMMY_PROPERTY
};
TilemapComponent2* tilemap_component2_new (TiledMap* map);
TilemapComponent2* tilemap_component2_construct (GType object_type, TiledMap* map);
static void tilemap_component2_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


TilemapComponent2* tilemap_component2_construct (GType object_type, TiledMap* map) {
	TilemapComponent2 * self = NULL;
	TiledMap* _tmp0_ = NULL;
	TiledMap* _tmp1_ = NULL;
	g_return_val_if_fail (map != NULL, NULL);
	self = (TilemapComponent2*) engine_component_construct (object_type);
	_tmp0_ = map;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->map);
	self->map = _tmp1_;
	return self;
}


TilemapComponent2* tilemap_component2_new (TiledMap* map) {
	return tilemap_component2_construct (TYPE_TILEMAP_COMPONENT2, map);
}


static void tilemap_component2_class_init (TilemapComponent2Class * klass) {
	tilemap_component2_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = tilemap_component2_finalize;
}


static void tilemap_component2_instance_init (TilemapComponent2 * self) {
}


static void tilemap_component2_finalize (GObject* obj) {
	TilemapComponent2 * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TILEMAP_COMPONENT2, TilemapComponent2);
	_g_object_unref0 (self->map);
	G_OBJECT_CLASS (tilemap_component2_parent_class)->finalize (obj);
}


GType tilemap_component2_get_type (void) {
	static volatile gsize tilemap_component2_type_id__volatile = 0;
	if (g_once_init_enter (&tilemap_component2_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TilemapComponent2Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tilemap_component2_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TilemapComponent2), 0, (GInstanceInitFunc) tilemap_component2_instance_init, NULL };
		GType tilemap_component2_type_id;
		tilemap_component2_type_id = g_type_register_static (ENGINE_TYPE_COMPONENT, "TilemapComponent2", &g_define_type_info, 0);
		g_once_init_leave (&tilemap_component2_type_id__volatile, tilemap_component2_type_id);
	}
	return tilemap_component2_type_id__volatile;
}



