/* camera.c generated by valac 0.32.0, the Vala compiler
 * generated from camera.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>


#define TYPE_CAMERA (camera_get_type ())
#define CAMERA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CAMERA, Camera))
#define CAMERA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CAMERA, CameraClass))
#define IS_CAMERA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CAMERA))
#define IS_CAMERA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CAMERA))
#define CAMERA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CAMERA, CameraClass))

typedef struct _Camera Camera;
typedef struct _CameraClass CameraClass;
typedef struct _CameraPrivate CameraPrivate;
typedef struct _ParamSpecCamera ParamSpecCamera;

struct _Camera {
	GTypeInstance parent_instance;
	volatile int ref_count;
	CameraPrivate * priv;
};

struct _CameraClass {
	GTypeClass parent_class;
	void (*finalize) (Camera *self);
};

struct _CameraPrivate {
	gint _x;
	gint _y;
	guint _w;
	guint _h;
};

struct _ParamSpecCamera {
	GParamSpec parent_instance;
};


static gpointer camera_parent_class = NULL;

gpointer camera_ref (gpointer instance);
void camera_unref (gpointer instance);
GParamSpec* param_spec_camera (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_camera (GValue* value, gpointer v_object);
void value_take_camera (GValue* value, gpointer v_object);
gpointer value_get_camera (const GValue* value);
GType camera_get_type (void) G_GNUC_CONST;
#define CAMERA_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_CAMERA, CameraPrivate))
enum  {
	CAMERA_DUMMY_PROPERTY
};
Camera* camera_new (gint x, gint y, guint w, guint h);
Camera* camera_construct (GType object_type, gint x, gint y, guint w, guint h);
void camera_set_x (Camera* self, gint value);
void camera_set_y (Camera* self, gint value);
void camera_set_w (Camera* self, guint value);
void camera_set_h (Camera* self, guint value);
gint camera_get_x (Camera* self);
gint camera_get_y (Camera* self);
guint camera_get_w (Camera* self);
guint camera_get_h (Camera* self);
static void camera_finalize (Camera* obj);


Camera* camera_construct (GType object_type, gint x, gint y, guint w, guint h) {
	Camera* self = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	guint _tmp2_ = 0U;
	guint _tmp3_ = 0U;
	self = (Camera*) g_type_create_instance (object_type);
	_tmp0_ = x;
	camera_set_x (self, _tmp0_);
	_tmp1_ = y;
	camera_set_y (self, _tmp1_);
	_tmp2_ = w;
	camera_set_w (self, _tmp2_);
	_tmp3_ = h;
	camera_set_h (self, _tmp3_);
	return self;
}


Camera* camera_new (gint x, gint y, guint w, guint h) {
	return camera_construct (TYPE_CAMERA, x, y, w, h);
}


gint camera_get_x (Camera* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_x;
	result = _tmp0_;
	return result;
}


void camera_set_x (Camera* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_x = _tmp0_;
}


gint camera_get_y (Camera* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_y;
	result = _tmp0_;
	return result;
}


void camera_set_y (Camera* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_y = _tmp0_;
}


guint camera_get_w (Camera* self) {
	guint result;
	guint _tmp0_ = 0U;
	g_return_val_if_fail (self != NULL, 0U);
	_tmp0_ = self->priv->_w;
	result = _tmp0_;
	return result;
}


void camera_set_w (Camera* self, guint value) {
	guint _tmp0_ = 0U;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_w = _tmp0_;
}


guint camera_get_h (Camera* self) {
	guint result;
	guint _tmp0_ = 0U;
	g_return_val_if_fail (self != NULL, 0U);
	_tmp0_ = self->priv->_h;
	result = _tmp0_;
	return result;
}


void camera_set_h (Camera* self, guint value) {
	guint _tmp0_ = 0U;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_h = _tmp0_;
}


static void value_camera_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_camera_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		camera_unref (value->data[0].v_pointer);
	}
}


static void value_camera_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = camera_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_camera_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_camera_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		Camera* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = camera_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_camera_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	Camera** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = camera_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_camera (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecCamera* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_CAMERA), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_camera (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_CAMERA), NULL);
	return value->data[0].v_pointer;
}


void value_set_camera (GValue* value, gpointer v_object) {
	Camera* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_CAMERA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_CAMERA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		camera_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		camera_unref (old);
	}
}


void value_take_camera (GValue* value, gpointer v_object) {
	Camera* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_CAMERA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_CAMERA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		camera_unref (old);
	}
}


static void camera_class_init (CameraClass * klass) {
	camera_parent_class = g_type_class_peek_parent (klass);
	((CameraClass *) klass)->finalize = camera_finalize;
	g_type_class_add_private (klass, sizeof (CameraPrivate));
}


static void camera_instance_init (Camera * self) {
	self->priv = CAMERA_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void camera_finalize (Camera* obj) {
	Camera * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_CAMERA, Camera);
	g_signal_handlers_destroy (self);
}


GType camera_get_type (void) {
	static volatile gsize camera_type_id__volatile = 0;
	if (g_once_init_enter (&camera_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_camera_init, value_camera_free_value, value_camera_copy_value, value_camera_peek_pointer, "p", value_camera_collect_value, "p", value_camera_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (CameraClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) camera_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Camera), 0, (GInstanceInitFunc) camera_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType camera_type_id;
		camera_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Camera", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&camera_type_id__volatile, camera_type_id);
	}
	return camera_type_id__volatile;
}


gpointer camera_ref (gpointer instance) {
	Camera* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void camera_unref (gpointer instance) {
	Camera* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		CAMERA_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



