/* gamestate.c generated by valac 0.32.0, the Vala compiler
 * generated from gamestate.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <engine.h>
#include <SDL2/SDL_render.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_rect.h>
#include <tiled.h>
#include <gobject/gvaluecollector.h>


#define TYPE_GAME_STATE (game_state_get_type ())
#define GAME_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME_STATE, GameState))
#define GAME_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME_STATE, GameStateClass))
#define IS_GAME_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME_STATE))
#define IS_GAME_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME_STATE))
#define GAME_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME_STATE, GameStateClass))

typedef struct _GameState GameState;
typedef struct _GameStateClass GameStateClass;
typedef struct _GameStatePrivate GameStatePrivate;

#define TYPE_TEXTURE_MANAGER (texture_manager_get_type ())
#define TEXTURE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXTURE_MANAGER, TextureManager))
#define TEXTURE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXTURE_MANAGER, TextureManagerClass))
#define IS_TEXTURE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXTURE_MANAGER))
#define IS_TEXTURE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXTURE_MANAGER))
#define TEXTURE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXTURE_MANAGER, TextureManagerClass))

typedef struct _TextureManager TextureManager;
typedef struct _TextureManagerClass TextureManagerClass;

#define TYPE_FONT_MANAGER (font_manager_get_type ())
#define FONT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FONT_MANAGER, FontManager))
#define FONT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FONT_MANAGER, FontManagerClass))
#define IS_FONT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FONT_MANAGER))
#define IS_FONT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FONT_MANAGER))
#define FONT_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FONT_MANAGER, FontManagerClass))

typedef struct _FontManager FontManager;
typedef struct _FontManagerClass FontManagerClass;

#define TYPE_CAMERA (camera_get_type ())
#define CAMERA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CAMERA, Camera))
#define CAMERA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CAMERA, CameraClass))
#define IS_CAMERA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CAMERA))
#define IS_CAMERA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CAMERA))
#define CAMERA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CAMERA, CameraClass))

typedef struct _Camera Camera;
typedef struct _CameraClass CameraClass;
#define _engine_engine_unref0(var) ((var == NULL) ? NULL : (var = (engine_engine_unref (var), NULL)))
#define _camera_unref0(var) ((var == NULL) ? NULL : (var = (camera_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_TILEMAP_COMPONENT2 (tilemap_component2_get_type ())
#define TILEMAP_COMPONENT2(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TILEMAP_COMPONENT2, TilemapComponent2))
#define TILEMAP_COMPONENT2_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TILEMAP_COMPONENT2, TilemapComponent2Class))
#define IS_TILEMAP_COMPONENT2(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TILEMAP_COMPONENT2))
#define IS_TILEMAP_COMPONENT2_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TILEMAP_COMPONENT2))
#define TILEMAP_COMPONENT2_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TILEMAP_COMPONENT2, TilemapComponent2Class))

typedef struct _TilemapComponent2 TilemapComponent2;
typedef struct _TilemapComponent2Class TilemapComponent2Class;

#define RESOURCE_COMPONENT_TYPE_RESOURCE_TYPE (resource_component_resource_type_get_type ())

#define TYPE_RESOURCE_COMPONENT (resource_component_get_type ())
#define RESOURCE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RESOURCE_COMPONENT, ResourceComponent))
#define RESOURCE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RESOURCE_COMPONENT, ResourceComponentClass))
#define IS_RESOURCE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RESOURCE_COMPONENT))
#define IS_RESOURCE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RESOURCE_COMPONENT))
#define RESOURCE_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RESOURCE_COMPONENT, ResourceComponentClass))

typedef struct _ResourceComponent ResourceComponent;
typedef struct _ResourceComponentClass ResourceComponentClass;

#define TYPE_RESOURCE_LOADER_SYSTEM (resource_loader_system_get_type ())
#define RESOURCE_LOADER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RESOURCE_LOADER_SYSTEM, ResourceLoaderSystem))
#define RESOURCE_LOADER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RESOURCE_LOADER_SYSTEM, ResourceLoaderSystemClass))
#define IS_RESOURCE_LOADER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RESOURCE_LOADER_SYSTEM))
#define IS_RESOURCE_LOADER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RESOURCE_LOADER_SYSTEM))
#define RESOURCE_LOADER_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RESOURCE_LOADER_SYSTEM, ResourceLoaderSystemClass))

typedef struct _ResourceLoaderSystem ResourceLoaderSystem;
typedef struct _ResourceLoaderSystemClass ResourceLoaderSystemClass;

#define TYPE_TEXTURE_SYSTEM (texture_system_get_type ())
#define TEXTURE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXTURE_SYSTEM, TextureSystem))
#define TEXTURE_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXTURE_SYSTEM, TextureSystemClass))
#define IS_TEXTURE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXTURE_SYSTEM))
#define IS_TEXTURE_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXTURE_SYSTEM))
#define TEXTURE_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXTURE_SYSTEM, TextureSystemClass))

typedef struct _TextureSystem TextureSystem;
typedef struct _TextureSystemClass TextureSystemClass;

#define TYPE_MOVEMENT_SYSTEM (movement_system_get_type ())
#define MOVEMENT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MOVEMENT_SYSTEM, MovementSystem))
#define MOVEMENT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MOVEMENT_SYSTEM, MovementSystemClass))
#define IS_MOVEMENT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MOVEMENT_SYSTEM))
#define IS_MOVEMENT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MOVEMENT_SYSTEM))
#define MOVEMENT_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MOVEMENT_SYSTEM, MovementSystemClass))

typedef struct _MovementSystem MovementSystem;
typedef struct _MovementSystemClass MovementSystemClass;

#define TYPE_ANIMATION_SYSTEM (animation_system_get_type ())
#define ANIMATION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ANIMATION_SYSTEM, AnimationSystem))
#define ANIMATION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ANIMATION_SYSTEM, AnimationSystemClass))
#define IS_ANIMATION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ANIMATION_SYSTEM))
#define IS_ANIMATION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ANIMATION_SYSTEM))
#define ANIMATION_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ANIMATION_SYSTEM, AnimationSystemClass))

typedef struct _AnimationSystem AnimationSystem;
typedef struct _AnimationSystemClass AnimationSystemClass;

#define TYPE_COLLISION_SYSTEM (collision_system_get_type ())
#define COLLISION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COLLISION_SYSTEM, CollisionSystem))
#define COLLISION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COLLISION_SYSTEM, CollisionSystemClass))
#define IS_COLLISION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COLLISION_SYSTEM))
#define IS_COLLISION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COLLISION_SYSTEM))
#define COLLISION_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COLLISION_SYSTEM, CollisionSystemClass))

typedef struct _CollisionSystem CollisionSystem;
typedef struct _CollisionSystemClass CollisionSystemClass;

#define TYPE_RENDER_SYSTEM (render_system_get_type ())
#define RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RENDER_SYSTEM, RenderSystem))
#define RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RENDER_SYSTEM, RenderSystemClass))
#define IS_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RENDER_SYSTEM))
#define IS_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RENDER_SYSTEM))
#define RENDER_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RENDER_SYSTEM, RenderSystemClass))

typedef struct _RenderSystem RenderSystem;
typedef struct _RenderSystemClass RenderSystemClass;

#define TYPE_TILEMAP_RENDER_SYSTEM (tilemap_render_system_get_type ())
#define TILEMAP_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TILEMAP_RENDER_SYSTEM, TilemapRenderSystem))
#define TILEMAP_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TILEMAP_RENDER_SYSTEM, TilemapRenderSystemClass))
#define IS_TILEMAP_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TILEMAP_RENDER_SYSTEM))
#define IS_TILEMAP_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TILEMAP_RENDER_SYSTEM))
#define TILEMAP_RENDER_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TILEMAP_RENDER_SYSTEM, TilemapRenderSystemClass))

typedef struct _TilemapRenderSystem TilemapRenderSystem;
typedef struct _TilemapRenderSystemClass TilemapRenderSystemClass;

#define TYPE_TEXT_RENDER_SYSTEM (text_render_system_get_type ())
#define TEXT_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXT_RENDER_SYSTEM, TextRenderSystem))
#define TEXT_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXT_RENDER_SYSTEM, TextRenderSystemClass))
#define IS_TEXT_RENDER_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXT_RENDER_SYSTEM))
#define IS_TEXT_RENDER_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXT_RENDER_SYSTEM))
#define TEXT_RENDER_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXT_RENDER_SYSTEM, TextRenderSystemClass))

typedef struct _TextRenderSystem TextRenderSystem;
typedef struct _TextRenderSystemClass TextRenderSystemClass;
typedef struct _ParamSpecGameState ParamSpecGameState;

struct _GameState {
	GTypeInstance parent_instance;
	volatile int ref_count;
	GameStatePrivate * priv;
	EngineEngine* engine;
	Camera* ncamera;
};

struct _GameStateClass {
	GTypeClass parent_class;
	void (*finalize) (GameState *self);
	void (*create_map) (GameState* self, EngineEntity* map);
	void (*add_entities) (GameState* self);
	void (*add_systems) (GameState* self, TextureManager* t, FontManager* f, SDL_Renderer* r);
	void (*update) (GameState* self);
};

struct _GameStatePrivate {
	GeeList* _states;
};

typedef enum  {
	RESOURCE_COMPONENT_RESOURCE_TYPE_FONT
} ResourceComponentResourceType;

struct _ParamSpecGameState {
	GParamSpec parent_instance;
};


static gpointer game_state_parent_class = NULL;

gpointer game_state_ref (gpointer instance);
void game_state_unref (gpointer instance);
GParamSpec* param_spec_game_state (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_game_state (GValue* value, gpointer v_object);
void value_take_game_state (GValue* value, gpointer v_object);
gpointer value_get_game_state (const GValue* value);
GType game_state_get_type (void) G_GNUC_CONST;
GType texture_manager_get_type (void) G_GNUC_CONST;
GType font_manager_get_type (void) G_GNUC_CONST;
gpointer camera_ref (gpointer instance);
void camera_unref (gpointer instance);
GParamSpec* param_spec_camera (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_camera (GValue* value, gpointer v_object);
void value_take_camera (GValue* value, gpointer v_object);
gpointer value_get_camera (const GValue* value);
GType camera_get_type (void) G_GNUC_CONST;
#define GAME_STATE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_GAME_STATE, GameStatePrivate))
enum  {
	GAME_STATE_DUMMY_PROPERTY
};
GameState* game_state_construct (GType object_type, const gchar* map_filename, TextureManager* t, FontManager* f, SDL_Renderer* r);
Camera* camera_new (gint x, gint y, guint w, guint h);
Camera* camera_construct (GType object_type, gint x, gint y, guint w, guint h);
void game_state_add_entities (GameState* self);
void game_state_add_map (GameState* self, const gchar* map_filename);
void game_state_add_systems (GameState* self, TextureManager* t, FontManager* f, SDL_Renderer* r);
TilemapComponent2* tilemap_component2_new (TiledMap* map);
TilemapComponent2* tilemap_component2_construct (GType object_type, TiledMap* map);
GType tilemap_component2_get_type (void) G_GNUC_CONST;
void game_state_create_map (GameState* self, EngineEntity* map);
static void game_state_real_create_map (GameState* self, EngineEntity* map);
static void game_state_real_add_entities (GameState* self);
GType resource_component_resource_type_get_type (void) G_GNUC_CONST;
ResourceComponent* resource_component_new (const gchar* identifier, const gchar* filename, gint ptsize, ResourceComponentResourceType type);
ResourceComponent* resource_component_construct (GType object_type, const gchar* identifier, const gchar* filename, gint ptsize, ResourceComponentResourceType type);
GType resource_component_get_type (void) G_GNUC_CONST;
static void game_state_real_add_systems (GameState* self, TextureManager* t, FontManager* f, SDL_Renderer* r);
ResourceLoaderSystem* resource_loader_system_new (FontManager* fontManager);
ResourceLoaderSystem* resource_loader_system_construct (GType object_type, FontManager* fontManager);
GType resource_loader_system_get_type (void) G_GNUC_CONST;
TextureSystem* texture_system_new (SDL_Renderer* renderer, TextureManager* textureManager);
TextureSystem* texture_system_construct (GType object_type, SDL_Renderer* renderer, TextureManager* textureManager);
GType texture_system_get_type (void) G_GNUC_CONST;
MovementSystem* movement_system_new (Camera* camera);
MovementSystem* movement_system_construct (GType object_type, Camera* camera);
GType movement_system_get_type (void) G_GNUC_CONST;
AnimationSystem* animation_system_new (void);
AnimationSystem* animation_system_construct (GType object_type);
GType animation_system_get_type (void) G_GNUC_CONST;
CollisionSystem* collision_system_new (void);
CollisionSystem* collision_system_construct (GType object_type);
GType collision_system_get_type (void) G_GNUC_CONST;
RenderSystem* render_system_new (Camera* camera, SDL_Renderer* renderer, TextureManager* textureManager);
RenderSystem* render_system_construct (GType object_type, Camera* camera, SDL_Renderer* renderer, TextureManager* textureManager);
GType render_system_get_type (void) G_GNUC_CONST;
TilemapRenderSystem* tilemap_render_system_new (Camera* camera, SDL_Renderer* renderer, TextureManager* textureManager);
TilemapRenderSystem* tilemap_render_system_construct (GType object_type, Camera* camera, SDL_Renderer* renderer, TextureManager* textureManager);
GType tilemap_render_system_get_type (void) G_GNUC_CONST;
TextRenderSystem* text_render_system_new (FontManager* fontManager, SDL_Renderer* renderer);
TextRenderSystem* text_render_system_construct (GType object_type, FontManager* fontManager, SDL_Renderer* renderer);
GType text_render_system_get_type (void) G_GNUC_CONST;
void game_state_update (GameState* self);
static void game_state_real_update (GameState* self);
void game_state_togglePause (GameState* self);
static GeeList* game_state_get_states (GameState* self);
static void game_state_set_states (GameState* self, GeeList* value);
static void game_state_finalize (GameState* obj);


GameState* game_state_construct (GType object_type, const gchar* map_filename, TextureManager* t, FontManager* f, SDL_Renderer* r) {
	GameState* self = NULL;
	SDL_Rect camerarect = {0};
	SDL_Renderer* _tmp0_ = NULL;
	SDL_Rect _tmp1_ = {0};
	SDL_Rect _tmp2_ = {0};
	guint _tmp3_ = 0U;
	SDL_Rect _tmp4_ = {0};
	guint _tmp5_ = 0U;
	Camera* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	TextureManager* _tmp8_ = NULL;
	FontManager* _tmp9_ = NULL;
	SDL_Renderer* _tmp10_ = NULL;
	g_return_val_if_fail (map_filename != NULL, NULL);
	g_return_val_if_fail (t != NULL, NULL);
	g_return_val_if_fail (f != NULL, NULL);
	g_return_val_if_fail (r != NULL, NULL);
	self = (GameState*) g_type_create_instance (object_type);
	_tmp0_ = r;
	SDL_RenderGetViewport (_tmp0_, &_tmp1_);
	camerarect = _tmp1_;
	_tmp2_ = camerarect;
	_tmp3_ = _tmp2_.w;
	_tmp4_ = camerarect;
	_tmp5_ = _tmp4_.h;
	_tmp6_ = camera_new (0, 0, _tmp3_ / 4, _tmp5_ / 4);
	_camera_unref0 (self->ncamera);
	self->ncamera = _tmp6_;
	game_state_add_entities (self);
	_tmp7_ = map_filename;
	game_state_add_map (self, _tmp7_);
	_tmp8_ = t;
	_tmp9_ = f;
	_tmp10_ = r;
	game_state_add_systems (self, _tmp8_, _tmp9_, _tmp10_);
	return self;
}


void game_state_add_map (GameState* self, const gchar* map_filename) {
	EngineEntity* entity = NULL;
	EngineEngine* _tmp0_ = NULL;
	EngineEntity* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	TiledMap* _tmp3_ = NULL;
	TiledMap* _tmp4_ = NULL;
	TilemapComponent2* _tmp5_ = NULL;
	TilemapComponent2* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (map_filename != NULL);
	_tmp0_ = self->engine;
	_tmp1_ = engine_engine_createEntity (_tmp0_);
	entity = _tmp1_;
	_tmp2_ = map_filename;
	_tmp3_ = tiled_loadMap (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = tilemap_component2_new (_tmp4_);
	_tmp6_ = _tmp5_;
	engine_entity_add_component (entity, (EngineComponent*) _tmp6_);
	_g_object_unref0 (_tmp6_);
	_g_object_unref0 (_tmp4_);
	game_state_create_map (self, entity);
	_g_object_unref0 (entity);
}


static void game_state_real_create_map (GameState* self, EngineEntity* map) {
	g_critical ("Type `%s' does not implement abstract method `game_state_create_map'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void game_state_create_map (GameState* self, EngineEntity* map) {
	g_return_if_fail (self != NULL);
	GAME_STATE_GET_CLASS (self)->create_map (self, map);
}


static void game_state_real_add_entities (GameState* self) {
	EngineEntity* entity = NULL;
	EngineEngine* _tmp0_ = NULL;
	EngineEntity* _tmp1_ = NULL;
	ResourceComponent* _tmp2_ = NULL;
	ResourceComponent* _tmp3_ = NULL;
	_tmp0_ = self->engine;
	_tmp1_ = engine_engine_createEntity (_tmp0_);
	entity = _tmp1_;
	_tmp2_ = resource_component_new ("defaultfont", "data/default.ttf", 12, RESOURCE_COMPONENT_RESOURCE_TYPE_FONT);
	_tmp3_ = _tmp2_;
	engine_entity_add_component (entity, (EngineComponent*) _tmp3_);
	_g_object_unref0 (_tmp3_);
	_g_object_unref0 (entity);
}


void game_state_add_entities (GameState* self) {
	g_return_if_fail (self != NULL);
	GAME_STATE_GET_CLASS (self)->add_entities (self);
}


static void game_state_real_add_systems (GameState* self, TextureManager* t, FontManager* f, SDL_Renderer* r) {
	EngineEngine* _tmp0_ = NULL;
	FontManager* _tmp1_ = NULL;
	ResourceLoaderSystem* _tmp2_ = NULL;
	ResourceLoaderSystem* _tmp3_ = NULL;
	EngineEngine* _tmp4_ = NULL;
	SDL_Renderer* _tmp5_ = NULL;
	TextureManager* _tmp6_ = NULL;
	TextureSystem* _tmp7_ = NULL;
	TextureSystem* _tmp8_ = NULL;
	EngineEngine* _tmp9_ = NULL;
	Camera* _tmp10_ = NULL;
	MovementSystem* _tmp11_ = NULL;
	MovementSystem* _tmp12_ = NULL;
	EngineEngine* _tmp13_ = NULL;
	AnimationSystem* _tmp14_ = NULL;
	AnimationSystem* _tmp15_ = NULL;
	EngineEngine* _tmp16_ = NULL;
	CollisionSystem* _tmp17_ = NULL;
	CollisionSystem* _tmp18_ = NULL;
	EngineEngine* _tmp19_ = NULL;
	Camera* _tmp20_ = NULL;
	SDL_Renderer* _tmp21_ = NULL;
	TextureManager* _tmp22_ = NULL;
	RenderSystem* _tmp23_ = NULL;
	RenderSystem* _tmp24_ = NULL;
	EngineEngine* _tmp25_ = NULL;
	Camera* _tmp26_ = NULL;
	SDL_Renderer* _tmp27_ = NULL;
	TextureManager* _tmp28_ = NULL;
	TilemapRenderSystem* _tmp29_ = NULL;
	TilemapRenderSystem* _tmp30_ = NULL;
	EngineEngine* _tmp31_ = NULL;
	FontManager* _tmp32_ = NULL;
	SDL_Renderer* _tmp33_ = NULL;
	TextRenderSystem* _tmp34_ = NULL;
	TextRenderSystem* _tmp35_ = NULL;
	g_return_if_fail (t != NULL);
	g_return_if_fail (f != NULL);
	g_return_if_fail (r != NULL);
	_tmp0_ = self->engine;
	_tmp1_ = f;
	_tmp2_ = resource_loader_system_new (_tmp1_);
	_tmp3_ = _tmp2_;
	engine_engine_addSystem (_tmp0_, (EngineSystem*) _tmp3_);
	_g_object_unref0 (_tmp3_);
	_tmp4_ = self->engine;
	_tmp5_ = r;
	_tmp6_ = t;
	_tmp7_ = texture_system_new (_tmp5_, _tmp6_);
	_tmp8_ = _tmp7_;
	engine_engine_addSystem (_tmp4_, (EngineSystem*) _tmp8_);
	_g_object_unref0 (_tmp8_);
	_tmp9_ = self->engine;
	_tmp10_ = self->ncamera;
	_tmp11_ = movement_system_new (_tmp10_);
	_tmp12_ = _tmp11_;
	engine_engine_addSystem (_tmp9_, (EngineSystem*) _tmp12_);
	_g_object_unref0 (_tmp12_);
	_tmp13_ = self->engine;
	_tmp14_ = animation_system_new ();
	_tmp15_ = _tmp14_;
	engine_engine_addSystem (_tmp13_, (EngineSystem*) _tmp15_);
	_g_object_unref0 (_tmp15_);
	_tmp16_ = self->engine;
	_tmp17_ = collision_system_new ();
	_tmp18_ = _tmp17_;
	engine_engine_addSystem (_tmp16_, (EngineSystem*) _tmp18_);
	_g_object_unref0 (_tmp18_);
	_tmp19_ = self->engine;
	_tmp20_ = self->ncamera;
	_tmp21_ = r;
	_tmp22_ = t;
	_tmp23_ = render_system_new (_tmp20_, _tmp21_, _tmp22_);
	_tmp24_ = _tmp23_;
	engine_engine_addSystem (_tmp19_, (EngineSystem*) _tmp24_);
	_g_object_unref0 (_tmp24_);
	_tmp25_ = self->engine;
	_tmp26_ = self->ncamera;
	_tmp27_ = r;
	_tmp28_ = t;
	_tmp29_ = tilemap_render_system_new (_tmp26_, _tmp27_, _tmp28_);
	_tmp30_ = _tmp29_;
	engine_engine_addSystem (_tmp25_, (EngineSystem*) _tmp30_);
	_g_object_unref0 (_tmp30_);
	_tmp31_ = self->engine;
	_tmp32_ = f;
	_tmp33_ = r;
	_tmp34_ = text_render_system_new (_tmp32_, _tmp33_);
	_tmp35_ = _tmp34_;
	engine_engine_addSystem (_tmp31_, (EngineSystem*) _tmp35_);
	_g_object_unref0 (_tmp35_);
}


void game_state_add_systems (GameState* self, TextureManager* t, FontManager* f, SDL_Renderer* r) {
	g_return_if_fail (self != NULL);
	GAME_STATE_GET_CLASS (self)->add_systems (self, t, f, r);
}


static void game_state_real_update (GameState* self) {
	EngineEngine* _tmp0_ = NULL;
	_tmp0_ = self->engine;
	engine_engine_update (_tmp0_);
}


void game_state_update (GameState* self) {
	g_return_if_fail (self != NULL);
	GAME_STATE_GET_CLASS (self)->update (self);
}


void game_state_togglePause (GameState* self) {
	EngineEngine* _tmp0_ = NULL;
	EngineState _tmp1_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->engine;
	_tmp1_ = _tmp0_->state;
	if (_tmp1_ == ENGINE_STATE_PAUSED) {
		EngineEngine* _tmp2_ = NULL;
		_tmp2_ = self->engine;
		_tmp2_->state = ENGINE_STATE_RUNNING;
	} else {
		EngineEngine* _tmp3_ = NULL;
		EngineState _tmp4_ = 0;
		_tmp3_ = self->engine;
		_tmp4_ = _tmp3_->state;
		if (_tmp4_ == ENGINE_STATE_RUNNING) {
			EngineEngine* _tmp5_ = NULL;
			_tmp5_ = self->engine;
			_tmp5_->state = ENGINE_STATE_PAUSED;
		}
	}
}


static GeeList* game_state_get_states (GameState* self) {
	GeeList* result;
	GeeList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_states;
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void game_state_set_states (GameState* self, GeeList* value) {
	GeeList* _tmp0_ = NULL;
	GeeList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_states);
	self->priv->_states = _tmp1_;
}


static void value_game_state_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_game_state_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		game_state_unref (value->data[0].v_pointer);
	}
}


static void value_game_state_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = game_state_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_game_state_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_game_state_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		GameState* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = game_state_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_game_state_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	GameState** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = game_state_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_game_state (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecGameState* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_GAME_STATE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_game_state (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_GAME_STATE), NULL);
	return value->data[0].v_pointer;
}


void value_set_game_state (GValue* value, gpointer v_object) {
	GameState* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_GAME_STATE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_GAME_STATE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		game_state_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		game_state_unref (old);
	}
}


void value_take_game_state (GValue* value, gpointer v_object) {
	GameState* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_GAME_STATE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_GAME_STATE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		game_state_unref (old);
	}
}


static void game_state_class_init (GameStateClass * klass) {
	game_state_parent_class = g_type_class_peek_parent (klass);
	((GameStateClass *) klass)->finalize = game_state_finalize;
	g_type_class_add_private (klass, sizeof (GameStatePrivate));
	((GameStateClass *) klass)->create_map = game_state_real_create_map;
	((GameStateClass *) klass)->add_entities = game_state_real_add_entities;
	((GameStateClass *) klass)->add_systems = game_state_real_add_systems;
	((GameStateClass *) klass)->update = game_state_real_update;
}


static void game_state_instance_init (GameState * self) {
	EngineEngine* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	self->priv = GAME_STATE_GET_PRIVATE (self);
	_tmp0_ = engine_engine_new ();
	self->engine = _tmp0_;
	_tmp1_ = gee_array_list_new (TYPE_GAME_STATE, (GBoxedCopyFunc) game_state_ref, game_state_unref, NULL, NULL, NULL);
	self->priv->_states = (GeeList*) _tmp1_;
	self->ref_count = 1;
}


static void game_state_finalize (GameState* obj) {
	GameState * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_GAME_STATE, GameState);
	g_signal_handlers_destroy (self);
	_engine_engine_unref0 (self->engine);
	_camera_unref0 (self->ncamera);
	_g_object_unref0 (self->priv->_states);
}


GType game_state_get_type (void) {
	static volatile gsize game_state_type_id__volatile = 0;
	if (g_once_init_enter (&game_state_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_game_state_init, value_game_state_free_value, value_game_state_copy_value, value_game_state_peek_pointer, "p", value_game_state_collect_value, "p", value_game_state_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (GameStateClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) game_state_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GameState), 0, (GInstanceInitFunc) game_state_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType game_state_type_id;
		game_state_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GameState", &g_define_type_info, &g_define_type_fundamental_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&game_state_type_id__volatile, game_state_type_id);
	}
	return game_state_type_id__volatile;
}


gpointer game_state_ref (gpointer instance) {
	GameState* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void game_state_unref (gpointer instance) {
	GameState* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GAME_STATE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



