/* main.c generated by valac 0.32.0, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include <SDL2/SDL_timer.h>


#define TYPE_GAME (game_get_type ())
#define GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME, Game))
#define GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME, GameClass))
#define IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME))
#define IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME))
#define GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME, GameClass))

typedef struct _Game Game;
typedef struct _GameClass GameClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



#define FRAMES_PER_SECOND 30
#define FRAMEDURATION (1000 / FRAMES_PER_SECOND)
void _vala_main (gchar** argv, int argv_length1);
GType game_get_type (void) G_GNUC_CONST;
Game* game_new (gint width, gint height);
Game* game_construct (GType object_type, gint width, gint height);
gboolean game_is_running (Game* self);
void game_handle_events (Game* self);
void game_update (Game* self);
void game_quit (Game* self);


void _vala_main (gchar** argv, int argv_length1) {
	Game* game = NULL;
	Game* _tmp0_ = NULL;
	Game* _tmp11_ = NULL;
	SDL_Init ((guint32) SDL_INIT_EVERYTHING);
	TTF_Init ();
	_tmp0_ = game_new (640, 512);
	game = _tmp0_;
	while (TRUE) {
		Game* _tmp1_ = NULL;
		gboolean _tmp2_ = FALSE;
		guint32 start = 0U;
		guint32 _tmp3_ = 0U;
		Game* _tmp4_ = NULL;
		Game* _tmp5_ = NULL;
		guint32 end = 0U;
		guint32 _tmp6_ = 0U;
		guint32 duration = 0U;
		guint32 _tmp7_ = 0U;
		guint32 _tmp8_ = 0U;
		guint32 _tmp9_ = 0U;
		_tmp1_ = game;
		_tmp2_ = game_is_running (_tmp1_);
		if (!_tmp2_) {
			break;
		}
		_tmp3_ = SDL_GetTicks ();
		start = _tmp3_;
		_tmp4_ = game;
		game_handle_events (_tmp4_);
		_tmp5_ = game;
		game_update (_tmp5_);
		_tmp6_ = SDL_GetTicks ();
		end = _tmp6_;
		_tmp7_ = end;
		_tmp8_ = start;
		duration = _tmp7_ - _tmp8_;
		_tmp9_ = duration;
		if (_tmp9_ < ((guint32) FRAMEDURATION)) {
			guint32 _tmp10_ = 0U;
			_tmp10_ = duration;
			SDL_Delay (FRAMEDURATION - _tmp10_);
		}
	}
	_tmp11_ = game;
	game_quit (_tmp11_);
	_g_object_unref0 (game);
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	_vala_main (argv, argc);
	return 0;
}



